### ISSUE TITLE
#ifdef FIPS_MODE in openssl 1.1.1 !?

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#9252]
diff --git a/crypto/evp/e_aes.c b/crypto/evp/e_aes.c
index 68322e1982..e60d736b9c 100644
--- a/crypto/evp/e_aes.c
+++ b/crypto/evp/e_aes.c
@@ -59,6 +59,12 @@ typedef struct {
                     const unsigned char iv[16]);
 } EVP_AES_XTS_CTX;
 
+#ifdef FIPS_MODE
+static const int allow_insecure_decrypt = 0;
+#else
+static const int allow_insecure_decrypt = 1;
+#endif
+
 typedef struct {
     union {
         double align;

=======
so far so good but this is not vendor validation 

In openssl 1.1.1 FIPS is supported in vendor validation 
So I cannot understand code like above in mainstream.
Please ensure correct retrofit (backport) of new functionality .

**Comment by paulidale** [comment]
My mistake merging and not checkout the result closely enough.  I'll fix.

**Comment by mattcaswell** [comment]
Fixed by #9255
