### ISSUE TITLE
BN_is_prime_ex() has some issue while verifying KeyGen_186-3_RandomProbablyPrime3_3_KAT.txt

### ISSUE THREAD

**Issue by hareesh-d** [openssl/openssl#9256]
This Test vector has 186 cases and API can Successfully validate 185 cases (API return value matches as per the Test vector).
API returns Success even for the below case. Looks like a bug.
openssl1.1.1a is used for testing.

e = 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a43b41 
prandom = 0f8ccf4caf955ec6fff71fd81d232846d832ad12ebbdb5b9ade50241c354ffd6c59d154e9865437deda9ab7b779599724961cbfcaa11953ef24c74e0c47d3668f23173fb86fd4a64cdd62f87de7570ba6b685af34f2ebfc851898ad5a6d6ad42d3b15abcc68b47c1a48a93616aaf3c6e80a6c0d782bd5856a78294e5eae74d69 
qrandom = 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
Result = F (Step 4.4 p < Floor_SQRT2_TIMES_2Power_n_div_2_minus_1 so get another random number.)

**Comment by hareesh-d** [comment]
The above mentioned test vector is from NIST.
https://csrc.nist.gov/Projects/Cryptographic-Algorithm-Validation-Program/Digital-Signatures#rsa2vs

**Comment by bernd-edlinger** [comment]
That's funny, because sage 8.1 says P is a prime number:
```
./sage 
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 8.1, Release Date: 2017-12-07                     │
│ Type "notebook()" for the browser-based notebook interface.        │
│ Type "help()" for help.                                            │
└────────────────────────────────────────────────────────────────────┘
sage: P=0x0f8ccf4caf955ec6fff71fd81d232846d832ad12ebbdb5b9ade50241c354ffd6c59d15
....: 4e9865437deda9ab7b779599724961cbfcaa11953ef24c74e0c47d3668f23173fb86fd4a64
....: cdd62f87de7570ba6b685af34f2ebfc851898ad5a6d6ad42d3b15abcc68b47c1a48a93616a
....: af3c6e80a6c0d782bd5856a78294e5eae74d69
sage: is_prime(P)
True
sage: factor(P)
10919608129465258431265682886045856599825679969965042180269682401788772705200432958744613778646740439209587508052493681157983823366121051170713887754364146356579680520056411087961358137156157083670383687120468527714938391576583216559153635418432013513094815417478341066349121219462619529089563478964367215977
```

**Comment by t8m** [comment]
I think this can be closed.

**Comment by hareesh-d** [comment]
But I see only this function is used to validate the random numbers p, q
during RSA key generation. So, if we get such random numbers, means they
will be accepted as valid P and Q ?

**Comment by t8m** [comment]
The RSA key generation algorithm in OpenSSL-1.1.1 is not necessarily FIPS 186-4 compliant. The OpenSSL-1.1.1 cannot be FIPS validated without additional changes similar to the patches in Red Hat Enterprise Linux 8 OpenSSL-1.1.1 package.
