### ISSUE TITLE
SSL_VERIFY_POST_HANDSHAKE implicitly enables cert validation

### ISSUE THREAD

**Issue by tiran** [openssl/openssl#9259]
The flag ``SSL_VERIFY_POST_HANDSHAKE`` for [``SSL_CTX_set_verify``](https://www.openssl.org/docs/man1.1.1/man3/SSL_set_verify.html) is documented as ``Client mode: ignored``. I was under the impression that I can set the flag safely for client connections and OpenSSL would just ignore the flag.

However ``tls_process_server_certificate`` does not ignore the flag. ``SSL_VERIFY_POST_HANDSHAKE`` implicitly enables cert validation. The code comes with a long and good reasoning why it performs ``s->verify_mode != SSL_VERIFY_NONE``.

https://github.com/openssl/openssl/blob/743694a6c29e5a6387819523fad5e3b7e613f1ee/ssl/statem/statem_clnt.c#L1899-L1918

I have two proposals to address the issue:

1) Modify the check to ignore PHA and client once flags: ``(s->verify_mode & ~(SSL_VERIFY_CLIENT_ONCE|SSL_VERIFY_POST_HANDSHAKE)) != SSL_VERIFY_NONE``
2) Update the documentation and explain that the flags implicitly enable cert chain validation.

**Comment by tiran** [comment]
Also see https://github.com/python/cpython/pull/14421 and https://bugs.python.org/issue37428

**Comment by tiran** [comment]
@t8m Tomas, please take a look.

**Comment by t8m** [comment]
The manpage already states that:

BUGS
In client mode, it is not checked whether the SSL_VERIFY_PEER flag is set, but whether any flags are set. This can lead to unexpected behaviour if SSL_VERIFY_PEER and other flags are not used as required.

I'd just adjust the manpage to say Client mode: see BUGS
