### ISSUE TITLE
CONF vs CONF_W32 char classes

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#9263]
The whole CONF API isn't documented.

Config file parsing is done using character classes in a custom keytable. There are actually
TWO keytables in conf_def.h (generated by keysets.pl), one for windows and the default.

Should we remove the windows one?  There are subtle differences (six entries in particular), things like ```#``` being the comment in default and ```;``` being the comment in win32. Since this was never documented, should we remove support?

Going further, shouldn't we remove the custom keytype and use ctype?

See also #5672

**Comment by levitte** [comment]
The *not so subtle difference* is that `\` doesn't work as an escape on windows...

**Comment by richsalz** [comment]
Do we know if anyone is using the Win32 keytab?  (Silly question, of course we don't.) But backslash doesn't work on windows, it doesn't work on windows *if someone read the source and changed their application to call the undocumented function*  And also, the documentation in man5 only describes the default behavior (such as the comment and backslash)

Here are the six differences:

char | default | win32
---- | -------- | -----
`\` | escape | nothing
`#` | comment | nothing
`'` | quote | nothing
`;` | punctuation | comment
`"` | quote | double-quote
`` |quote | nothing

The last is ONLY a single-backtick, but I couldn't get the markdown right.

**Comment by levitte** [comment]
The point about `\` is that paths that are natural to windows users should work, i.e `C:\Some\Where\File.PEM`

**Comment by levitte** [comment]
I don't mind merging the rest, really. Also, we could use a pragma that sets the escape char, with the default to nothing for Windows, and `\` everywhere else. See #8882 regarding pragmas.

**Comment by richsalz** [comment]
I think config files should be portable across systems, except for pragma's.  I would like the code in conf to use ctype.

**Comment by richsalz** [comment]
But windows also takes ```/``` as a path separator. This windows keytab is not documented, won't work with the auto-init stuff anyway, and there is the slash workaround.

**Comment by levitte** [comment]
> won't work with the auto-init stuff anyway

I don't understand this bit. Have I missed something?

**Comment by richsalz** [comment]
I guess thinking about it a bit more, if an application knows to call
```
CONF_set_default_method(NCONF_WIN32());
```

Before any openssl init is done then it should work.  That requires reading the source to find the *two* undocumented functions, ignoring the existing docs about config file syntax, and knowing enough about the auto-init to make sure it's done first.  I'm gonna bet nobody is doing that.

**Comment by richsalz** [comment]
I also want to point out that the using ```NCONF_WIN32``` means that the config file installed during the OpenSSL build will not work because apps/openssl.cnf is copied into the install tree.

How about a PR to make that function deprecated?

**Comment by richsalz** [comment]
> How about a PR to make that NCONF_WIN32() deprecated?

#9578

**Comment by levitte** [comment]
> But windows also takes `/` as a path separator.

The only trouble I see is if someone uses an application that *does* use `NCONF_WIN32` and expects to be able to just copy and paste a file name into the corresponding config file...  the sudden sound of dragons...

Generally speaking, though, I agree with deprecating NCONF_WIN32, and would additionally like to see a pragma where you can specify an escape character (I fully expect to see that as a separate PR, and might even submit it :wink:)

**Comment by levitte** [comment]
> (as you already did at least one of the pragma's :)

... which no one seems to care too much about.  I'm still waiting for comments...

**Comment by mattcaswell** [comment]
This was resolved by #9578. Closing.
