### ISSUE TITLE
TLS1.3 how to negotiate the version?

### ISSUE THREAD

**Issue by Mengliuxx** [openssl/openssl#9290]
in the client and service side are open tls1.3,  choose anonymous algorithm,and  do not authenticate the peer, finally the negotiated version is tls1.2, so the negotiated version is also with the algorithm settings, certificate selection, whether the authentication peer and so on, there is a relationship?

**Comment by mattcaswell** [comment]
I'm not sure I understand the question. If both client and server are capable of TLSv1.3 then TLSv1.3 should always be negotiated (or a handshake failure occurs). The only exception to that which I can think of is if a server is only configured with a certificate which is not allowed to be used in TLSv1.3 for some reason (e.g. DSA cert, GOST cert, or ECDSA cert with brainpool curve). In that case TLSv1.3 is automatically disabled, and (typically) TLSv1.2 will be negotiated instead.

**Comment by InfoHunter** [comment]
And perhaps cipher suites? What will happen if TLS13 is enabled but no TLS13 capable cipher suites are configured?

**Comment by mattcaswell** [comment]
> And perhaps cipher suites? What will happen if TLS13 is enabled but no TLS13 capable cipher suites are configured?

Then the connection fails. Version negotiation happens first. We then attempt to find suitable ciphersuites/sigalgs etc.

**Comment by Mengliuxx** [comment]
> I'm not sure I understand the question. If both client and server are capable of TLSv1.3 then TLSv1.3 should always be negotiated (or a handshake failure occurs). The only exception to that which I can think of is if a server is only configured with a certificate which is not allowed to be used in TLSv1.3 for some reason (e.g. DSA cert, GOST cert, or ECDSA cert with brainpool curve). In that case TLSv1.3 is automatically disabled, and (typically) TLSv1.2 will be negotiated instead.

When I was testing, the server I set up did not load the certificate, so the negotiated version is TLS1.2. But I am not sure if there are factors other than the server certificate that also affect the negotiation of the TLS1.3 version.

**Comment by mattcaswell** [comment]
> When I was testing, the server I set up did not load the certificate, so the negotiated version is TLS1.2. But I am not sure if there are factors other than the server certificate that also affect the negotiation of the TLS1.3 version.

If the client offers TLSv1.3, and the server is configured to accept TLSv1.3, and the server has a TLSv1.3 capable certificate, then TLSv1.3 should be negotiated. Other factors such as ciphersuites/sigalgs etc may cause the connection to fail if there is no overlap between the set offered by the client and the set accepted by the server - but they should not cause a fallback to TLSv1.2.

**Comment by Mengliuxx** [comment]
> > When I was testing, the server I set up did not load the certificate, so the negotiated version is TLS1.2. But I am not sure if there are factors other than the server certificate that also affect the negotiation of the TLS1.3 version.
> 
> If the client offers TLSv1.3, and the server is configured to accept TLSv1.3, and the server has a TLSv1.3 capable certificate, then TLSv1.3 should be negotiated. Other factors such as ciphersuites/sigalgs etc may cause the connection to fail if there is no overlap between the set offered by the client and the set accepted by the server - but they should not cause a fallback to TLSv1.2.

ok, i see, thanks
