### ISSUE TITLE
crypto-secure-allocated is documented

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#9300]
```CRYPTO_secure_allocated``` is documented in man3/OPENSSL_secure_malloc.pod  Why does it show up in the "missingcrypto" files?

**Comment by levitte** [comment]
It's *kinda sorta* documented.  It's only mentioned in the RETURN VALUES section of `doc/man3/OPENSSL_secure_malloc.pod`, but *no mention* in NAME or SYNOPSIS.  That's why.

PR welcome :wink:

**Comment by richsalz** [comment]
AArgh!  Thanks.  PR #10523
