### ISSUE TITLE
Problems with execution of `openssl version`

### ISSUE THREAD

**Issue by jaimesaez97** [openssl/openssl#9302]
Hi there.

I am looking for the intergration of a new QKD cipher suite into the OpenSSL library, 
so for that I need to understand very well how it works.

I have found a [guide](https://wiki.openssl.org/index.php/How_to_Integrate_a_Symmetric_Cipher) to integrate a new cipher suite into the library, which is the case of *aria* cipher suite.

To understand exactly what steps should I take to integrate it, I am trying to extract it from the library, compile the new library without aria and, when I have proven its correct functioning, re-integrate *aria* step by step.

There are no failures on `./config`, `make`, but in `make tests` appears errors in some tests (`test_md2`, `test_ rc5`, `test_enc`, `test_gost`, `test_overhead`, `test_external_boringssl`, `test_external_krb5`, `test_external_pyca`).

I think everything is **ok** because the errors are not fatal (`md2 and rc5 not implemented on this version`, `no test GOST engine found`...), and in the `make install` step everything is ok.

Now, exploring the directory `/usr/local/`, you can find all the binaries and libraries that are listed in the file [INSTALL](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/INSTALL).

The **error** appears here:

                $ openssl version -a
                openssl: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

I understand this is out of the scope of the project, but ¿anyone can give me some advice? I am not able to find the error.

**Comment by mattcaswell** [comment]
Try:

````
LD_LIBRARY_PATH=/usr/local/lib openssl version
````

**Comment by romen** [comment]
To better understand what is happening and why Matt's advice works you should familiarize to how shared libraries work in Linux: http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html

**Comment by mattcaswell** [comment]
I'd also suggest carefully reading the file NOTES.UNIX

https://github.com/openssl/openssl/blob/master/NOTES.UNIX

In particular the section on "Shared libraries and installation in non-default locations"

**Comment by jaimesaez97** [comment]
Effectively this works, thank you all very much, I will.
