### ISSUE TITLE
a problem about engine

### ISSUE THREAD

**Issue by n0pn0pn0p** [openssl/openssl#9306]
hello! I want to add my own ECDSA with engine in openssl_1.1.1c, and i find a example in [openssl wiki](https://wiki.openssl.org/index.php/Creating_an_OpenSSL_Engine_to_use_indigenous_ECDH_ECDSA_and_HASH_Algorithms), but i find it is not fit for openssl_1.1.1c, because there is no `ECDSA_METHOD`,`ENGINE_set_ECDSA ` and so on in ossl_tpy.h, can you please issue a example using openssl_1.1.1c ?

**Comment by mattcaswell** [comment]
Use EC_KEY_METHOD instead. Create a new one using `EC_KEY_METHOD_new`. Set the various function pointers that are required using `EC_KEY_METHOD_set_init`, `EC_KEY_METHOD_set_keygen`, `EC_KEY_METHOD_set_sign`, `EC_KEY_METHOD_set_verify` etc.

Set the ENGINE to use the method using `ENGINE_set_EC`.

When cleaning up your engine be sure to free the EC_KEY_METHOD using `EC_KEY_METHOD_free`.

**Comment by n0pn0pn0p** [comment]
Thx very much, I'll have a try it !

**Comment by asifmds** [comment]
Hello ! I'm trying to implement ECDSA algo using EC_KEY_METHOD.  can I get sample code for this ?
