### ISSUE TITLE
Undefined reference to EVP_aria_128_gcm

### ISSUE THREAD

**Issue by jaimesaez97** [openssl/openssl#9307]
Good morning.

I am re-integrating the ARIA cihper suite into OpenSSL library (for testing purposes) and I get a fatal error on a undefined reference to `EVP_aria_128_gcm` and `EVP_aria_256_gcm`.

- How is possible ARIA CCM has been well integrated and GCM has not?
- Where is the integration of GCM and CCM in the EVP interface?

I have copied the [e_aria.c](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/crypto/evp/e_aria.c) and I can not understand it.

I copy the `sudo make` statement output:

```
${LDCMD:-gcc} -pthread -m64 -Wa,--noexecstack -Wall -O3 -L.   \
        -o apps/openssl apps/asn1pars.o apps/ca.o apps/ciphers.o apps/cms.o apps/crl.o apps/crl2p7.o apps/dgst.o apps/dhparam.o apps/dsa.o apps/dsaparam.o apps/ec.o apps/ecparam.o apps/enc.o apps/engine.o apps/errstr.o apps/gendsa.o apps/genpkey.o apps/genrsa.o apps/nseq.o apps/ocsp.o apps/openssl.o apps/passwd.o apps/pkcs12.o apps/pkcs7.o apps/pkcs8.o apps/pkey.o apps/pkeyparam.o apps/pkeyutl.o apps/prime.o apps/rand.o apps/rehash.o apps/req.o apps/rsa.o apps/rsautl.o apps/s_client.o apps/s_server.o apps/s_time.o apps/sess_id.o apps/smime.o apps/speed.o apps/spkac.o apps/srp.o apps/storeutl.o apps/ts.o apps/verify.o apps/version.o apps/x509.o \
         apps/libapps.a -lssl -lcrypto -ldl -pthread
./libssl.so: undefined reference to `EVP_aria_128_gcm'
./libssl.so: undefined reference to `EVP_aria_256_gcm'
collect2: error: ld returned 1 exit status
Makefile:6441: recipe for target 'apps/openssl' failed
make[1]: *** [apps/openssl] Error 1
make[1]: Leaving directory '/home/osm/Coupling/openssl'
Makefile:172: recipe for target 'all' failed
make: *** [all] Error 2
```

Thank you all.

**Comment by jaimesaez97** [comment]
I have all the fork proyect updated on [my github](https://github.com/openssl/openssl), but 
I copy the files that I think may contain the error to make it easier.

- [Aria EVP Interface](https://github.com/openssl/openssl/tree/OpenSSL_1_1_1-stable/crypto/evp/e_aria.c)
- [Objects ID](https://github.com/openssl/openssl/tree/OpenSSL_1_1_1-stable/crypto/objects/objects.txt)

**Comment by mattcaswell** [comment]
- Is the file e_aria.c being built? (i.e. is there a ".o" file?)
- Did you run "make update" to add the functions to "util/libcrypto.num"?

**Comment by jaimesaez97** [comment]
> * Is the file e_aria.c being built? (i.e. is there a ".o" file?)

Yes, it is being built.

> * Did you run "make update" to add the functions to "util/libcrypto.num"?

I have done and this is the output of `$ make update`:
```
osm@osm:~/Coupling/openssl$ sudo make update
( cd .; /usr/bin/perl VMS/VMSify-conf.pl \
                        < apps/openssl.cnf > apps/openssl-vms.cnf )
( cd .; /usr/bin/perl crypto/bn/bn_prime.pl > crypto/bn/bn_prime.h )
( cd .; /usr/bin/perl crypto/objects/objects.pl -n \
                        crypto/objects/objects.txt \
                        crypto/objects/obj_mac.num \
                        > crypto/objects/obj_mac.new && \
    mv crypto/objects/obj_mac.new crypto/objects/obj_mac.num )
( cd .; /usr/bin/perl crypto/objects/objects.pl \
                        crypto/objects/objects.txt \
                        crypto/objects/obj_mac.num \
                        > include/openssl/obj_mac.h )
( cd .; /usr/bin/perl crypto/objects/obj_dat.pl \
                        include/openssl/obj_mac.h \
                        > crypto/objects/obj_dat.h )
( cd .; /usr/bin/perl crypto/objects/objxref.pl \
                        crypto/objects/obj_mac.num \
                        crypto/objects/obj_xref.txt \
                        > crypto/objects/obj_xref.h )
( cd .; /usr/bin/perl crypto/conf/keysets.pl \
                        > crypto/conf/conf_def.h )
( cd .; /usr/bin/perl crypto/asn1/charmap.pl \
                        > crypto/asn1/charmap.h )
( cd .; /usr/bin/perl fuzz/mkfuzzoids.pl \
                        crypto/objects/obj_dat.h \
                        > fuzz/oids.txt )
( b=`pwd`; set -e; cd .; \
          /usr/bin/perl util/ck_errf.pl -strict -internal; \
          /usr/bin/perl -I$b util/mkerr.pl  -internal )
( b=`pwd`; set -e; cd ./engines; \
          for E in *.ec ; do \
              /usr/bin/perl ../util/ck_errf.pl -strict \
                -conf $E `basename $E .ec`.c; \
              /usr/bin/perl -I$b ../util/mkerr.pl  -static \
                -conf $E `basename $E .ec`.c ; \
          done )
( b=`pwd`; cd .; /usr/bin/perl -I$b util/mkdef.pl crypto update )
LIBCRYPTO: No new symbols added
( b=`pwd`; cd .; /usr/bin/perl -I$b util/mkdef.pl ssl update )
LIBSSL: No new symbols added
```

After, on the execution of `$ sudo make` I get a new error:

```
make[1]: *** Deleting file 'apps/pkeyparam.o'
Makefile:6656: recipe for target 'apps/pkeyparam.o' failed
make[1]: *** [apps/pkeyparam.o] Interrupt
Makefile:172: recipe for target 'all' failed
make: *** [all] Interrupt
```

But after, I run again `$ sudo make` whithout any changes and it is correct, or so it seems.

Thank you very much!!

**Comment by mattcaswell** [comment]
That's quite odd. I'd suggest you use "make clean" when getting strange output like that, and start the build again.

**Comment by bowensd** [comment]
@mattcaswell @jaimesaez97  I'm sorry to bother you guys.It seems that I did as what jaimesaez97 did.I implemented a new evp interface EVP_sm4_128_gcm()，and run make update or make clean ，but it doesn't seem to work. The build error shows that:


make depend && make _all
make[1]: Entering directory '/home/bowen/openssl-1.1.1d'
make[1]: Leaving directory '/home/bowen/openssl-1.1.1d'
make[1]: Entering directory '/home/bowen/openssl-1.1.1d'
rm -f apps/openssl
${LDCMD:-gcc} -pthread -m64 -Wa,--noexecstack -Wall -O3 -L.   \
	-o apps/openssl apps/asn1pars.o apps/ca.o apps/ciphers.o apps/cms.o apps/crl.o apps/crl2p7.o apps/dgst.o apps/dhparam.o apps/dsa.o apps/dsaparam.o apps/ec.o apps/ecparam.o apps/enc.o apps/engine.o apps/errstr.o apps/gendsa.o apps/genpkey.o apps/genrsa.o apps/nseq.o apps/ocsp.o apps/openssl.o apps/passwd.o apps/pkcs12.o apps/pkcs7.o apps/pkcs8.o apps/pkey.o apps/pkeyparam.o apps/pkeyutl.o apps/prime.o apps/rand.o apps/rehash.o apps/req.o apps/rsa.o apps/rsautl.o apps/s_client.o apps/s_server.o apps/s_time.o apps/sess_id.o apps/smime.o apps/speed.o apps/spkac.o apps/srp.o apps/storeutl.o apps/ts.o apps/verify.o apps/version.o apps/x509.o \
	 apps/libapps.a -lssl -lcrypto -ldl -pthread 
./libssl.so: undefined reference to `EVP_sm4_128_gcm'
collect2: error: ld returned 1 exit status
Makefile:6459: recipe for target 'apps/openssl' failed
make[1]: *** [apps/openssl] Error 1
make[1]: Leaving directory '/home/bowen/openssl-1.1.1d'
Makefile:174: recipe for target 'all' failed
make: *** [all] Error 2

I checked "util/libcrypto.num" and my algorithm has been added.
So how to solve this ?It troubles me a couple of days.Thanks!

**Comment by paulidale** [comment]
New `EVP_xxx` algorithm descriptor functions are not being added.  This isn't going to change.
Fetch the algorithm by name instead.

**Comment by kaduk** [comment]
To expand a bit on the previous comment, you will need to change your implementation strategy if you are looking to make a submission that will be accepted upstream; it will only be available by, e.g., `EVP_CIPHER_fetch(., "algorithm name", "")`.
With respect to the mechanics of the libcrypto.num update and linker error, you need to make sure that the library is rebuilt after `make update`.

**Comment by bowensd** [comment]
Thanks for advice.I notes that my OPENSSL version is `OpenSSL 1.1.1d  10 Sep 2019` ,there is not `EVP_CIPHER_fetch()`，If there is some other way? Thanks ~

**Comment by paulidale** [comment]
Try `EVP_get_cipherbyname()`.

**Comment by bowensd** [comment]
You are right.I'm grateful to your help.Thanks a lot!
