### ISSUE TITLE
Add support for ECIES scheme

### ISSUE THREAD

**Issue by dima91** [openssl/openssl#9314]
Hello everyone,
has been ECIES scheme already implemented in openssl? I need it to implement an ETSI standard and, more specifically, to realize communications with a PKI.

**Comment by Xor-el** [comment]
Not yet, the problem with implementing ECIES is that there are quite a lot of defined standards with none to govern them all.
That been said, the required components to implement it by yourself are already available in OpenSSL which are ECDH, ECDSA, HMAC, and any reasonable symmetric encryption algorithm preferably (AES).
So in reality, you just have to pick a choice in the sea of various standards and implement it yourself.

**Comment by dima91** [comment]
Ok, thanks for the quick response! I'll try to implement it.
