### ISSUE TITLE
Incorrect RAND_set_rand_method documentation.

### ISSUE THREAD

**Issue by shawnw** [openssl/openssl#9316]
The [documentation](https://www.openssl.org/docs/manmaster/man3/RAND_set_rand_method.html) for `RAND_set_rand_method()`  says it doesn't return anything, But the function actually returns an int ([Header](https://github.com/openssl/openssl/blob/master/include/openssl/rand.h#L31), [Source](https://github.com/openssl/openssl/blob/master/crypto/rand/rand_lib.c#L706)), the usual OpenSSL convention of 1 for success, 0 for error.

**Comment by paulidale** [comment]
Feel free to submit a pull request correcting this.......

**Comment by mspncp** [comment]
This issue was fixed by @agnosticdev in #9351.
