### ISSUE TITLE
support "expected failure" for test framework 

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#9330]
Current master(2019-07-09) fail on cygwin. In brief failure is verbose mode is:
...
DSO_dsobyaddr() failed
../../util/shlib_wrap.sh ../../test/shlibloadtest.exe -dso_ref cygcrypto-3.dll cygssl-3.dll ...
not ok 7 - running shlibloadtest -dso_ref ...
...
Comment in test/shlibloadtest.c explains failure "We are not testing this on Windows, because it is done there in a completely different way. Especially as a call to DSO_dsobyaddr() will always return an error, because DSO_pathbyaddr() is not implemented there."

With other word "shlibloadtest -dso_ref " is expected to fail on windows platforms.

Goal of request is in similar cases some tests to be marked that are expected to fail. Skip or error is not enough.

**Comment by kroeckx** [comment]
Not having looked at what this PR does, maybe you want to change
the test itself to return success in case calling the function
failed.

**Comment by levitte** [comment]
> Not having looked at what this PR does

Side note: This is not a PR

**Comment by petrovr** [comment]
I'm not convinced that change of test "C-code" to return success is acceptable. This will make test "false positive" and users will assume that all is correct. This is one of reasons to not report issue as defect.

Another solution is to exclude this tests from 90-test_shlibload.t. Question is how?
Currently reasons(statuses) are pass(ok), fail, and skip. Skip does not looks good to me.
And so I decided to ask for an enhancement - new reasons "expected failure".

If enhancement requires lot of work let then close and I will open a defect - just to skip test on OS <...>

**Comment by kroeckx** [comment]
Expected failure to me sounds like: it's broken, we know it, we're
going to just ignore that it's broken. It would also introduce the
unexpected success case.

But from what I understand, it's just never going to work on that
platform. So the expected reply on that platform is that it
returns an error. So we can test that it returns the error we
expect it to return. We already do various negative tests, they
are just as important as positive tests, but maybe not in this
case.

The other alternative is that we skip the test, because the test
doesn't make sense for that platform. And I suggest you go that
way.

**Comment by petrovr** [comment]
Additional review of code shows that "shlibloadtes" does not look like regression tests. It look like more functional (capability) tests. Such tests could be executed at configuration time. Unfortunately OpenSSL build system does not run functional test at configuration time

At end of test we see '#if defined(DSO_DLFCN) || defined(DSO_WIN32)'. "-dso_ref" is only for DSO_DLFCN. This test is not general.

Perhaphs it could be excluded from 'regular' tests and added to 'extended' tests, i.e. test that user could run explicitly.

**Comment by levitte** [comment]
Is this issue still current?

**Comment by petrovr** [comment]
This is not issue.
It is feature request for enhancement of test suite.

I prefer to close now. May be in the future.
