### ISSUE TITLE
Re-organizing the source tree

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#9331]

**Comment by richsalz** [comment]
This is to start discussion on how to re-org the OpenSSL source tree.  It was started because of feedback in #8211 and #9150, and also because #8919 was done.

Here are some suggested guidelines:

1. A directory should, ideally, only have files or sub-directories.
1. An exception to this is ```asm``` subdirectories which have assembler versions of the C code.
1. There should be a ```utils``` directory
1. The ```utils``` directory should be at the same level as ```ssl``` and ```crypto```
1. Maybe there should be a ```sys``` or ```platform``` directory, with sub-dirs for platforms with large "differences" from the main systems; this would be Windows and VMS.
1. Variants within Linux/Unix should probably be handled by ifdef controls within individual files
1. A new ```common``` directory might have files that are common to the providers that OpenSSL ships with (default and FIPS)

**Comment by richsalz** [comment]
Move ```e_os.h``` to ```include/internal``` (point 1 above)

**Comment by beldmit** [comment]
My 2 cents.

1. Totally agree, speaking about C sources/headers.
3-4. I sometimes used low-level non crypto-related OpenSSL primitives in small projects. I think there are currently more or less universal code, such as LHASH or STACK, and some code that cant'beused out of OpenSSL scope. It's worth to treat them separately.

**Comment by mspncp** [comment]
FWIW: pull request #9333 seems to be closely related to this issue.

**Comment by levitte** [comment]
If we want to be like that, I would like to see a `core` directory with the stuff that's absolutely central and cannot be disabled.

I'm not sure about having things spread out in the top directory, though. `crypto` contains everything that should go into libcrypto (apart from built in engines and providers), and `ssl` contains everything that should go into libssl. That's fairly easy to understand... But it's worth discussing.

**Comment by levitte** [comment]
I for one would like to keep the library (libcrypto / libssl) stuff and the apps stuff separated.

**Comment by levitte** [comment]
PR for somewhat better libapps structure coming up

**Comment by levitte** [comment]
(there's going to be further work on libapps, apps.c needs to be split, but that will be for another PR, 'cause it's *hard* work)

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev barring further input
