### ISSUE TITLE
Remove I_CAN_LIVE_WITH_LNK4049

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#9332]
In e_os.h there is the following:

```
#    elif _MSC_VER<1300 && defined(I_CAN_LIVE_WITH_LNK4049)
```

Looking at https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B, it appears that this is for MSVC *older than* Visual Studio .NET 2002 version 7.0

I think this renaming of stdin/out/err and such should be removed because of the age, and because this is a completely undocumented compile flag.  (A web search shows it only appearing in this file, as far as I can tell.)

**Comment by RameshwarapuSanthosh** [comment]
good first issue
