### ISSUE TITLE
Android compilation no longer works with just a standalone toolchain

### ISSUE THREAD

**Issue by rhardih** [openssl/openssl#9337]
Previously for 1.0.2p I've been able to successfully compile everything, with an architecture specific toolchain, but I guess since ebea0f3014c5f19573afc7a8746278b557e5a1f5, now the *entire* NDK is required to compile OpenSSL.

From the comment below this check in the configure script:

https://github.com/openssl/openssl/blob/7a228c391e0a35e1dc1223e3af3371968376857b/Configurations/15-android.conf#L33

It seems to allude to differentiating between an NDK and a standalone toolchain, but the failure case tests for presence of both **platforms** and **AndroidVersion.txt**, which I'm confused about.

Is there a specific reason that makes having the entire NDK a requirement, instead of just just a specific toolchain?

cc @dot-asm @levitte

**Comment by petrovr** [comment]
Expression is same even in master.
My recent builds was with NDK r15c, r17c and now r19c. Actually I decided to build 1.1* releases. 
May be issue in not on this line.

**Comment by rhardih** [comment]
I realised my build system was relying on r10e, which predates having AndroidVersion.txt, that was the reason I couldn't figure it out. r15c seems to work. 👍
