### ISSUE TITLE
pvk processing

### ISSUE THREAD

**Issue by kinichiro** [openssl/openssl#9338]
- In i2b_PVK(), EVP_Decrypt is used instead of EVP_Encrypt
- In i2b_PVK_bio(), return value handling seems not good

```diff
diff --git a/crypto/pem/pvkfmt.c b/crypto/pem/pvkfmt.c
index 348a92b64a..0ca7ee2ef1 100644
--- a/crypto/pem/pvkfmt.c
+++ b/crypto/pem/pvkfmt.c
@@ -841,9 +841,9 @@ static int i2b_PVK(unsigned char **out, EVP_PKEY *pk, int enclevel,
         if (!EVP_EncryptInit_ex(cctx, EVP_rc4(), NULL, keybuf, NULL))
             goto error;
         OPENSSL_cleanse(keybuf, 20);
-        if (!EVP_DecryptUpdate(cctx, p, &enctmplen, p, pklen - 8))
+        if (!EVP_EncryptUpdate(cctx, p, &enctmplen, p, pklen - 8))
             goto error;
-        if (!EVP_DecryptFinal_ex(cctx, p + enctmplen, &enctmplen))
+        if (!EVP_EncryptFinal_ex(cctx, p + enctmplen, &enctmplen))
             goto error;
     }
 
@@ -871,11 +871,11 @@ int i2b_PVK_bio(BIO *out, EVP_PKEY *pk, int enclevel,
         return -1;
     wrlen = BIO_write(out, tmp, outlen);
     OPENSSL_free(tmp);
-    if (wrlen == outlen) {
+    if (wrlen != outlen) {
         PEMerr(PEM_F_I2B_PVK_BIO, PEM_R_BIO_WRITE_FAILURE);
-        return outlen;
+        return -1;
     }
-    return -1;
+    return outlen;
 }
 
 # endif
```

pvk support seems to be removed by PR #9234 soon, though.

**Comment by levitte** [comment]
I'm actually amazed that someone found this, after PVK files being deprecated for...  how long is it now?

**Comment by levitte** [comment]
> pvk support seems to be removed by PR #9234 soon, though.

Yes, but it should still be fixed in 1.1.1

**Comment by quiret** [comment]
Is this why I am getting this error?

22484:error:060A6094:digital envelope routines:EVP_DecryptUpdate:invalid operation:crypto\evp\evp_enc.c:451:

By the way, PVK is the only key file supported by makecert?

**Comment by mattcaswell** [comment]
> Is this why I am getting this error?

Quite possibly.

> By the way, PVK is the only key file supported by makecert?

Interesting!

**Comment by romen** [comment]
@kinichiro would you be willing to open a PR with your proposed patch?

**Comment by mattcaswell** [comment]
@levitte already created a PR in #10521.
