### ISSUE TITLE
API and comand line tool not in sync for PEM_write_bio_RSAPrivateKey call

### ISSUE THREAD

**Issue by tuxmaster5000** [openssl/openssl#9344]
Versions with the problem: 1.0.2s, 1.1.0k
using PEM_write_bio_RSAPrivateKey an pem file with an aes256 GCM encrypted private key can created. This will work like expected. But the command line tool openss rsa  can't read this file, because it only can handle cbc aes256 protected keys.

Sample:
openssl rsa -text -noout -in /tmp/ss
unable to load Private Key
140421883557776:error:0906B072:PEM routines:PEM_get_EVP_CIPHER_INFO:unsupported encryption:pem_lib.c:550:

I have create an sample key for testing , using the password 12345678 for the developers.
[ss.txt](https://github.com/openssl/openssl/files/3380357/ss.txt)

**Comment by levitte** [comment]
Sorry for the late answer.

`openssl rsa` is aged and superseded by `openssl pkey`, please try that instead.
