### ISSUE TITLE
EVP_DigestInit_ex:initialization error for rmd160

### ISSUE THREAD

**Issue by vt-alt** [openssl/openssl#9349]
1. openssl/master at 164c51f built from sources.
2. `./config -d shared`
```
Operating system: x86_64-whatever-linux2
Configuring OpenSSL version 3.0.0-dev for target linux-x86_64
```
3. `perl configdata.pm --dump` shows `Enabled features:` `rmd160`.

Reproduce:
```
~/src/openssl (master)$ apps/openssl rmd160
Error setting digest
00:74:03:D3:8E:7F:00:00:error:06080086:digital envelope routines:EVP_DigestInit_ex:initialization error:crypto/evp/digest.c:180:
```

**Comment by levitte** [comment]
This happens because we have moved rmd160 to the legacy provider, which is currently not loaded by default.  There's currently no way to change that, but there should be.

**Comment by mattcaswell** [comment]
For the moment (on master) you have to load and unload the legacy provider explicitly in order to be able to use rmd160. So, somewhere at the beginning of your application you might do:

````
    OSSL_PROVIDER *prov = OSSL_PROVIDER_load(NULL, "legacy");
````

And then, before your application exits:

````
    OSSL_PROVIDER_unload(prov);
````

Eventually, there will be better ways to do this - but they've not been implemented yet on master.

**Comment by levitte** [comment]
Do note, @mattcaswell, that @vt-alt is trying to run *our* application.

**Comment by levitte** [comment]
(BTW, I'm looking into this for the moment.  This is related to our ambition to load the config file automagically)

**Comment by vt-alt** [comment]
Thanks for explanations. But, maybe the error message should be more meaningful?

**Comment by beldmit** [comment]
> (BTW, I'm looking into this for the moment. This is related to our ambition to load the config file automagically)

Yesss!
3+ ways to enforce the config to be loaded in 1.0, 1.1.0, 1.1.1 made me a bit crazy :)

**Comment by levitte** [comment]
@beldmit, so a forth way is the answer, eh?

Ref: https://xkcd.com/927/

:wink:

**Comment by mattcaswell** [comment]
> Do note, @mattcaswell, that @vt-alt is trying to run our application.

Oh..yes - sorry. Missed that aspect.

**Comment by vt-alt** [comment]
Actually, I tried to use `rmd160` for [ima-evm-utils](https://github.com/vt-alt/ima-evm-utils) but it reproduced easily with `openssl` with the same error message, so explanation was useful.

**Comment by mattcaswell** [comment]
Config file loading is now automatic, so this issue could be resolved by modifying a config file. Possibly a better answer would be for us to add a "-provider" flag to the apps to be able to specify the providers you want on the command line without having to edit a config file.

**Comment by richsalz** [comment]
Is #10435 the same issue as this one?

**Comment by mattcaswell** [comment]
> Is #10435 the same issue as this one?

Yes

**Comment by ismail** [comment]
Why is this closed? Is there a new API or similar to enable these insecure ciphers?

**Comment by paulidale** [comment]
It looks like the question has been answered three ways:

- loading on the command line with the `-provider` option;
- loading via the configuration file and
- loading using the OSSL_PROVIDER_load() function call.

What more of a response is required?
