### ISSUE TITLE
compiling openssl-1.0.2g with 'no-tls' option (disable TLS-1.0, like no-ssl2, no-ssl3 options) failed

### ISSUE THREAD

**Issue by JackieXie168** [openssl/openssl#935]
Hi,

I'm using openssl version 1.0.2g, and I'm trying to compile it with no-tls options. Unfortunately, every time I try to do this, I get the following error messages:

cc -I../crypto -I.. -I../include  -fPIC -fno-common -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DDSO_DLFCN -DHAVE_DLFCN_H -DOPENSSL_NO_ERR -arch x86_64 -O3 -DL_ENDIAN -Wall -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM   -c -o s2_meth.o s2_meth.c
In file included from s2_meth.c:59:
./ssl_locl.h:568:5: error: unknown type name 'custom_ext_add_cb'
    custom_ext_add_cb add_cb;
    ^
./ssl_locl.h:569:5: error: unknown type name 'custom_ext_free_cb'
    custom_ext_free_cb free_cb;
    ^
./ssl_locl.h:571:5: error: unknown type name 'custom_ext_parse_cb'
    custom_ext_parse_cb parse_cb;
    ^
3 errors generated.
<builtin>: recipe for target 's2_meth.o' failed
make[1]: *** [s2_meth.o] Error 1

Please encountered this error or can someone help please?

Thanks,
Jackie

**Comment by mattcaswell** [comment]
Fixed in  847fe929.
