### ISSUE TITLE
ssl_shutdown causes block/hung while calling second time

### ISSUE THREAD

**Issue by SK851831** [openssl/openssl#9354]
Hi, 

Integrated openssl 1.0.2r to an application and using this, established a connection between a Secure syslog server and my application.
When  I tried to exit the SSL3 TLS handshake by calling SSL_shutdown twice (Bi directional), application gets hung for a long time.
This hung is only seen when TLS connection is already established and the reachability between  my application and the syslog server goes down after.

**Comment by SK851831** [comment]
This issue is seen only after 1.0.2r integration.

**Comment by mattcaswell** [comment]
> When I tried to exit the tlsv3 handshake by calling SSL_shutdown twice

I'm not sure what you mean by tlsv3 since there is no such thing. Probably you mean sslv3? Or possibly TLSv1.3 (but that is not supported by 1.0.2).

**Comment by SK851831** [comment]
Apology. Its SSLv3 TLS handshake. Edited

**Comment by kroeckx** [comment]
Which version worked for you?

Are you sure that the shutdown was successful before?

Since you say this is about syslog, does the client only write, and the server never sends data back?

In any case, I suggest you read the manpage of SSL_shutdown as it is now. It's been rewritten, and if you follow what that says it should work properly if you move to TLS 1.3: https://www.openssl.org/docs/manmaster/man3/SSL_shutdown.html

**Comment by SK851831** [comment]
Can any one give me any push start?
After first SSL_shutdown() Got SSL_ERROR_SYSCALL error code in SSL_get_error() in both cases(Either other side is reachable or not reachable) but for only one case(Reachable) second SSL_shutdown() worked without being hung all time

**Comment by SK851831** [comment]
Worked version was OPENSSL 1.0.2o

**Comment by kroeckx** [comment]
If you get that error, it means that the connection was not
succesfully shut down, you should not call shutdown again.
There was a bug that calling shutdown again would make that
error go away.

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
