### ISSUE TITLE
check_issued() with X509_V_ERR_PATH_LOOP 

### ISSUE THREAD

**Issue by cacamille3** [openssl/openssl#9367]
I have some code that use `X509_STORE_CTX_get_get_issuer()`
I switched from OpenSSL 1.0.2 to 1.1.1 and since then the function do not return the same result.
I could see the change is in [check_issued()](https://github.com/openssl/openssl/blob/baba1545105131fa34068f62928322e99d695ab1/crypto/x509/x509_vfy.c#L328) and that it does not return anymore 1 (OK) but 0 (NOT Ok) in my case.

In my case am I have an OPC UA Server and I connect from an OPC UA Client having a certificate signed by a Root certificate.
I have the root certificate in the store of the OPC UA Server.
The Server is at some point calling `X509_STORE_CTX_get_get_issuer()` to verify if it might trust the client trying to connect.
This was working with OpenSSL 1.0.2 but does not work anymore with 1.1.1

I could see a [change ](https://github.com/openssl/openssl/commit/2b3936e8825efa15eceaa41ba6d3486dfc6ee2c0) from @snhenson that added this code in 1.1.0 but I do not really understand its purpose. 
Moreover the note written in the Readme for this commit is about debug notification.

```
static int check_issued(X509_STORE_CTX *ctx, X509 *x, X509 *issuer)
{
    int ret;
    if (x == issuer)
        return cert_self_signed(x);
    ret = X509_check_issued(issuer, x);
    if (ret == X509_V_OK) {
        int i;
        X509 *ch;
        /* Special case: single self signed certificate */
        if (cert_self_signed(x) && sk_X509_num(ctx->chain) == 1)
            return 1;
        for (i = 0; i < sk_X509_num(ctx->chain); i++) {
            ch = sk_X509_value(ctx->chain, i);
            if (ch == issuer || !X509_cmp(ch, issuer)) {
                ret = X509_V_ERR_PATH_LOOP;
                break;
            }
        }
    }

    return (ret == X509_V_OK);
}
```

So my question is what is this X509_V_ERR_PATH_LOOP and what does it mean in this context ? 
For me its sounds normal that at some point the `ch == issuer` check is true since the certificate is signed by the issuer...

**Comment by bernd-edlinger** [comment]
Looks like a circle in the issuer chain.
How many certificates are in the chain ?

**Comment by cacamille3** [comment]
Only 2. The certificate itself and its issuer.
But yes if I go in the chain for me its normal that when i = 1,` ch == issuer` is true ...

**Comment by bernd-edlinger** [comment]
I mean what is sk_X509_num(ctx->chain) ?

**Comment by cacamille3** [comment]
2...

**Comment by bernd-edlinger** [comment]
What does the call stack look like?

**Comment by cacamille3** [comment]
I could find this Mail archive about it here: https://www.mail-archive.com/openssl-dev@openssl.org/msg30525.html 

The last information was: 

> I'm not sure why we need to do anything more than that. As I see it if
> the candidate issuer certificate is already in the chain we should
> always reject it as we never want to include duplicate certificates in
> the chain.

I can understand that but the problem is that we only returns 1 (OK) for `check_issued() ` only when `ret == X509_V_OK `....
IMHO this should also returns 1 when `ret == X509_V_ERR_PATH_LOOP`

**Comment by bernd-edlinger** [comment]
I think it must be something with your root certificate, would you mind posting the certificates here?

**Comment by bernd-edlinger** [comment]
> IMHO check_issued() should also returns 1 when ret == X509_V_ERR_PATH_LOOP

The point is, usually when this function is called, the next thing will be to push the certificate
onto the chain stack, but it is already there.

**Comment by cacamille3** [comment]
```

Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            c0:72:c3:dd:6d:2d:1f:ad
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = AT, ST = Vienna, L = Vienna, O = LOYTEC electronics GmbH, OU = Development, CN = MY.OWN.CA
        Validity
            Not Before: Apr 21 12:28:05 2017 GMT
            Not After : Apr 19 12:28:05 2027 GMT
        Subject: C = AT, ST = Vienna, L = Vienna, O = LOYTEC electronics GmbH, OU = Development, CN = MY.OWN.CA
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:d3:6a:d0:62:ec:db:81:cc:38:da:08:61:fe:6c:
                    96:2b:5f:34:af:52:e2:13:c1:b9:22:17:f4:3d:17:
                    07:a8:86:3d:b4:6a:a0:68:95:cf:db:6b:bd:34:20:
                    dd:74:48:51:0b:9e:d0:4a:e7:75:c0:d1:85:14:fb:
                    db:cd:9f:64:7a:fb:49:db:fd:c9:dc:cd:33:ef:49:
                    ee:cb:4f:2a:68:be:7b:29:19:03:5f:61:18:9b:77:
                    f1:f3:02:ab:26:74:97:15:3d:cc:31:e1:49:0b:4d:
                    27:8e:fc:7e:aa:de:b4:7b:31:b5:d2:0d:fd:99:d4:
                    f5:cc:3c:59:c0:9a:8f:d9:15:4e:87:e2:64:30:1e:
                    1e:cd:5c:dc:21:a4:53:ee:fa:0a:73:8b:69:41:dc:
                    5c:b7:16:75:ec:60:4e:f6:13:bf:29:f6:e6:3b:c6:
                    e3:2d:96:a6:27:64:89:25:8f:b8:c9:b6:dc:ab:30:
                    25:f0:0e:53:cc:1a:f7:c8:41:6c:d4:7c:08:ee:26:
                    40:91:13:02:39:f4:46:44:d3:a5:2f:d5:b0:1a:ef:
                    6b:c4:2d:8e:88:be:a8:fa:6b:c6:d5:ee:4a:11:3b:
                    2e:85:36:6c:0a:da:6b:3c:0e:0f:db:03:d2:c4:ac:
                    e0:08:1c:d4:49:eb:00:5f:98:96:79:4b:0f:2e:95:
                    be:95
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                E2:B7:D0:5A:54:63:28:A0:21:E1:4B:C8:86:6A:EC:38:87:31:D1:AD
            X509v3 Authority Key Identifier: 
                keyid:E2:B7:D0:5A:54:63:28:A0:21:E1:4B:C8:86:6A:EC:38:87:31:D1:AD

            X509v3 Basic Constraints: 
                CA:TRUE
    Signature Algorithm: sha256WithRSAEncryption
         0f:5d:c1:38:85:ea:3d:c0:cc:dd:97:88:76:07:05:c0:f6:7a:
         af:5f:a6:ef:74:59:8e:42:4e:dc:f5:9f:91:95:3d:95:3b:c3:
         97:1b:07:ef:e4:ac:f3:89:18:76:3c:4a:e4:51:e7:f5:41:39:
         40:cd:e9:83:16:0c:ff:7c:6e:d0:9a:c9:18:0e:7b:cd:09:e0:
         53:e8:5e:00:e4:07:71:0c:ab:1c:93:4f:43:a0:f1:b8:94:59:
         6f:73:8e:d1:eb:4f:e8:95:b3:7f:27:bf:69:15:9c:cf:f9:ca:
         d5:24:71:d3:2f:43:30:f6:2f:d9:d4:43:47:31:91:bc:71:08:
         bc:a5:17:1e:32:7f:e1:9a:94:3a:2e:fb:d9:6e:2e:3e:24:98:
         e9:88:c5:be:24:44:06:7c:19:e1:9b:89:4f:96:f8:d4:61:b3:
         71:92:ff:3d:92:b7:02:97:34:06:93:cb:22:be:22:c6:f4:45:
         8d:26:8f:cb:7d:54:6f:ed:10:b9:42:9d:c1:53:52:a7:94:f9:
         d9:04:e4:34:0e:c4:8b:6c:06:3b:73:00:b8:a0:15:df:7b:7e:
         2b:dc:d4:de:ee:93:44:a2:ff:df:1e:c8:7a:7b:c6:88:28:a6:
         4b:db:75:cf:1b:b8:1d:da:b0:5f:a9:3d:65:89:89:f6:3e:92:
         91:26:04:2e

```

**Comment by bernd-edlinger** [comment]
It's unusual that the root certificate does not have X509v3 Key Usage.

**Comment by cacamille3** [comment]
Yes but the result will be same ....

**Comment by bernd-edlinger** [comment]
So could you provide the call stack when this happens?

**Comment by cacamille3** [comment]
Do you want the call stack that call check_issued ?
I could not provide the original call stack currently but the caller are the following:
My OPC UA Server call: `X509_STORE_CTX_get_get_issuer`()
Since I didn't define a new `X509_STORE_CTX_get_issuer_fn `the default one is called 
[X509_STORE_CTX_get1_issuer](https://github.com/openssl/openssl/blob/b926f9deb3dc79d00f0a989370e95867516a3a17/crypto/x509/x509_lu.c#L662)
This function then call `check_issued`

**Comment by bernd-edlinger** [comment]
Ah, I misunderstood that it was called somehow a second time from X509_verify_cert.
I think the X509_STORE_CTX is only for single use.  After it was used for X509_verify_cert
you should dispose of it.
What is you application trying to accomplish there?
The X509_verify_cert has already been done, correct?

**Comment by cacamille3** [comment]
My application is trying to find if a given certificate should be allowed to connect.
By doing it so it check locally if it contains the certificate in a given path.
If this is not the case and the certificate has an issuer (not self-signed), it verify if this issuer is present or not in the given path.

To do so I have to call 2 OpenSSL API: 

- `X509_STORE_CTX_get_check_issued()` to verify if the certificate is self-signed or not

- `X509_STORE_CTX_get_get_issuer()` if the certificate is not self-signed, then I try to get the certificate issuer (to check if this one is my given path)

As I said before, `X509_STORE_CTX_get_get_issuer()` was returning 1 and the issuer certificate of the client certificate, now it returns 0 and no issuer certificate due to the change in `check_issued`

**Comment by bernd-edlinger** [comment]
But what built up the chain, there is already a chain in the X509_STORE_CTX ?
Have you called X509_verify_cert before that get_issuer ?

**Comment by cacamille3** [comment]
Yes `X509_verify_cert` is called before and returns 1 in both case where the Certificate issuer is or not in my list of trusted certs

**Comment by bernd-edlinger** [comment]
But you were supposed to use the chain that X509_verify_cert built up, instead of building up
a completely different one.
If you use only get_issues and check_issued then you do not check the signatures either.

**Comment by bernd-edlinger** [comment]
X509_STORE_CTX_get0_chain or X509_STORE_CTX_get1_chain after X509_verify_cert
gives you the chain which has **verified** signatures.

**Comment by bernd-edlinger** [comment]
I can't tell why X509_verify_cert should return 1 of the issuer is not trusted, but that is
certainly your real problem.

**Comment by cacamille3** [comment]
I have removed the code using X509_STORE_CTX_get_get_issuer() in my OPC UA Server.
This was actually not required anymore with OpenSSL 1.1.1.
With OpenSSL 1.0.X the call to X509_verify_cert was returning an error in my case and I was circuvemting it by checking verifying manually the folder of trusted certs
