### ISSUE TITLE
How to use keylogfile option externally

### ISSUE THREAD

**Issue by dinesh-git-hub** [openssl/openssl#9368]
How to use `-keylogfile` option from nginx / apache server?

I want to save ssl session keys to a file on my server (nginx / apache / others).
I found following option `keylogfile` when starting openssl s_server.
```
openssl s_server -key /etc/ssl/key.key -cert /etc/ssl/cert.pem -accept 443 -keylogfile sslkeylog.log -state -www
```

How do I replicate the same in external server like nginx / apache?

**Comment by mattcaswell** [comment]
I guess that's probably a question to ask apache/nginx

**Comment by dinesh-git-hub** [comment]
Is there an environment variable which can be set to enable it instead of passing argument to s_server?

**Comment by richsalz** [comment]
> Is there an environment variable which can be set to enable it instead of passing argument to s_server?

No, that would be a security issue.
