### ISSUE TITLE
SSL_get0_chain_certs always returns zero

### ISSUE THREAD

**Issue by ramahmoo** [openssl/openssl#9374]
We are using OpenSSL-1.1.1. The function SSL_get0_chain_certs is always returning zero.

The following code in **s3_lib.c** is not setting return code, therefore the function **ssl3_ctrl**  always returns zero.

```
case SSL_CTRL_GET_CHAIN_CERTS:
        *(STACK_OF(X509) **)parg = s->cert->key->chain;
        break;
```

**Comment by mattcaswell** [comment]
Fix in #9395.
