### ISSUE TITLE
DSO pathbyaddr for Cygwin

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#9385]
File dso_dlfcn.c has line "undef HAVE_DLINFO" for certain platforms. One of cases is for Cygwin.
As result of this pathbyaddr always returns -1.

Cygwin support function  dladdr and its argument structure Dl_info. So "undef" is outdated.

Removal will prevent faillre reported in issue #9330 and could help to resolve properly issue #9339 .

Remark: Let my check cygwin version that adds dladdr().

For protocol returned data in dli.dli_fname has path component.

**Comment by petrovr** [comment]
commit with 'Implement dladdr() (partially)' from 6 Mar 2017
Note that this always returns with dli_sname and dli_saddr set to NULL,
indicating no symbol matching addr could be found.

So on Cygwin dladdr() in usable in OpenSSL since above commit.
It is path of library version tagged with cygwin-2_8_0-release from "30 
Mar 2017 14:26:23 +0000"


It seems to me is save to activate use of dladdr() in master and 1.1.1 
branches.

Roumen

**Comment by levitte** [comment]
Ok.  proposed fix in #9402
