### ISSUE TITLE
Question: Is the CLI api stable?

### ISSUE THREAD

**Issue by albertvaka** [openssl/openssl#9426]
In the KDE Connect project we are considering calling the `openssl` command line app directly from our code, to generate a certificate file. However, we are concerned that if the arguments of the `openssl` command line interface ever change, this could break our app. Is there any guarantee that the CLI arguments are going to remain stable in future releases?

**Comment by mattcaswell** [comment]
We try to avoid making breaking changes to command line arguments and I think it is unlikely we would intentionally do so in a minor or patch release. Major releases could make such changes. Our next release (3.0) will be a major release - although our stated intention for that release is to avoid making breaking changes wherever possible.

**Comment by beldmit** [comment]
It's worth mentioning that the default values for digests, ciphers etc are subject to change between major releases.

**Comment by albertvaka** [comment]
What is the recommended way of using openssl programmatically from an application, then? Is the ABI of the library stable?

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
