### ISSUE TITLE
SHA3_squeeze causes segmentation fault on some platforms

### ISSUE THREAD

**Issue by tniessen** [openssl/openssl#9431]
While trying to add support for variable output lengths for shake128 and shake256 to Node.js, I noticed a number of segmentation faults on some of our CI platforms such as s390x. We are using OpenSSL 1.1.c.

One test case calls `EVP_DigestFinalXOF` with a requested output size of zero bytes. I expected OpenSSL not to write to the supplied buffer in this case, and that is true on some platforms. On other platforms such as s390x, `SHA3_squeeze` causes a segmentation fault, maybe trying to access the buffer which is `NULL`.

It is possible that other inputs are affected as well, even though I was not able to produce any segmentation faults for inputs other than `0`.

Arguably, calling `EVP_DigestFinalXOF` with an output size of `0` bytes makes little sense, but it still should not cause a segmentation fault in my opinion. The C implementation of `SHA3_squeeze` seems to handle this case nicely.

**Comment by mattcaswell** [comment]
Ping @p-steuer.

Is it only s390x, or are there are platforms impacted?

**Comment by tniessen** [comment]
The following platforms appear to be impacted:

- s390x
- Raspberry Pi 2, Raspberry Pi 3
- ppc64
- armv7
- ppcle

There might be other affected platforms that we are not testing against.

**Comment by p-steuer** [comment]
Im working on a fix (that is, match sha3_squeeze asm implementations to the reference implementation), but may need help to verify the fix for architectures i have no access.

**Comment by p-steuer** [comment]
should be firxed by a890ef8 (master) resp. 6087d4a (1.1.1).

please verify.

**Comment by tniessen** [comment]
I can confirm that this fixes the problem for output lengths of zero bytes, I have never been able to produce segfaults using other sizes.
