### ISSUE TITLE
Certs folder empty after compiling openssl

### ISSUE THREAD

**Issue by katsar0v** [openssl/openssl#9436]
Hello! I am trying to compile openssl and php, here is my dockerfile:

https://www.pastiebin.com/5d37031706310

All my certificates are in `/etc/ssl/certs/` though and not in `/usr/local/certs` which breaks my php application. Making a symlink fixes this, but maybe I am compiling `openssl` wrong. What is the issue and why does php not want to find certificates?

In case this also helps, here is the php error:
```
Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /var/www/html/wp-includes/class-smtp.php on line 368
```

**Comment by levitte** [comment]
/etc/ssl/certs/ is a path usually used by openssl packaged by the vendor, most notably Linux distributions like Debian. So I am guessing that the OpenSSL you have used so far is the system installed one, right?

You're not doing anything wrong, it's just that we have our default paths, and many packagers choose to use other defaults that suit them better.

**Comment by katsar0v** [comment]
I am trying to compile latest openssl stable and latest php stable on debian yes. But for example on php smtp over tls will not work, because openssl cannot verify the certificates. A symlink fixes this issue, but is this how it should be solved? These "ca-certificates" always go in "/etc/ssl/...", no matter where openssl is installed, but how can I tell openssl to use these certs? Or should I use `openssl.capath` in `php.ini`?

**Comment by katsar0v** [comment]
Hello, is there any update? Is there an option which tells `openssl` from which folder to search for certs? `ln -s /etc/ssl/certs /usr/local/share/certs` fixed it in my case... but I need the configuration for compiling, would like to avoid "symlink hacks" :)

**Comment by levitte** [comment]
If php provides a variable that you can set, then do it!

**Comment by katsar0v** [comment]
What about python and urllib?

**Comment by katsar0v** [comment]
Any updates on this issue?

**Comment by levitte** [comment]
The *current* way does mean that you have to do your symlink hack do get what you want.

It's still undecided whether we will have a more fine-grained way to do the same thing via configuration.  I have it in the back of my mind, but there are other things that we currently consider higher priority.

However, should someone feel inspired, PR welcome!

**Comment by Nitin-Salunke** [comment]
@katsar0v exporting the below environment variable should work for you I think

export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
