### ISSUE TITLE
re-use allocated space in error structure

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#9458]
See comment thread ta https://github.com/openssl/openssl/pull/9452#discussion_r307103294

The error field has a pointer, mainly used for printf'd extra data.  That should be re-used when possible. That means adding a size field, and perhaps other cleanups.

This is important because the allocation is 1K.  It should probably be 256  and longer printf strings should just be truncated (which vnsprintf does, happily).

**Comment by levitte** [comment]
Note that we have the exact same issue regardless of #9452.  Right now, as soon as a new error is recorded, the old data for that error is cleared, which includes freeing previously allocated data in the `err_data` field.

**Comment by richsalz** [comment]
Yes, this is not a change in behavior and now that it's going to be easier to add data because of #9452 we should fix it.  Before it was awkward at best.

**Comment by levitte** [comment]
See #9459

**Comment by levitte** [comment]
(sorry, suddenly got inspired)
