### ISSUE TITLE
avoid C++ style return value

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#9465]
Currently public header <openssl/params.h> declare a number of function that return complex structure.
This is not usual C style and is not well documented compiler behaviour. On some platforms different compilers generate different code. It could depend from used compiler or compiler flags. For instance see 'gcc --help -v 2> /dev/null | grep -i aggregate'.

To avoid such issue please change from C++ style to C style, i.e. AGGREGATE foo(...) ->  foo(AGGREGATE, ...).

**Comment by levitte** [comment]
I'm sorry?  Returning a structure has been perfectly acceptable C since a very long time.  I remember using it when I first learned the language back in the 80's.  This is even fairly common, for example with `pthread_t` on platforms where that type is a bit more complex than a mere number.

**Comment by levitte** [comment]
...or rmaybe it was in the 90's.  A quick search tells me that K&R C didn't allow this, but considering we don't require such compilers, I can't see why this should be a bother.  Just don't use `-Waggregate-return`.  Even the GNU folks seem to view it as anachronistic, and that was already 7 years ago (from https://lists.gnu.org/archive/html/bug-gnulib/2012-09/msg00006.html):

> In the GNU apps I'm familiar with (Emacs, coreutils, ...)
> we simply disable -Waggregate-return.  It a completely
> anachronistic warning, since its motivation was to
> support backwards compatibility with C compilers that
> did not allow returning structures.  Those compilers
> are long dead and are no longer of practical concern.

**Comment by paulidale** [comment]
K&R didn't allow this, but pretty much all later versions did.

I much prefer strict K&R and its fun:

1. The unused _entry_ keyword
2. Unchecked function arguments and different function declaration syntax
3. Comments expanding to nothing rather than whitespace ([I've used this good effect](https://www.ioccc.org/1988/dale.c))
4. All _real_ expressions are evaluated in double precision (this one is serious)

Fortunately, the defaulting everything to _int_ remains in the language even now.

**Comment by levitte** [comment]
> (I've used this good effect)

Of course I had to look.  My eyes hurt now, and I can't un-see it...

**Comment by paulidale** [comment]
It was award winning code.
How could you possibly forget it 😆

**Comment by mspncp** [comment]
> 3\. ([I've used this good effect](https://www.ioccc.org/1988/dale.c))

I shiver in awe! You are listed in the [IOCCC Hall of Fame](https://www.ioccc.org/years.html)?!

**Comment by mspncp** [comment]
Can this be reformatted according to our [Coding Style](https://www.openssl.org/policies/codingstyle.html)?

**Comment by levitte** [comment]
>  How could you possibly forget it :laughing:

That kind of stuff?  In through one ear, out through the other.

**Comment by paulidale** [comment]
Yes, it could be reformatted to the coding style but I doubt it would be any more readable :)

I created this abomination during my honours year at university.  I had nothing better to do at the time, well besides programming a [chess](https://www.hpcalc.org/details/280) player for a calculator.  The 3x3 graphical representations of the pieces were, IMHO, the high point of our honours year's efforts.

I had a followup IOCCC entry that was even more evil but I couldn't get it down to the size restrictions at the time.  I suggest you "man 1 cat", then consider adding pretty much every upper and lower case letter, some digits and a few symbols.  For example, `cat -9` naturally produced base-9 encoded output.  Options were present to replace many Unix command line utilities (e.g. `rm` was possible by unlinking the files after processing).  Sadly, the man page was rejected by _rec.humor.funny_ because it contained the standard options which weren't funny enough.

**Comment by paulidale** [comment]
> That kind of stuff? In through one ear, out through the other.

Thus spoketh the Perl programmer.

**Comment by levitte** [comment]
I have *no* idea what you're implying!

**Comment by mspncp** [comment]
Any chance to get this to compile nowadays? Or does it require a K&R C compiler?

```make
make -k dale
cc -O -std=c90 dale.c -o dale
dale.c:2:2: error: invalid preprocessing directive #_
 #_ P char
  ^
dale.c:3:2: error: invalid preprocessing directive #_
 #_ p int
  ^
...
dale.c:15:1: error: unknown type name 'P'
 P z[l<<(1<<l<<1)<<1<<(l<<1)<<(l<<l<<l)<<1],*v;p r,A=0,c=1;
 ^
dale.c:15:5: error: 'l' undeclared here (not in a function)
 P z[l<<(1<<l<<1)<<1<<(l<<1)<<(l<<l<<l)<<1],*v;p r,A=0,c=1;
     ^
dale.c:15:47: error: unknown type name 'p'
 P z[l<<(1<<l<<1)<<1<<(l<<1)<<(l<<l<<l)<<1],*v;p r,A=0,c=1;
                                               ^
```

**Comment by mspncp** [comment]
> > > That kind of stuff? In through one ear, out through the other.
> > 
> > Thus spoketh the Perl programmer.
>
> I have _no_ idea what you're implying!

I think what @paulidale is saying that here is no IOPPP context, because Perl itself is the perfect impersonation of obfuscation.

**Comment by levitte** [comment]
I'm actually a bit offended on perl's behalf...

BTW, isn't the discussion a bit off topic? :wink:

**Comment by paulidale** [comment]
You will need a K&R compiler (or at least pre-processor).  ANSI C specifies that comments are treated as if they were spaces, K&R allowed them inside identifiers.  This code was written before the ANSI siege had begun.  A hint: replace `for/*/(;;);/*/k` with `fork`

BTW: there is (was) an IOPP contest.  I've never looked into the Lovecraftian horrors that are created in this abyss :)

Yes, we're off topic a bit.

**Comment by paulidale** [comment]
Oh, I missed that `#define _ define` followed by `#_` didn't work anymore.  Such a waste of pure beauty.  It will need a K&R option set, or an older compiler.

**Comment by richsalz** [comment]
K&R C didn't allow struct returns, but the K&R _C Book_ talked about them, and it was added to v7 unix IIRC.

Close this.

**Comment by petrovr** [comment]
Richard Levitte wrote:
> ...or rmaybe it was in the 90's.  A quick search tells me that K&R C didn't allow this, but considering we don't require such compilers, I can't see why this should be a bother.  Just don't use `-Waggregate-return`.  
Even the GNU folks seem to view it as anachronistic, and that was 
already 7 years ago (from 
https://lists.gnu.org/archive/html/bug-gnulib/2012-09/msg00006.html):

No! Report is not related to outdated compilers. C compilers should 
support "by value". If I remember its is part of c89 standard.

I'm concerned about compatibility between compilers.

**Comment by richsalz** [comment]
> I'm concerned about compatibility between compilers.

You mean like openssl is built with clang and someone uses gcc on their app and things don't work? I still don't think that is worth OpenSSL worrying about.

**Comment by levitte** [comment]
@petrovr, you are incorrect.  For example, the C89 spec mentions `div_t`, returned by the function `div()`.  `div_t` is a struct with two members, `quot` and `rem`.

Here's what the Linux manual has to say re conformance (emphasis mine):

> CONFORMING TO
> POSIX.1-2001, POSIX.1-2008, *C89*, C99, SVr4, 4.3BSD.  The functions  ll‐div() and imaxdiv() were added in C99.

**Comment by petrovr** [comment]
Richard Levitte wrote:
> @petrovr, you are incorrect.  For example, the C89 spec mentions `div_t`, returned by the function `div()`.  `div_t` is a struct with two members, `quot` and `rem`.

Let me quite my first post "Currently public header <openssl/params.h> 
declare a number of function that return complex structure." Please note 
word - complex.

Quick check of div_t shows two integers, does not look like complex.

Regard,
Roumen Petrov

**Comment by levitte** [comment]
Uhmmmm, `OSSL_PARAM` has five fields, straight up, no unions, no substructures...  In terms of returned values, a five field structure isn't more complex than a two field structures, it's a bunch of bytes to copy either way.

**Comment by levitte** [comment]
To put it differently, a struct (named or anonymous) is a type that can be passes just like any other type, such as int, double, int128_t or whatnot.  Incidently, that kind of passing *is* "by value", like you mentioned earlier.

However, I can put it more simply: no.  I do not see us changing that.  The response you've received so far should be pretty clear.

**Comment by petrovr** [comment]
It seems to me compiler inconsistency is not so important. More or less it does not exist on widely used OS-es.

Also it seems to me team prefer to perform double or triple initialization of memory.

**Comment by levitte** [comment]
> It seems to me compiler inconsistency is not so important.

Do you have a use case, where it isn't simply a compiler bug that is fixed in a newer version?

> Also it seems to me team prefer to perform double or triple initialization of memory.

Make that a different issue and please point out exactly where that happens.  It's quite possible we missed it.
