### ISSUE TITLE
Failed to cross compile for android64-aarch64

### ISSUE THREAD

**Issue by joywelt** [openssl/openssl#948]
In v1.0.2x, the supported os/compiler list doesn't include android64-aarch64(armv8).

Whe compiling 1.1.0x, I always get the following errors:

```
( trap "rm -f crypto/chacha/chacha-armv8.s.*" INT 0; \

          CC="aarch64-linux-android-gcc" /usr/bin/perl crypto/chacha/asm/chacha-armv8.pl linux64 crypto/chacha/chacha-armv8.s.S; \

          aarch64-linux-android-gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DENGINESDIR="\"/usr/local/lib/engines\"" -mandroid -fPIC --sysroot=/opt/new_android_toolchain/sysroot -Wa,--noexecstack -Wall -O3 -fPIE -pie  -Iinclude -I. -Icrypto/include -Icrypto -E -P crypto/chacha/chacha-armv8.s.S > crypto/chacha/chacha-armv8.s.i && mv -f crypto/chacha/chacha-armv8.s.i crypto/chacha/chacha-armv8.s )
crypto/chacha/chacha-armv8.s.S:271:0: error: unterminated #ifdef
 #ifdef __ARMEB__
 ^
```

OR

```
./libcrypto.so: undefined reference to `getcontext'

./libcrypto.so: undefined reference to `setcontext'

./libcrypto.so: undefined reference to `makecontext'

./libcrypto.so: undefined reference to `ChaCha20_neon'
```

The command I used is:

```
export  INSTALLDIR=/opt/new_android_toolchain

export PATH=$INSTALLDIR/bin:$PATH

export TARGETMACH=aarch64-none-linux-android

export BUILDMACH=x86_64-linux-gnu

export CROSS=aarch64-linux-android

export CC=${CROSS}-gcc

export LD=${CROSS}-ld

export AS=${CROSS}-as

export AR=${CROSS}-ar

export CXX=${CROSS}-g++

export RANLIB=${CROSS}-ranlib

export NM=${CROSS}-nm

export CROSS_SYSROOT=/opt/new_android_toolchain/sysroot
```

`./Configure shared android64-aarch64`

Then I edited the Makefile to add "-fPIE -pie" to CFLAGS. Afterwards I ran

`make`

Did I do anything wrong?

**Comment by ekasper** [comment]
Flagging @dot-asm

**Comment by dot-asm** [comment]
Failure to compile chacha-armv8.S is addressed now in b9077d85b0042d3d5d877d5cf7f06a8a8c035673. As for other things. You don't need to set separate CC, LD, AR, etc., variables, it's sufficient to set just set CROSS_COMPILE (see example in Configurations/10-main.cf). Nor should you have to edit Makefile to add -fPIE -pie, because -pie is already there and so is -fPIC, which is equivalent to -fPIE in the context. Well, you should never have to edit Makefile, because one can as well pass additional compiler flags the moment you run ./Configure, e.g. ./Confgiure ... -fPIE -pie. Though once again, these specific flags should not be necessary. As for failure to link with *context, it would take additional look...

**Comment by joywelt** [comment]
Thanks for the detailed explanation, I'll try to compile it again.

**Comment by dot-asm** [comment]
There was android update, cba792a1e941788cba7dc700a2ef59420e7f2522, which addresses linking problems.

**Comment by mattcaswell** [comment]
Ping @joywelt, can this be closed now?

**Comment by joywelt** [comment]
Yes, I compiled it successfully. Thanks!

**Comment by pkalebu** [comment]
@joywelt did you at all experience the following error?

```
clangclangclang: : : error: unknown argument: '-mandroid'clang:
error: unknown argument: '-mandroid'
error: unknown argument: '-mandroid'
error: unknown argument: '-mandroid'
make[1]: *** [crypto/aes/aes_ecb.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [crypto/aes/aes_core.o] Error 1
make[1]: *** [crypto/aes/aes_cfb.o] Error 1
make[1]: *** [crypto/aes/aes_cbc.o] Error 1
make[1]: Leaving directory `/Users/pkalebu/Dropbox/Akruta/Voice/alexa/android_workplace/BUILD/android-26/arm64-v8a/openssl'
make: *** [all] Error 2
```
I can't seem to figure out why it happens or how to get past i
