### ISSUE TITLE
OPENSSL_VERSION_TEXT no longer a proper string

### ISSUE THREAD

**Issue by rwfranks** [openssl/openssl#9489]
For as long as anyone cares to remember, the OPENSSL_VERSION_TEXT macro has been defined as a single string:
```
    #define OPENSSL_VERSION_TEXT    "OpenSSL 1.1.1  11 Sep 2018"
```
From 3.0.0, this is redefined as four separate elements:
```
    #define OPENSSL_VERSION_TEXT        \
        "OpenSSL " OPENSSL_FULL_VERSION_STR " " OPENSSL_RELEASE_DATE
```
This introduces compilation errors if OPENSSL_VERSION_TEXT is used in a context where a single string is expected.

Attempting to coerse OPENSSL_VERSION_TEXT into a single string using OPENSSL_MSTR produces a result with embedded \"s resulting from premature evaluation.
```
    \"OpenSSL \"\"3\" \".\"\"0\" \".\"\"0\"\"-dev\"\"\" \" \"\"xx XXX xxxx\"
```
The following code produces something close to the pre-3.0.0 OPENSSL_VERSION_TEXT:
```
    #define OPENSSL_VERSION_PRE_RELEASE     -dev            /* NOT within quotes */
    #define OPENSSL_RELEASE_DATE    xx XXX xxxx             /* NOT within quotes */
    #undef OPENSSL_BUILD_METADATA                           /* NOT within quotes */

    #ifdef OPENSSL_VERSION_PRE_RELEASE
    # define _OPENSSL_PRE_RELEASE   OPENSSL_VERSION_PRE_RELEASE
    #else
    # define _OPENSSL_PRE_RELEASE
    #endif

    #ifdef OPENSSL_BUILD_METADATA
    # define _OPENSSL_BUILD_METADATA        OPENSSL_BUILD_METADATA
    #else
    # define _OPENSSL_BUILD_METADATA
    #endif

    #define _SPACE  _

    #define OPENSSL_VERSION_TEXT    OPENSSL_MSTR( OpenSSL _SPACE    \
            OPENSSL_VERSION_MAJOR.OPENSSL_VERSION_MINOR.OPENSSL_VERSION_PATCH       \
            _OPENSSL_PRE_RELEASE _OPENSSL_BUILD_METADATA _SPACE OPENSSL_RELEASE_DATE )
```
Devising a satisfactory definition of the _SPACE macro (inserting white space) is left as an exercise for the student.

**Comment by levitte** [comment]
Exactly what are you trying to do? Due to string concatenation, which any C compiler *should* do, I fully expect `OPENSSL_VERSION_TEXT` to be interpreted as a single string indeed.

**Comment by rwfranks** [comment]
This recycles the result of an investigation which involved #include file names assembled from #define arguments and encountered similar issues.

The following assumes that the goal is to provide a new OPENSSL_VERSION_TEXT,  incorporating the new OPENSSL_VERSION_* macros, but otherwise in the same form as previous versions.

In order to know for certain that the result is acceptable, the #include directive can be (ab)used to demonstrate that it consists of exactly one proper string.
```
#define BAD text
#include BAD
explore.c:10:10: error: #include expects "BAD" or <BAD>
   10 | #include BAD
      |          ^~~
```
which can be stringified using the existing OPENSSL_MSTR macro:
```
#define BAD text
#define GOOD    OPENSSL_MSTR(BAD)
#include GOOD
explore.c:11:10: fatal error: text: No such file or directory
   11 | #include GOOD
      |          ^~~~
```
All that then remains is to construct the pre-stringified token sequence.
Note: Quoted strings will be inserted verbatim, complete with enclosing quotes.
```
#define OPENSSL_VERSION_PRE_RELEASE     -dev
#define OPENSSL_VERSION_BUILD_METADATA  vendor stuff
#define OPENSSL_RELEASE_DATE            xx XXX xxxx

#define OPENSSL_GLUE(x) x               /* glue argument to following token */

#define _OPENSSL_VERSION  OPENSSL_VERSION_MAJOR.OPENSSL_VERSION_MINOR.OPENSSL_VERSION_PATCH

#define OPENSSL_VERSION_TEXT \
        OPENSSL_MSTR(OpenSSL OPENSSL_GLUE(_OPENSSL_VERSION)OPENSSL_PRE_RELEASE \
        OPENSSL_BUILD_METADATA OPENSSL_RELEASE_DATE)
```
Some practical details have been glossed over in the interests of clarity.

A fully worked patch is attached for your consideration.

[opensslv.h-patch.gz](https://github.com/openssl/openssl/files/3468381/opensslv.h-patch.gz)

**Comment by paulidale** [comment]
While it is legal C, using macro expansion as part of a #include directive is pretty ugly.

**Comment by rwfranks** [comment]
C has nothing at all to do with this.
Macro expansion, #define and #include directives are features of cpp.

**Comment by mspncp** [comment]
> C has nothing at all to do with this.

I disagree: string concatenation happens by the compiler _after_ macro expansion

> First, at translation phase 6 (after macro expansion), the adjacent string literals (that is, string literals separated by whitespace only) are concatenated.

(see https://en.cppreference.com/w/c/language/string_literal)

**Comment by mspncp** [comment]
> Macro expansion, #define and #include directives are features of cpp.

In this case you are right, and that's very likely the reason why your #include hack does not work, because after macro expansion (and before the C compiler concatenates it), `OPENSSL_VERSION_TEXT` consists indeed of several literal strings.

But who cares? Is there any practical use case for expanding `OPENSSL_VERSION_TEXT` inside an #include directive?

**Comment by mspncp** [comment]
As for #include directives using macro expansion: those are called 'computed includes' and there is some limited use for them, see the [gcc preprocessor documentation](https://gcc.gnu.org/onlinedocs/gcc-4.1.0/cpp/Computed-Includes.html). But the essential part is that the macros must expand to one of the following two valid forms for include directives

```C
	#include <some/header.h>
	#include "another/header.h"
```

and something like the following is not allowed:

```C
	#include "another"  "/" "header.h"
```

(See also http://herbert.the-little-red-haired-girl.org/html/gcc/cpp_1.html#SEC6)

**Comment by rwfranks** [comment]
That misses the point.

It is explicitly stated in my post, that #include was being abused as a tool to determine if the macro definition cobbled together from the five already defined components consists of a single string.
I am using one part of cpp to verify the actions of my macro definitions, knowing that cpp will eventually be called upon to expand these same macros and deliver something that looks like a string.

**Comment by richsalz** [comment]
OpenSSL moved away from using define's in include statements; this was done when #9204 was merged and I am sure that the team doesn't want to go back there. :)

It seems that you are trying to use version-dependent headers in your application, but you never clearly answered the question at https://github.com/openssl/openssl/issues/9489#issuecomment-516720522.

The macro ```OPENSSL_VERSION_STRING``` continues to remain a valid C string. It was never intended to be a pre-processor string, *if that is what you are trying to do.*

**Comment by kaduk** [comment]
I'm still confused about the actual practical impact/complaint here.

> This introduces compilation errors if OPENSSL_VERSION_TEXT is used in a context where a single string is expected.

is just a conditional statement without any evidence that the condition is ever met in practice.

To phrase it differently, there are a lot of places in openssl where people have assumed that historical behavior would continue into the future, even when that was a bad idea and caused problems for both the maintainers and the consumers making those assumptions.  (Consider the move to opaque structures as a move out of such a situation.)  Why should this particular historical behavior be promoted to an invariant?

**Comment by mspncp** [comment]
> That misses the point.

No it doesn't. You are missing it. Do you intend to start an academic discussion, or are you actually reporting a bug? We asked you that several times, and we still did not get an answer from you.

**Comment by levitte** [comment]
I will echo the sentiment by asking: why is it important for that macro to end up being a single string in cpp?

If we have an understanding, I'm not saying we will change its current nature, but might be able to advise better mechanisms to do what you're trying to do. 

(unless this is just an academic discussion, in which case I personally find it moot, and reason for closing this issue immediately)

**Comment by paulidale** [comment]
> C has nothing at all to do with this.

It does.  The C standard defines how cpp works as well.  Macro expansion does occur in #include directives under some circumstances.  Thus:
```
#define S <stdio.h>
#include S
```
is defined to work.

**Comment by paulidale** [comment]
The outcome is including a file based on the version number.  It seems, to me, that a series of #if directives would be as good or better than using #include this way.  E.g. slightly difference versions could share an include...

**Comment by kroeckx** [comment]
The string is now "OpenSSL 1.1.1c  28 May 2019". This does not
look like something you want to use in an include.

The new define is still a string for the compiler. cpp does not
even have a concept of strings. (The # operator turns it into a
string for the compiler, not for cpp.)

I suggest we just close this.

**Comment by paulidale** [comment]
@kroeckx I concur.
