### ISSUE TITLE
openssl 1.1.1a _arm7_tick issue

### ISSUE THREAD

**Issue by dadadage** [openssl/openssl#9498]
Hi,

I'm currently experiencing an issue related to _arm7_tick, the stack trace is attached below:

1 | 0x0 | libcrypto.so!_armv7_tick
-- | -- | --
2 | 0xe | libcrypto.so!rand_drbg_get_additional_data
3 | 0x2e | libcrypto.so!RAND_DRBG_bytes
4 | 0xca | libcrypto.so!RAND_DRBG_get0_public
5 | 0x102 | libcrypto.so!RAND_DRBG_get0_public
...

Looks like _arm7_tick function has been triggered on some processors that actually do not support _arm7_tick, does anyone here saw similar issues? Is there any suggestions to fix the issue?

Thank you!
William

**Comment by bernd-edlinger** [comment]
Did you set OPENSSL_armcap=2 ?

**Comment by dadadage** [comment]
> Did you set OPENSSL_armcap=2 ?

Where can I set this?

**Comment by petrovr** [comment]
dadadage wrote:
>> Did you set OPENSSL_armcap=2 ?
> Where can I set this?
>

OPENSSL_armcap is an environment variable .

Actually CPU capabilities are defined from cpu OPENSSL_<CPU>cap  .

Regards,
Roumen Petrov

**Comment by kroeckx** [comment]
Which processor is that?

**Comment by kroeckx** [comment]
This isn't making sense. OPENSSL_cpuid_setup() should detect that
armv7_tick is available or not, by trying to run it. If it's an
illegal instruction, we should not try to do this again.

The exception to this is if the environment variable
OPENSSL_armcap is set, in which case it trust the bits set in
that. If you set those wrong, it will do the wrong thing.

**Comment by stevezhou6** [comment]
I had the same problem.
Android 10,level 29
ROM  Oppo/COLOROS
arm64-v8a
I didn't set the variable OPENSSL_armcap.

**Comment by stevezhou6** [comment]
@kroeckx  thanks a lot!

**Comment by goodpaperman** [comment]
had the same problem:

signal 4 code 1 at address 0xb35b0808
 backtrace:
 #0 pc 0xba3808 /data/data/com.baidu.netdisk/files/p2psdk/jni-kservice_194.so (_armv7_tick+0)
 basic:
 ABI: arm pid: 32174  tid: 32373
