### ISSUE TITLE
compiler problem in ssl/packet_iocl.h of openssl 1.1.1c

### ISSUE THREAD

**Issue by johankleuskens** [openssl/openssl#9503]
When compiling my application for openssl 1.1.1c, I get a compiler error:
openssl-1.1.1c/ssl/packet_locl.h:429:13: error: invalid conversion from 'void*' to 'unsigned char*'

This seems a valid error to me and it would be valid to fix this error by changing line 429 of packet_locl.h from:
&nbsp;&nbsp;&nbsp; _*data = OPENSSL_memdup(pkt->curr, length);_
to:
&nbsp;&nbsp;&nbsp;_*data = (unsigned char *)OPENSSL_memdup(pkt->curr, length);_

Johan Kleuskens

**Comment by mattcaswell** [comment]
> When compiling my application for openssl 1.1.1c, I get a compiler error:

Does this mean you are including "packet_locl.h" directly from your application? That is unsupported.

Or did you mean you get this error when compiling openssl itself?

Looking at the source we do this throughout the code with OPENSSL_memdup().

**Comment by johankleuskens** [comment]
I do not include packet_locl.h from my application, but  I include ssl/ssl_locl.h directly from my app, and i have to do this because if i omit this i get this error:
openssl-1.1.1c/include/openssl/ssl.h:212:16: error: forward declaration of 'const SSL_CIPHER {aka const struct ssl_cipher_st}' 
This seems valid as ssl_cipher_st is declared in ssl_locl.h, but this header file in not included in any other header file.

**Comment by mattcaswell** [comment]
> openssl-1.1.1c/include/openssl/ssl.h:212:16: error: forward declaration of 'const SSL_CIPHER {aka const struct ssl_cipher_st}'

Then this is the real problem. Do not include ssl_locl.h in your application.

I assume your application has been ported from OpenSSL 1.0.2? In 1.0.2 the SSL_CIPHER structure definition was in the public headers. In 1.1.0+ it was made opaque. You are no longer allowed to directly access the structure members of SSL_CIPHER. Instead you need to use SSL_CIPHER accessors. E.g see:

https://www.openssl.org/docs/man1.1.1/man3/SSL_CIPHER_get_name.html

**Comment by levitte** [comment]
>  openssl-1.1.1c/ssl/packet_locl.h:429:13: error: invalid conversion from 'void*' to 'unsigned char*'

This is an error that usually comes when compiling with a C++ compiler, where automatic 'void*' coercion can't be done as liberally as with C, if I understand things correctly.

I believe the other error indicates the same thing, that you're trying to compile OpenSSL with a C++ compiler.

Please use a C compiler to compile OpenSSL.

**Comment by levitte** [comment]
Actually, the second error message seems mysterious...  we do wrap all of ssl.h in `extern "C"`, so one would hope that C++ rules would be a bit more relaxed.  If you're using g++ to compile your application, does it help to add  `-fpermissive` to the compiler flags?

**Comment by levitte** [comment]
@mattcaswell, do note that the ssl.h error has nothing to do with trying to access anything in that structure.  this is the "offending" line:

``` C
typedef struct ssl_cipher_st SSL_CIPHER;
```

**Comment by johankleuskens** [comment]
I indeed moved from 1.0.2 to 1.1.1, and using the functions to access the structure members solves my issue. Many thanks!!

BTW, yes i use C++ and -fpermissive solved the issue but in not really a good solution as this means in my case altering the build environment for other projects also.
