### ISSUE TITLE
deprecate engine initlalization compatibility with 0.9.7

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#9509]
Openssl engine command still supports -pre and -post  command arguments.
It seems to me this is for compatibility with 0.9.7 releases (and separated 0.9.6 engine releases).

Starting from version 0.9.8 OpenSSL supports configuration from file - see config(5). This obsoletes 0.9.7 style.

Goal of this enhancement request is in master branch to remove -pre and -post argument from engine command.

Also "dynamic" engine commands to be marked as internal. Command list:
```
(dynamic) Dynamic engine loading support
     SO_PATH: Specifies the path to the new ENGINE shared library
          (input flags): STRING
     NO_VCHECK: Specifies to continue even if version checking fails (boolean)
          (input flags): NUMERIC
     ID: Specifies an ENGINE id name for loading
          (input flags): STRING
     LIST_ADD: Whether to add a loaded ENGINE to the internal list (0=no,1=yes,2=mandatory)
          (input flags): NUMERIC
     DIR_LOAD: Specifies whether to load from 'DIR_ADD' directories (0=no,1=yes,2=mandatory)
          (input flags): NUMERIC
     DIR_ADD: Adds a directory from which ENGINEs can be loaded
          (input flags): STRING
     LOAD: Load up the ENGINE specified by other settings
          (input flags): NO_INPUT
```
Or may be more - "dynamic" engine to be hided at all.

**Comment by levitte** [comment]
I'm unsure that this change is actually viable...  however, considering our effort to move to providers and make everything engine deprecated, I don't think this will happen either way.

**Comment by kaduk** [comment]
@levitte if this is resolved:wontfix, should it be formally closed as well?

**Comment by levitte** [comment]
Well, when @mattcaswell and I went through issues, we left some of the resolved ones open in case someone had a different opinion.  However, seeing that no one has said a peep here for two weeks, closing is probably the right option at this point.
