### ISSUE TITLE
Deprecated issue - undefined reference to XXX

### ISSUE THREAD

**Issue by smartechru** [openssl/openssl#9515]
I have a problem to enable deprecated functions when I build OpenSSL.
There is no problem in compilation but I can't fix the deprecation issue.
I tried with OpenSSL 1.0.0, 1.0.1, 1.0.2 and 1.1.1 and nothing is helpful to fix this deprecated issue.
I also tried with latest OpenSSL 3.3.0. But no luck so far.
Of course, I set the $INSTALL_DIR and $CROSSCOMP_DIR exactly.
I am trying to cross compile it for Raspberry pi.
```
$ ./Configure linux-generic32 shared \
--prefix=$INSTALL_DIR --openssldir=$INSTALL_DIR/openssl \
--cross-compile-prefix=$CROSSCOMP_DIR/arm-linux-gnueabihf-
```
When I tested it on my Ubuntu 18.04, it worked pretty well.
I tested the OpenSSL version of my Ubuntu with the following command.
```
$ openssl version -a

OpenSSL 1.1.1  11 Sep 2018
built on: Thu Jun 20 17:36:28 2019 UTC
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-cn9tZy/openssl-1.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
Seeding source: os-specific
```
I installed openssl on my Ubuntu with `sudo apt install libssl-dev`.
I downloaded the same version of openssl 1.1.1 and built it.
But when I used it, I noticed the issue was not resolved. I also tried to add `enable-deprecated` when Configuring it. But nothing is working.
These are the error messages I got. Please help me fix this issue. Thanks.

../../../lib/libcurl.so: undefined reference to `SSL_CTX_free'
../../../lib/libcurl.so: undefined reference to `X509_NAME_get_index_by_NID'
../../../lib/libcurl.so: undefined reference to `OCSP_response_status'
../../../lib/libcurl.so: undefined reference to `ASN1_STRING_print'
../../../lib/libcurl.so: undefined reference to `DSA_get0_key'
../../../lib/libcurl.so: undefined reference to `OpenSSL_version_num'
../../../lib/libcurl.so: undefined reference to `DH_get0_pqg'
../../../lib/libcurl.so: undefined reference to `OCSP_RESPONSE_free'
../../../lib/libcurl.so: undefined reference to `BIO_ctrl'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_set_default_passwd_cb_userdata'
../../../lib/libcurl.so: undefined reference to `X509_get0_extensions'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_get_cert_store'
../../../lib/libcurl.so: undefined reference to `RSA_get0_key'
../../../lib/libcurl.so: undefined reference to `OCSP_crl_reason_str'
../../../lib/libcurl.so: undefined reference to `X509_LOOKUP_file'
../../../lib/libcurl.so: undefined reference to `d2i_PKCS12_fp'
../../../lib/libcurl.so: undefined reference to `UI_get0_user_data'
../../../lib/libcurl.so: undefined reference to `BIO_puts'
../../../lib/libcurl.so: undefined reference to `EVP_PKEY_id'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_check_private_key'
../../../lib/libcurl.so: undefined reference to `DSA_get0_pqg'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_use_PrivateKey'
../../../lib/libcurl.so: undefined reference to `OCSP_response_get1_basic'
../../../lib/libcurl.so: undefined reference to `SSL_get_error'
../../../lib/libcurl.so: undefined reference to `UI_destroy_method'
../../../lib/libcurl.so: undefined reference to `EVP_PKEY_copy_parameters'
../../../lib/libcurl.so: undefined reference to `OPENSSL_sk_pop_free'
../../../lib/libcurl.so: undefined reference to `SSL_CIPHER_get_name'
../../../lib/libcurl.so: undefined reference to `OPENSSL_sk_value'
../../../lib/libcurl.so: undefined reference to `ENGINE_init'
../../../lib/libcurl.so: undefined reference to `CRYPTO_malloc'
../../../lib/libcurl.so: undefined reference to `ASN1_STRING_to_UTF8'
../../../lib/libcurl.so: undefined reference to `X509_load_crl_file'
../../../lib/libcurl.so: undefined reference to `ASN1_STRING_type'
../../../lib/libcurl.so: undefined reference to `RAND_bytes'
../../../lib/libcurl.so: undefined reference to `UI_get_string_type'
../../../lib/libcurl.so: undefined reference to `ENGINE_ctrl_cmd'
../../../lib/libcurl.so: undefined reference to `RSA_free'
../../../lib/libcurl.so: undefined reference to `MD4_Final'
../../../lib/libcurl.so: undefined reference to `SSL_SESSION_free'
../../../lib/libcurl.so: undefined reference to `OCSP_resp_get0'
../../../lib/libcurl.so: undefined reference to `SSL_get_peer_certificate'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_set_default_passwd_cb'
../../../lib/libcurl.so: undefined reference to `UI_method_set_opener'
../../../lib/libcurl.so: undefined reference to `GENERAL_NAMES_free'
../../../lib/libcurl.so: undefined reference to `UI_method_get_writer'
../../../lib/libcurl.so: undefined reference to `BN_print'
../../../lib/libcurl.so: undefined reference to `ASN1_STRING_length'
../../../lib/libcurl.so: undefined reference to `X509_get_serialNumber'
../../../lib/libcurl.so: undefined reference to `UI_create_method'
../../../lib/libcurl.so: undefined reference to `OPENSSL_sk_pop'
../../../lib/libcurl.so: undefined reference to `BIO_free'
../../../lib/libcurl.so: undefined reference to `SHA256_Final'
../../../lib/libcurl.so: undefined reference to `EVP_PKEY_free'
../../../lib/libcurl.so: undefined reference to `X509_get_ext_d2i'
../../../lib/libcurl.so: undefined reference to `PKCS12_PBE_add'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_load_verify_locations'
../../../lib/libcurl.so: undefined reference to `UI_method_get_reader'
../../../lib/libcurl.so: undefined reference to `DES_set_key'
../../../lib/libcurl.so: undefined reference to `SSL_get0_alpn_selected'
../../../lib/libcurl.so: undefined reference to `OPENSSL_load_builtin_modules'
../../../lib/libcurl.so: undefined reference to `DES_ecb_encrypt'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_set_cipher_list'
../../../lib/libcurl.so: undefined reference to `X509_get_subject_name'
../../../lib/libcurl.so: undefined reference to `SSL_get1_session'
../../../lib/libcurl.so: undefined reference to `X509_free'
../../../lib/libcurl.so: undefined reference to `X509_EXTENSION_get_object'
../../../lib/libcurl.so: undefined reference to `UI_method_set_closer'
../../../lib/libcurl.so: undefined reference to `SHA256_Update'
../../../lib/libcurl.so: undefined reference to `EVP_PKEY_get0_DH'
../../../lib/libcurl.so: undefined reference to `PEM_read_X509'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_use_certificate'
../../../lib/libcurl.so: undefined reference to `ERR_error_string_n'
../../../lib/libcurl.so: undefined reference to `CRYPTO_free'
../../../lib/libcurl.so: undefined reference to `OCSP_check_validity'
../../../lib/libcurl.so: undefined reference to `MD5_Final'
../../../lib/libcurl.so: undefined reference to `d2i_OCSP_RESPONSE'
../../../lib/libcurl.so: undefined reference to `OCSP_resp_count'
../../../lib/libcurl.so: undefined reference to `X509_get0_signature'
../../../lib/libcurl.so: undefined reference to `SSL_set_bio'
../../../lib/libcurl.so: undefined reference to `OCSP_cert_status_str'
../../../lib/libcurl.so: undefined reference to `MD4_Init'
../../../lib/libcurl.so: undefined reference to `OCSP_single_get0_status'
../../../lib/libcurl.so: undefined reference to `SHA256_Init'
../../../lib/libcurl.so: undefined reference to `DH_get0_key'
../../../lib/libcurl.so: undefined reference to `SSL_read'
../../../lib/libcurl.so: undefined reference to `SSL_get_verify_result'
../../../lib/libcurl.so: undefined reference to `X509_NAME_get_entry'
../../../lib/libcurl.so: undefined reference to `OCSP_response_status_str'
../../../lib/libcurl.so: undefined reference to `X509_NAME_ENTRY_get_data'
../../../lib/libcurl.so: undefined reference to `BIO_printf'
../../../lib/libcurl.so: undefined reference to `UI_method_get_opener'
../../../lib/libcurl.so: undefined reference to `PEM_write_bio_X509'
../../../lib/libcurl.so: undefined reference to `i2d_X509_PUBKEY'
../../../lib/libcurl.so: undefined reference to `MD5_Init'
../../../lib/libcurl.so: undefined reference to `i2t_ASN1_OBJECT'
../../../lib/libcurl.so: undefined reference to `SSL_ctrl'
../../../lib/libcurl.so: undefined reference to `EVP_PKEY_get0_DSA'
../../../lib/libcurl.so: undefined reference to `X509_EXTENSION_get_data'
../../../lib/libcurl.so: undefined reference to `OPENSSL_sk_num'
../../../lib/libcurl.so: undefined reference to `OCSP_BASICRESP_free'
../../../lib/libcurl.so: undefined reference to `EVP_PKEY_get1_RSA'
../../../lib/libcurl.so: undefined reference to `SSL_pending'
../../../lib/libcurl.so: undefined reference to `X509_get0_notBefore'
../../../lib/libcurl.so: undefined reference to `PKCS12_free'
../../../lib/libcurl.so: undefined reference to `OCSP_basic_verify'
../../../lib/libcurl.so: undefined reference to `ENGINE_get_next'
../../../lib/libcurl.so: undefined reference to `SSL_shutdown'
../../../lib/libcurl.so: undefined reference to `BIO_s_mem'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_set_verify'
../../../lib/libcurl.so: undefined reference to `RAND_status'
../../../lib/libcurl.so: undefined reference to `ENGINE_free'
../../../lib/libcurl.so: undefined reference to `X509_get_issuer_name'
../../../lib/libcurl.so: undefined reference to `SSL_get_current_cipher'
../../../lib/libcurl.so: undefined reference to `SSL_get_peer_cert_chain'
../../../lib/libcurl.so: undefined reference to `EVP_PKEY_get0_RSA'
../../../lib/libcurl.so: undefined reference to `MD4_Update'
../../../lib/libcurl.so: undefined reference to `ENGINE_finish'
../../../lib/libcurl.so: undefined reference to `ASN1_STRING_get0_data'
../../../lib/libcurl.so: undefined reference to `X509_STORE_set_flags'
../../../lib/libcurl.so: undefined reference to `X509_signature_print'
../../../lib/libcurl.so: undefined reference to `ERR_peek_error'
../../../lib/libcurl.so: undefined reference to `CONF_modules_load_file'
../../../lib/libcurl.so: undefined reference to `UI_set_result'
../../../lib/libcurl.so: undefined reference to `X509_verify_cert_error_string'
../../../lib/libcurl.so: undefined reference to `SSL_set_session'
../../../lib/libcurl.so: undefined reference to `ENGINE_get_id'
../../../lib/libcurl.so: undefined reference to `X509_check_issued'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_new'
../../../lib/libcurl.so: undefined reference to `X509_get_version'
../../../lib/libcurl.so: undefined reference to `BIO_f_ssl'
../../../lib/libcurl.so: undefined reference to `ENGINE_ctrl'
../../../lib/libcurl.so: undefined reference to `SSL_version'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_add_client_CA'
../../../lib/libcurl.so: undefined reference to `RAND_load_file'
../../../lib/libcurl.so: undefined reference to `UI_method_set_reader'
../../../lib/libcurl.so: undefined reference to `BIO_new'
../../../lib/libcurl.so: undefined reference to `TLS_client_method'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_set_alpn_protos'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_set_msg_callback'
../../../lib/libcurl.so: undefined reference to `MD5_Update'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_use_certificate_file'
../../../lib/libcurl.so: undefined reference to `X509_STORE_add_lookup'
../../../lib/libcurl.so: undefined reference to `X509_get0_notAfter'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_set_options'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_set_next_proto_select_cb'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_use_certificate_chain_file'
../../../lib/libcurl.so: undefined reference to `SSL_connect'
../../../lib/libcurl.so: undefined reference to `SSL_set_connect_state'
../../../lib/libcurl.so: undefined reference to `UI_method_get_closer'
../../../lib/libcurl.so: undefined reference to `ERR_clear_error'
../../../lib/libcurl.so: undefined reference to `SSL_get_certificate'
../../../lib/libcurl.so: undefined reference to `SSL_free'
../../../lib/libcurl.so: undefined reference to `ASN1_TIME_print'
../../../lib/libcurl.so: undefined reference to `ENGINE_by_id'
../../../lib/libcurl.so: undefined reference arm-linux-gnueabihf-g++: warning: /home/lavender/Work/vishwam_vision/thirdparty/openssl: linker input file unused because linking not done
to `SSL_write'
../../../lib/libcurl.so: undefined reference to `SSL_set_fd'
../../../lib/libcurl.so: undefined reference to `PKCS12_parse'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_use_PrivateKey_file'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_ctrl'
../../../lib/libcurl.so: undefined reference to `X509_NAME_print_ex'
../../../lib/libcurl.so: undefined reference to `i2a_ASN1_OBJECT'
../../../lib/libcurl.so: undefined reference to `UI_method_set_writer'
../../../lib/libcurl.so: undefined reference to `ERR_get_error'
../../../lib/libcurl.so: undefined reference to `ASN1_STRING_new'
../../../lib/libcurl.so: undefined reference to `DES_set_odd_parity'
../../../lib/libcurl.so: undefined reference to `ASN1_STRING_free'
../../../lib/libcurl.so: undefined reference to `SSL_get_privatekey'
../../../lib/libcurl.so: undefined reference to `UI_get_input_flags'
../../../lib/libcurl.so: undefined reference to `ENGINE_get_first'
../../../lib/libcurl.so: undefined reference to `RAND_add'
../../../lib/libcurl.so: undefined reference to `ENGINE_set_default'
../../../lib/libcurl.so: undefined reference to `X509_get_X509_PUBKEY'
../../../lib/libcurl.so: undefined reference to `X509V3_EXT_print'
../../../lib/libcurl.so: undefined reference to `SSL_new'
../../../lib/libcurl.so: undefined reference to `ENGINE_load_private_key'
../../../lib/libcurl.so: undefined reference to `UI_OpenSSL'
../../../lib/libcurl.so: undefined reference to `RAND_file_name'
../../../lib/libcurl.so: undefined reference to `X509_get_pubkey'
../../../lib/libcurl.so: undefined reference to `RSA_flags'

../../../lib/libcurl.so: undefined reference to `OPENSSL_sk_num'
../../../lib/libcurl.so: undefined reference to `SSL_connect'
../../../lib/libcurl.so: undefined reference to `X509_check_issued'
../../../lib/libcurl.so: undefined reference to `SSL_set_bio'
../../../lib/libcurl.so: undefined reference to `EVP_PKEY_id'
../../../lib/libcurl.so: undefined reference to `BIO_free'
../../../lib/libcurl.so: undefined reference to `BIO_s_mem'
../../../lib/libcurl.so: undefined reference to `UI_method_get_reader'
../../../lib/libcurl.so: undefined reference to `UI_get_string_type'
../../../lib/libcurl.so: undefined reference to `BIO_ctrl'
../../../lib/libcurl.so: undefined reference to `DES_set_odd_parity'
../../../lib/libcurl.so: undefined reference to `UI_get0_user_data'
../../../lib/libcurl.so: undefined reference to `X509_get0_notAfter'
../../../lib/libcurl.so: undefined reference to `ENGINE_get_next'
../../../lib/libcurl.so: undefined reference to `PEM_read_X509'
../../../lib/libcurl.so: undefined reference to `EVP_PKEY_get0_DH'
../../../lib/libcurl.so: undefined reference to `MD4_Update'
../../../lib/libcurl.so: undefined reference to `ASN1_STRING_to_UTF8'
../../../lib/libcurl.so: undefined reference to `GENERAL_NAMES_free'
../../../lib/libcurl.so: undefined reference to `PKCS12_free'
../../../lib/libcurl.so: undefined reference to `EVP_PKEY_get0_RSA'
../../../lib/libcurl.so: undefined reference to `SSL_get1_session'
../../../lib/libcurl.so: undefined reference to `SSL_set_session'
../../../lib/libcurl.so: undefined reference to `ASN1_STRING_length'
../../../lib/libcurl.so: undefined reference to `ENGINE_get_first'
../../../lib/libcurl.so: undefined reference to `UI_OpenSSL'
../../../lib/libcurl.so: undefined reference to `UI_method_get_closer'
../../../lib/libcurl.so: undefined reference to `OPENSSL_load_builtin_modules'
../../../lib/libcurl.so: undefined reference to `X509_NAME_get_index_by_NID'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_set_verify'
../../../lib/libcurl.so: undefined reference to `UI_method_set_writer'
../../../lib/libcurl.so: undefined reference to `SSL_SESSION_free'
../../../lib/libcurl.so: undefined reference to `RAND_load_file'
../../../lib/libcurl.so: undefined reference to `MD5_Init'
../../../lib/libcurl.so: undefined reference to `SSL_ctrl'
../../../lib/libcurl.so: undefined reference to `UI_method_get_opener'
../../../lib/libcurl.so: undefined reference to `MD5_Final'
../../../lib/libcurl.so: undefined reference to `UI_method_set_closer'
../../../lib/libcurl.so: undefined reference to `CRYPTO_malloc'
../../../lib/libcurl.so: undefined reference to `X509_STORE_set_flags'
../../../lib/libcurl.so: undefined reference to `PKCS12_PBE_add'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_check_private_key'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_use_certificate_chain_file'
../../../lib/libcurl.so: undefined reference to `OCSP_BASICRESP_free'
../../../lib/libcurl.so: undefined reference to `SSL_get_peer_certificate'
../../../lib/libcurl.so: undefined reference to `BIO_new'
../../../lib/libcurl.so: undefined reference to `BIO_f_ssl'
../../../lib/libcurl.so: undefined reference to `X509_get_subject_name'
../../../lib/libcurl.so: undefined reference to `SSL_free'
../../../lib/libcurl.so: undefined reference to `OCSP_RESPONSE_free'
../../../lib/libcurl.so: undefined reference to `ERR_clear_error'
../../../lib/libcurl.so: undefined reference to `X509_NAME_get_entry'
../../../lib/libcurl.so: undefined reference to `d2i_PKCS12_fp'
../../../lib/libcurl.so: undefined reference to `SHA256_Init'
../../../lib/libcurl.so: undefined reference to `OpenSSL_version_num'
../../../lib/libcurl.so: undefined reference to `OCSP_basic_verify'
../../../lib/libcurl.so: undefined reference to `OPENSSL_sk_pop_free'
../../../lib/libcurl.so: undefined reference to `BIO_puts'
../../../lib/libcurl.so: undefined reference to `i2t_ASN1_OBJECT'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_set_alpn_protos'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_add_client_CA'
../../../lib/libcurl.so: undefined reference to `SSL_get_certificate'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_set_default_passwd_cb_userdata'
../../../lib/libcurl.so: undefined reference to `CRYPTO_free'
../../../lib/libcurl.so: undefined reference to `X509_get_ext_d2i'
../../../lib/libcurl.so: undefined reference to `d2i_OCSP_RESPONSE'
../../../lib/libcurl.so: undefined reference to `SSL_set_connect_state'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_new'
../../../lib/libcurl.so: undefined reference to `OCSP_response_status'
../../../lib/libcurl.so: undefined reference to `SSL_get_verify_result'
../../../lib/libcurl.so: undefined reference to `OCSP_response_status_str'
../../../lib/libcurl.so: undefined reference to `X509_load_crl_file'
../../../lib/libcurl.so: undefined reference to `UI_create_method'
../../../lib/libcurl.so: undefined reference to `SSL_read'
../../../lib/libcurl.so: undefined reference to `RAND_bytes'
../../../lib/libcurl.so: undefined reference to `SSL_set_fd'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_use_PrivateKey'
../../../lib/libcurl.so: undefined reference to `X509_NAME_print_ex'
../../../lib/libcurl.so: undefined reference to `SSL_pending'
../../../lib/libcurl.so: undefined reference to `OPENSSL_sk_pop'
../../../lib/libcurl.so: undefined reference to `X509_verify_cert_error_string'
../../../lib/libcurl.so: undefined reference to `SSL_get_current_cipher'
../../../lib/libcurl.so: undefined reference to `OPENSSL_sk_value'
../../../lib/libcurl.so: undefined reference to `UI_destroy_method'
../../../lib/libcurl.so: undefined reference to `ENGINE_load_private_key'
../../../lib/libcurl.so: undefined reference to `X509_get0_signature'
../../../lib/libcurl.so: undefined reference to `RSA_free'
../../../lib/libcurl.so: undefined reference to `OCSP_crl_reason_str'
../../../lib/libcurl.so: undefined reference to `X509_LOOKUP_file'
../../../lib/libcurl.so: undefined reference to `ENGINE_finish'
../../../lib/libcurl.so: undefined reference to `RAND_add'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_load_verify_locations'
../../../lib/libcurl.so: undefined reference to `X509_get0_extensions'
../../../lib/libcurl.so: undefined reference to `SSL_CIPHER_get_name'
../../../lib/libcurl.so: undefined reference to `ASN1_STRING_type'
../../../lib/libcurl.so: undefined reference to `ASN1_STRING_new'
../../../lib/libcurl.so: undefined reference to `ENGINE_get_id'
../../../lib/libcurl.so: undefined reference to `ERR_get_error'
../../../lib/libcurl.so: undefined reference to `i2a_ASN1_OBJECT'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_set_options'
../../../lib/libcurl.so: undefined reference to `OCSP_cert_status_str'
../../../lib/libcurl.so: undefined reference to `EVP_PKEY_free'
../../../lib/libcurl.so: undefined reference to `SSL_get_privatekey'
../../../lib/libcurl.so: undefined reference to `RAND_file_name'
../../../lib/libcurl.so: undefined reference to `ENGINE_ctrl_cmd'
../../../lib/libcurl.so: undefined reference to `ERR_peek_error'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_use_PrivateKey_file'
../../../lib/libcurl.so: undefined reference to `SHA256_Update'
../../../lib/libcurl.so: undefined reference to `OCSP_check_validity'
../../../lib/libcurl.so: undefined reference to `UI_method_set_opener'
../../../lib/libcurl.so: undefined reference to `X509_signature_print'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_set_default_passwd_cb'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_use_certificate_file'
../../../lib/libcurl.so: undefined reference to `X509V3_EXT_print'
../../../lib/libcurl.so: undefined reference to `MD5_Update'
../../../lib/libcurl.so: undefined reference to `SHA256_Final'
../../../lib/libcurl.so: undefined reference to `EVP_PKEY_get0_DSA'
../../../lib/libcurl.so: undefined reference to `UI_method_get_writer'
../../../lib/libcurl.so: undefined reference to `DSA_get0_key'
../../../lib/libcurl.so: undefined reference to `RSA_get0_key'
../../../lib/libcurl.so: undefined reference to `X509_get_pubkey'
../../../lib/libcurl.so: undefined reference to `X509_get_X509_PUBKEY'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_set_cipher_list'
../../../lib/libcurl.so: undefined reference to `BIO_printf'
../../../lib/libcurl.so: undefined reference to `SSL_new'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_use_certificate'
../../../lib/libcurl.so: undefined reference to `X509_get_serialNumber'
../../../lib/libcurl.so: undefined reference to `UI_get_input_flags'
../../../lib/libcurl.so: undefined reference to `SSL_write'
../../../lib/libcurl.so: undefined reference to `X509_get_version'
../../../lib/libcurl.so: undefined reference to `OCSP_resp_get0'
../../../lib/libcurl.so: undefined reference to `EVP_PKEY_get1_RSA'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_get_cert_store'
../../../lib/libcurl.so: undefined reference to `i2d_X509_PUBKEY'
../../../lib/libcurl.so: undefined reference to `TLS_client_method'
../../../lib/libcurl.so: undefined reference to `OCSP_response_get1_basic'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_set_msg_callback'
../../../lib/libcurl.so: undefined reference to `X509_free'
../../../lib/libcurl.so: undefined reference to `DH_get0_key'
../../../lib/libcurl.so: undefined reference to `X509_get0_notBefore'
../../../lib/libcurl.so: undefined reference to `ERR_error_string_n'
../../../lib/libcurl.so: undefined reference to `DES_set_key'
../../../lib/libcurl.so: undefined reference to `SSL_shutdown'
../../../lib/libcurl.so: undefined reference to `ASN1_TIME_print'
../../../lib/libcurl.so: undefined reference to `SSL_version'
../../../lib/libcurl.so: undefined reference to `DES_ecb_encrypt'
../../../lib/libcurl.so: undefined reference to `ENGINE_set_default'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_set_next_proto_select_cb'
../../../lib/libcurl.so: undefined reference to `X509_STORE_add_lookup'
../../../lib/libcurl.so: undefined reference to `X509_get_issuer_name'
../../../lib/libcurl.so: undefined reference to `RSA_flags'
../../../lib/libcurl.so: undefined reference to `OCSP_single_get0_status'
../../../lib/libcurl.so: undefined reference to `DSA_get0_pqg'
../../../lib/libcurl.so: undefined reference to `X509_EXTENSION_get_object'
../../../lib/libcurl.so: undefined reference to `RAND_status'
../../../lib/libcurl.so: undefined reference to `EVP_PKEY_copy_parameters'
../../../lib/libcurl.so: undefined reference to `X509_EXTENSION_get_data'
../../../lib/libcurl.so: undefined reference to `ENGINE_free'
../../../lib/libcurl.so: undefined reference to `MD4_Final'
../../../lib/libcurl.so: undefined reference to `SSL_get0_alpn_selected'
../../../lib/libcurl.so: undefined reference to `DH_get0_pqg'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_ctrl'
../../../lib/libcurl.so: undefined reference to `BN_print'
../../../lib/libcurl.so: undefined reference to `ASN1_STRING_free'
../../../lib/libcurl.so: undefined reference to `UI_method_set_reader'
../../../lib/libcurl.so: undefined reference to `MD4_Init'
../../../lib/libcurl.so: undefined reference to `CONF_modules_load_file'
../../../lib/libcurl.so: undefined reference to `ASN1_STRING_get0_data'
../../../lib/libcurl.so: undefined reference to `ENGINE_ctrl'
../../../lib/libcurl.so: undefined reference to `X509_NAME_ENTRY_get_data'
../../../lib/libcurl.so: undefined reference to `SSL_get_error'
../../../lib/libcurl.so: undefined reference to `PEM_write_bio_X509'
../../../lib/libcurl.so: undefined reference to `ENGINE_by_id'
../../../lib/libcurl.so: undefined reference to `SSL_CTX_free'
../../../lib/libcurl.so: undefined reference to `OCSP_resp_count'
../../../lib/libcurl.so: undefined reference to `ENGINE_init'
../../../lib/libcurl.so: undefined reference to `PKCS12_parse'
../../../lib/libcurl.so: undefined reference to `ASN1_STRING_print'
../../../lib/libcurl.so: undefined reference to `SSL_get_peer_cert_chain'
../../../lib/libcurl.so: undefined reference to `UI_set_result'

**Comment by levitte** [comment]
Did you perchance forget this when building your program: `-lssl -lcrypto` (must come after `-lcurl`)

**Comment by smartechru** [comment]
As I mentioned above, it works well on my Ubuntu.
The only difference is OpenSSL library reference.
I used system reference when building it on my Ubuntu platform. not cross compile.
To make it work on the Raspberry pi, I need to cross-compile it.
And changed the raspberry pi toolchain like this.
```
set(3RDPARTY ${CMAKE_SOURCE_DIR}/thirdparty)

SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR armv7-a)
# Define the cross compiler locations

SET(CMAKE_C_COMPILER   ${3RDPARTY}/tools/arm-bcm2708/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc)
SET(CMAKE_CXX_COMPILER ${3RDPARTY}/tools/arm-bcm2708/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++)
# Define the sysroot path for the RaspberryPi distribution in our tools folder
SET(CMAKE_FIND_ROOT_PATH ${3RDPARTY}/tools/arm-bcm2708/arm-linux-gnueabihf/arm-linux-gnueabihf/sysroot/)
#SET(CMAKE_SYSROOT ${3RDPARTY}/raspberry-tools/arm-bcm2708/arm-linux-gnueabihf/arm-linux-gnueabihf/sysroot/)
# Use our definitions for compiler tools
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# Search for libraries and headers in the target directories only
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(OPENSSL_ROOT_DIR ${3RDPARTY}/openssl)
SET(OPENSSL_INCLUDE_DIR ${3RDPARTY}/openssl/include) # add /openssl if there is an error
SET(OPENSSL_SSL_LIBRARY ${3RDPARTY}/openssl/lib)
SET(OPENSSL_CRYPTO_LIBRARY ${3RDPARTY}/openssl/lib)
```

**Comment by levitte** [comment]
This is very obviously a problem where som other project isn't linking correctly with openssl libraries, i.e not an issue with openssl per se.

What software is it that you're failing to build? Curl?

**Comment by smartechru** [comment]
But it is working with default OpenSSL libraries.
Let me explain in detail.

The project which I am going to build is located in my Ubuntu.
I've installed OpenSSL 1.1.1 by apt command. `sudo apt install libssl-dev`.
In this case, I don't need to compile OpenSSL because it is done automatically.
And there is no problem to build my project.

The issue occurs when I cross-compile my project.
As I explained above, I have to compile all the dependencies with the arm v7 compiler.
Everything works fine with that, but only OpenSSL doesn't work and gives me error.
I thought it was an OpenSSL cross compile configuration issue.
I hope you understand my logic.

**Comment by levitte** [comment]
I hear what you're saying, but I think you misunderstand the message:

```
../../../lib/libcurl.so: undefined reference to SSL_CTX_free
../../../lib/libcurl.so: undefined reference to X509_NAME_get_index_by_NID
...
```

This tells me that for some reason, when something is linked with libcurl, it also needs to be linked with OpenSSL libraries, and currently is not.

From the CMAKE recipe you're showing us, the OpenSSL libraries are meant to be found in subdirectories of `${3RDPARTY}/openssl`...  so my question is, are the OpenSSL libraries there (presumably in `${3RDPARTY}/openssl/lib`)?  If not, why not?  Have you verified that `${3RDPARTY}` has the value you think it should?

**Comment by smartechru** [comment]
Yes, of course.
I attach the screenshot. I build the openssl with arm-v7 gcc compiler and put them under the ${3RDPARTY} path.
![image](https://user-images.githubusercontent.com/32426840/62386198-b3035d80-b589-11e9-8d83-e74f38b7bf0f.png)

**Comment by levitte** [comment]
I can only conclude that there's a fault somewhere in your build data, 'cause like I said, it seems like your project is simply not linking with OpenSSL libraries when it should.  Have you done a verbose build and actually seen the building commands, those that fail?  What do they look like?

**Comment by levitte** [comment]
Looking again, I see that the directory you display doesn't have the symlinks `libcrypto.so` and `libssl.so`...

**Comment by bug-code** [comment]
how to fix , bro.  I got the same error when  build openssl 1.1.0  or 1.0.2. 
`/home/openssl$ nm -rCu libcrypto.a | grep GENERAL_NAME_free                                                                                                                              U GENERAL_NAME_free                                                                                                                                                                          U GENERAL_NAME_free                                                                                                                                                                          U GENERAL_NAME_free                                                                                                                                                                          U GENERAL_NAME_free                                                                                                                                                                          U GENERAL_NAME_free                                                                                                                                                                          U GENERAL_NAME_free                                                                                                                                                                          U GENERAL_NAME_free                                                                                                                                                                          U GENERAL_NAME_free`
