### ISSUE TITLE
i2d_ECDSA_SIG error return value does not match manpage

### ISSUE THREAD

**Issue by bdonlan** [openssl/openssl#9517]
The [manual page for i2d_ECDSA_SIG](https://www.openssl.org/docs/man1.1.1/man3/i2d_ECDSA_SIG.html) documents it as returning 0 on error. However, in fact, [it returns -1 on error](https://github.com/openssl/openssl/blob/0d03acea7aa45e94903fb12186ed6cc324eb1b03/crypto/ec/ec_asn1.c#L1196).

Additionally, the manpage does not document how it modifies the `*pp` pointer.

**Comment by mattcaswell** [comment]
Fix in #9533.
