### ISSUE TITLE
If the program has an exception that does not call OPENSSL_cleanup, how do I release the memory that was previously requested internally?

### ISSUE THREAD

**Issue by zev-netizen** [openssl/openssl#9521]
Hi, if the program has an exception that does not call OPENSSL_cleanup, how do I release the memory that was previously requested internally? 

The version of OpenSSL I am using is 1.1.1a

**Comment by mattcaswell** [comment]
You can always call OPENSSL_cleanup directly if you so wish. Or alternatively, if the program is exiting, then the OS will release all resources anyway.

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
