### ISSUE TITLE
Could we set unlimited time expiration for key which generating by openssl ( x509)

### ISSUE THREAD

**Issue by kvu-luong** [openssl/openssl#9523]
I wonder if we could unset expiration time for key which generating by openssl. For instance, we have a command like this one.
openssl req -newkey rsa:2048 -nodes -keyout PrivateKey.key -x509 -days 3650 -out certFile.crt
It will set expiration time is 10 years, could we set it forever. Thank you in advance for any answer on this issue

**Comment by kvu-luong** [comment]
I wonder if we could unset expiration time for key which generating by openssl. For instance, we have a command like this one.
openssl req -newkey rsa:2048 -nodes -keyout PrivateKey.key -x509 -days 3650 -out certFile.crt
It will set expiration time is 10 years, could we set it forever. Thank you in advance for any answer on this issue

**Comment by richsalz** [comment]
No, the certificate must have an expiration field, the "notAfter" field in the X509v3 certificate definition.

**Comment by InfoHunter** [comment]
> No, the certificate must have an expiration field, the "notAfter" field in the X509v3 certificate definition.

What @richsalz said is right. I also noticed there is a paragraph in [RFC 5280](https://tools.ietf.org/html/rfc5280), saying:

```
   To indicate that a certificate has no well-defined expiration date,
   the notAfter SHOULD be assigned the GeneralizedTime value of
   99991231235959Z.
```

@kvu-luong , maybe you can consider this time value as the *de facto* "forever" :-)

**Comment by kvu-luong** [comment]
Thank you so much for response on my issue
