### ISSUE TITLE
PKCS7_decrypt with rc4 symmetric alg fail

### ISSUE THREAD

**Issue by haobohuiying** [openssl/openssl#9526]
>>OPENSSL -1.0.1u version
when decrypted rc4 evplope with PKCS7_decrypt，PKCS7_decrypt ->PKCS7_dataDecode ->EVP_CIPHER_asn1_to_param return -1 becuse xx_asn1_parameters of rc4 cipher is NULL

**Comment by agnosticdev** [comment]
Are you able to see what is being set to `&evp_ctx` in:

```c
BIO *PKCS7_dataDecode(PKCS7 *p7, EVP_PKEY *pkey, BIO *in_bio, X509 *pcert)
{
        evp_ctx = NULL;
        BIO_get_cipher_ctx(etmp, &evp_ctx);
        if (EVP_CipherInit_ex(evp_ctx, evp_cipher, NULL, NULL, NULL, 0) <= 0)
            goto err;
        if (EVP_CIPHER_asn1_to_param(evp_ctx, enc_alg->parameter) < 0)
            goto err;

}

```
This should lead us in the direction of why `EVP_CIPHER_asn1_to_param` is returning -1.

**Comment by haobohuiying** [comment]
I created a pkcs7 ciphertxt of RC4 with PKCS7_encrypt method and then decrypted the ciphertxt with PKCS7_decrypt. PKCS7_decrypt failed as decribed above.

**Comment by agnosticdev** [comment]
Thank you.  Based on the report of `EVP_CIPHER_asn1_to_param` returning -1, and the execution path for `PKCS7_decrypt`, it looks like the error is bubbling up from `PKCS7_dataDecode`. 
Here are a few ideas on how to diagnose the issue:

1. Are you able to log or see what is being set in your debugger for `evp_ctx` and `enc_alg->parameter` these values are passed into `EVP_CIPHER_asn1_to_param(evp_ctx, enc_alg->parameter)` in pk7_doit.c?  This will allow visibility into what is occurring in the execution of that function from evp.lib.c.
2. Does the cipher that was created have ANS.1 support?  From the docs, this would cause `EVP_CIPHER_asn1_to_param()` to fail also.
> It is possible for this function to fail if the cipher does not have any ASN1 support or the parameters cannot be set .

**Comment by haobohuiying** [comment]
Many thanks for your suggestion. I hava solved this issues by definiting get_asn1_parameters and  adding it to r4_cipher ctx in e_rc4 as decribed below.

`static int rc4_get_asn1_parameters (EVP_CIPHER_CTX * ctx, ASN1_TYPE * type)
{
return 0;
}

static const EVP_CIPHER r4_cipher = {
    NID_rc4,
    1, EVP_RC4_KEY_SIZE, 0,
    EVP_CIPH_VARIABLE_LENGTH,
    rc4_init_key,
    rc4_cipher,
    NULL,
    sizeof(EVP_RC4_KEY),
    NULL,
    rc4_get_asn1_parameters ,
    NULL,
    NULL
};`

rc4_cipher theoretically don't need to parse asn1_parameters because it is stream cipher. so I belive there is more elegant method to fix this issue.

`int EVP_CIPHER_asn1_to_param(EVP_CIPHER_CTX *c, ASN1_TYPE *type)
{
    int ret;

    if (c->cipher->get_asn1_parameters != NULL)
        ret = c->cipher->get_asn1_parameters(c, type);
    else if (c->cipher->flags & EVP_CIPH_FLAG_DEFAULT_ASN1) {
        switch (EVP_CIPHER_CTX_mode(c)) {

        case EVP_CIPH_GCM_MODE:
        case EVP_CIPH_CCM_MODE:
        case EVP_CIPH_XTS_MODE:
            ret = -1;
            break;

        default:
            ret = EVP_CIPHER_get_asn1_iv(c, type);
            break;
        }
    } else
        ret = -1;
    return (ret);
}`

**Comment by agnosticdev** [comment]
Glad I was able to assist and you were able to resolve the issue.
I see now where it looks like `c->cipher->get_asn1_parameters` was not set causing issues in `EVP_CIPHER_asn1_to_param()`.

If this does resolve the issue please feel free to close.
Thank you!

**Comment by haobohuiying** [comment]
I look forward to you can fix this for avoiding i use my openssl branch instead of offical master branch。
Thank you ！

**Comment by agnosticdev** [comment]
@haobohuiying feel free to create a pull request with your solution for the larger team to review.  If not, please close this ticket.  Thank you!

**Comment by haobohuiying** [comment]
Many thanks for your help. I parse pkcs7 data to get ciphertext  and decrypt through p1 method.
