### ISSUE TITLE
API inconsistency of ERR_PUT_error() and ERR_PUT_func_error()

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#9530]
Since #56c3a135b23, `openssl/err.h` defines the macros `ERR_PUT_error()` and `ERR_PUT_func_error()` regardless of API compatibility, 
while the former macro refers to `ERR_put_error()`, which has been deprecated in 3.0,
and the latter macro refers to `ERR_put_func_error()`, which meanwhile has disappeared entirely.

**Comment by DDvO** [comment]
Moreover, shouldn't the call to `ERR_set_debug()` in
```
#if !OPENSSL_API_3
/* Backward compatibility */
#define ERR_put_error(lib, func, reason, file, line)            \
    (ERR_new(),                                                 \
     ERR_set_debug((file), (line), NULL),                       \
     ERR_set_error((lib), (reason), NULL))
#endif
```
better read as follows?
```
     ERR_set_debug((file), (line), (func)),                     \
```

**Comment by petrovr** [comment]
David von Oheimb wrote:
> Since #56c3a135b23, `openssl/err.h` defines the macros `ERR_PUT_error()` and `ERR_PUT_func_error()` regardless of API compatibility,
> while the former macro refers to `ERR_put_error()`, which has been deprecated in 3.0,
> and the latter macro refers to `ERR_put_func_error()`, which meanwhile has disappeared entirely.

https://github.com/openssl/openssl/issues/9522

**Comment by levitte** [comment]
`ERR_put_func_error` was replaced by something more to the point.  It has never existed in any released OpenSSL, so just do like it never existed.

**Comment by levitte** [comment]
> Moreover, shouldn't the call to `ERR_set_debug()` in
> ```
> #if !OPENSSL_API_3
> /* Backward compatibility */
> #define ERR_put_error(lib, func, reason, file, line)            \
>     (ERR_new(),                                                 \
>      ERR_set_debug((file), (line), NULL),                       \
>      ERR_set_error((lib), (reason), NULL))
> #endif
> ```
> better read as follows?
> ```
>      ERR_set_debug((file), (line), (func)),                     \
> ```

No.  `ERR_put_error()` never dealt with function names.  The `func` that was passed to it was a number, i.e. the old macros `{LIB}_F_{NAME}`.  Those numbers are gone, all existing such macros all have the value 0.

**Comment by petrovr** [comment]
Issue is fixed long time ago. What about to close?
