### ISSUE TITLE
Implementation of Ecdh using Openssl

### ISSUE THREAD

**Issue by smartdeveloper19** [openssl/openssl#9536]
Hello,

Implementation of Ecdh using openssl.

**Comment by mattcaswell** [comment]
It's unclear what you are asking. What are you trying to achieve?

**Comment by smartdeveloper19** [comment]
I want to ask about implementation of Ecdh in OpenSSL.

Do openssl has implementation of Ecdh?

**Comment by mattcaswell** [comment]
Yes. First create two EVP_PKEY objects. One containing the EC_KEY with your private/public pair, and one containing an EC_KEY with the peer's public key. Use `EVP_PKEY_derive_init` and `EVP_PKEY_derive` to derive a shared secret:

https://www.openssl.org/docs/man1.1.1/man3/EVP_PKEY_derive.html

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
