### ISSUE TITLE
Cannot use GCM

### ISSUE THREAD

**Issue by stas730** [openssl/openssl#954]
# openssl (from this source code) enc -aes-256-gcm -in key.key -out encrypted.key
enc: AEAD ciphers not supported
How to install AEAD ciphers?
I need maximal security, so I need GCM. I has an EV Certificate, I need to modify it…

**Comment by stas730** [comment]
Sorry for BIG text. I running this program as root.

**Comment by richsalz** [comment]
It is not possible; the command needs to be updated.  You might have write your own custom code.
See https://rt.openssl.org/Ticket/Display.html?id=4228

**Comment by stas730** [comment]
I don't have access to rt.openssl.org (Login & password).

**Comment by richsalz** [comment]
User guest password guest

**Comment by stas730** [comment]
I find some code (AEAD). Is it working? I can't write my code (C++).
https://boringssl.googlesource.com/boringssl/+/2272/include/openssl/aead.h

**Comment by richsalz** [comment]
I have no idea.

**Comment by stas730** [comment]
And I need answer for this question: what is more secure: CBC, GCM or some other?

**Comment by richsalz** [comment]
The best place to ask general questions is the openssl-users mailing list.  See https://mta.openssl.org
