### ISSUE TITLE
 Issue with OpenSSL CMP

### ISSUE THREAD

**Issue by gezhouyu** [openssl/openssl#9540]
你好，我在使用openssl 时遇到以下问题，需求求助以下:
1、我在使用OpenSSL cmp 模拟客户端申请证书时，报这错误，请问这应该怎么解决？
2、在使用OpenSSL cmp 模拟客户端申请证书时，需要配置什么文件吗？
CMP INFO: using OpenSSL configuration file '/opt/openssl/../openssl-1.1.0j/openssl.cnf'
CMP INFO: no [cmp] section found in config file '/opt/openssl/../openssl-1.1.0j/openssl.cnf'; will thus use just [default] and unnamed section if present
CMP INFO: sending ir
140327457654592:error:27076072:OCSP routines:parse_http_line1:server response error:crypto/ocsp/ocsp_ht.c:260:Code=404
140327457654592:error:390B1091:CMP routines:OSSL_CMP_MSG_http_perform:failed to receive pkimessage:crypto/cmp/cmp_http.c:516:
140327457654592:error:390A1098:CMP routines:OSSL_CMP_exec_IR_ses:ip not received:crypto/cmp/cmp_ses.c:199:

**Comment by mattcaswell** [comment]
Please can you give your questions in English?

**Comment by gezhouyu** [comment]
Hello, I have encountered the following problems when using openssl:
1. When I use the OpenSSL cmp to simulate a client to apply for a certificate, this error is reported. What should I do?
2. When you use the OpenSSL cmp to simulate a client to apply for a certificate, what files need to be configured?
CMP INFO: using OpenSSL configuration file '/opt/openssl/../openssl-1.1.0j/openssl.cnf'
CMP INFO: no [cmp] section found in config file '/opt/openssl/../openssl-1.1.0j/openssl.cnf'; will thus use just [default] and unnamed section if present
CMP INFO: sending ir
140327457654592:error:27076072:OCSP routines:parse_http_line1:server response error:crypto/ocsp/ocsp_ht.c:260:Code=404
140327457654592:error:390B1091:CMP routines:OSSL_CMP_MSG_http_perform:failed to receive pkimessage:crypto/cmp/cmp_http.c:516:
140327457654592:error:390A1098:CMP routines:OSSL_CMP_exec_IR_ses:ip not received:crypto/cmp/cmp_ses.c:199:

**Comment by ladislavnagy** [comment]
ladislavnagy6ln@gmail.com

**Comment by ladislavnagy** [comment]
Android Motorola one

**Comment by ladislavnagy** [comment]
Pleace legali

**Comment by mattcaswell** [comment]
> When I use the OpenSSL cmp to simulate a client to apply for a certificate, this error is reported. What should I do?

In order to be using cmp you must be using the master (development) branch of OpenSSL since that feature does not exist in any released branch. The cmp code is still under development and is not currently in a usable state. E.g. see #9107.

**Comment by gezhouyu** [comment]
Hello, can you provide the OpenSSL software package that supports the cmp function or obtain the OpenSSL software package?

**Comment by mattcaswell** [comment]
Not at this time. This feature is expected to be in the next major release of OpenSSL (OpenSSL 3.0). We expect to release that around Q2 2020.
