### ISSUE TITLE
Cannot get 3DES ciphers in OpenSSL 1.1.1c

### ISSUE THREAD

**Issue by johankleuskens** [openssl/openssl#9541]
Hi,
I am using OpenSSL 1.1.1c and need 3DES ciphers to support some old clients. I can not get these ciphers to show up when getting a list of available ciphers in OpenSSL via "openssl ciphers -V".

I am using OpenSSL on Ubuntu 18.04 and here is how i built it:
- sudo **./Configure  linux-x86_64 enable-tls1_3 enable-weak-ssl-ciphers enable-des**
- sudo make
- sudo make install
 
When querying for available DES ciphers, i get no result ( and my old clients do not connect ether): **openssl ciphers -V | grep DES** returns nothing.

Is this a bug in OpenSSL 1.1.1c or am i doing something wrong?

**Comment by mattcaswell** [comment]
3DES ciphersuites are not in the "DEFAULT" list of ciphersuites. The "openssl ciphers" command takes a cipherstring as a parameter, or uses "DEFAULT" if none is specified. Try:

````
$ openssl ciphers -V ALL | grep DES
          0xC0,0x08 - ECDHE-ECDSA-DES-CBC3-SHA       TLSv1   Kx=ECDH     Au=ECDSA Enc=3DES(168) Mac=SHA1
          0xC0,0x12 - ECDHE-RSA-DES-CBC3-SHA         TLSv1   Kx=ECDH     Au=RSA   Enc=3DES(168) Mac=SHA1
          0x00,0x16 - DHE-RSA-DES-CBC3-SHA           SSLv3   Kx=DH       Au=RSA   Enc=3DES(168) Mac=SHA1
          0x00,0x13 - DHE-DSS-DES-CBC3-SHA           SSLv3   Kx=DH       Au=DSS   Enc=3DES(168) Mac=SHA1
          0xC0,0x17 - AECDH-DES-CBC3-SHA             TLSv1   Kx=ECDH     Au=None  Enc=3DES(168) Mac=SHA1
          0x00,0x1B - ADH-DES-CBC3-SHA               SSLv3   Kx=DH       Au=None  Enc=3DES(168) Mac=SHA1
          0xC0,0x34 - ECDHE-PSK-3DES-EDE-CBC-SHA     TLSv1   Kx=ECDHEPSK Au=PSK   Enc=3DES(168) Mac=SHA1
          0xC0,0x1C - SRP-DSS-3DES-EDE-CBC-SHA       SSLv3   Kx=SRP      Au=DSS   Enc=3DES(168) Mac=SHA1
          0xC0,0x1B - SRP-RSA-3DES-EDE-CBC-SHA       SSLv3   Kx=SRP      Au=RSA   Enc=3DES(168) Mac=SHA1
          0xC0,0x1A - SRP-3DES-EDE-CBC-SHA           SSLv3   Kx=SRP      Au=SRP   Enc=3DES(168) Mac=SHA1
          0x00,0x93 - RSA-PSK-3DES-EDE-CBC-SHA       SSLv3   Kx=RSAPSK   Au=RSA   Enc=3DES(168) Mac=SHA1
          0x00,0x8F - DHE-PSK-3DES-EDE-CBC-SHA       SSLv3   Kx=DHEPSK   Au=PSK   Enc=3DES(168) Mac=SHA1
          0x00,0x0A - DES-CBC3-SHA                   SSLv3   Kx=RSA      Au=RSA   Enc=3DES(168) Mac=SHA1
          0x00,0x8B - PSK-3DES-EDE-CBC-SHA           SSLv3   Kx=PSK      Au=PSK   Enc=3DES(168) Mac=SHA1
````

> sudo ./Configure linux-x86_64 enable-tls1_3 enable-weak-ssl-ciphers enable-des

Also note in your "Configure" line that "enable_tls1_3" is the default anyway so does not need to be specified, and "enable-des" is not required to get 3DES.

**Comment by johankleuskens** [comment]
Thanks for your help, but i still do not see any 3DES cipher. Is there anything else I am missing or do you have any tips for me to check?

**Comment by mattcaswell** [comment]
As long as you have configured with the `enable-weak-ssl-ciphers` option, and you ran the `openssl ciphers` command as I described above then there should be no reason why you don't see the 3DES ciphers. If you're still not getting them, then I think the most likely explanation is that you're not running the version of OpenSSL that you just installed. Please try running the following command:

````
$ openssl version -b -v
````
You should see output like this:
````
OpenSSL 1.1.1c  28 May 2019
built on: Tue Aug  6 21:50:50 2019 UTC
````
If it comes back with a different version, or the build date doesn't match the one you just built then you are probably picking up a system version of OpenSSL rather than the new one.

**Comment by johankleuskens** [comment]
Well, this is going to sound strange and is totally not satisfying, but i got the 3des ciphers showing up in the cipher list. 
I installed an older version (1.1.0j) and this showed the 3DES ciphers, then i installed 1.1.1c again and now it shows the 3DES ciphers. 
I have done my best to check that i did use not any leftover from an older version, and i am pretty sure i did not, but i cannot explain why things are working now.

**Comment by mattcaswell** [comment]
Hmmmm....issues that mysteriously fix themselves are always fun. :-)

Shall we close this issue now?

**Comment by johankleuskens** [comment]
Thanks for your support  Matt, i will close the issue now.

**Comment by ethaniel** [comment]
> or the build date doesn't match the one you just built then you are probably picking up a system version of OpenSSL rather than the new one.

Dear Matt, 

I am having exactly the same problem now, but the "build date" is way far in the past no matter what I do.
Here is my list of commands:

```
cd /tmp
rm -rfv openssl*
wget https://www.openssl.org/source/openssl-1.1.1h.tar.gz
tar -xzf openssl-1.1.1h.tar.gz
cd openssl-1.1.1h
./config enable-weak-ssl-ciphers  -DOPENSSL_TLS_SECURITY_LEVEL=0 enable-des --prefix=/opt/openssl-1.1.1h shared
make
sudo make install
/opt/openssl-1.1.1h/bin/openssl ciphers -V ALL | grep DES # this returns nothing
/opt/openssl-1.1.1h/bin/openssl version -b -v
```
returns:
```
OpenSSL 1.1.1h  22 Sep 2020 (Library: OpenSSL 1.1.1e-dev  xx XXX xxxx)
built on: Wed Jan 15 17:49:05 2020 UTC
```

And I can't get DES to work :(

**Comment by ethaniel** [comment]
Here is the command sequence that worked for me in the end (if somebody else hits the same problem):

```
cd /tmp
rm -rfv openssl*
rm -rfv /opt/openssl*
wget https://www.openssl.org/source/openssl-1.1.1h.tar.gz
tar -xzf openssl-1.1.1h.tar.gz
cd openssl-1.1.1h
./config enable-weak-ssl-ciphers  -DOPENSSL_TLS_SECURITY_LEVEL=0 enable-des --prefix=/opt/openssl-1.1.1h no-shared 
make
sudo make install
```

My original problem was because I was building shared library. Switching to "no-shared" solved the problem for me.

**Comment by kroeckx** [comment]
> OpenSSL 1.1.1h  22 Sep 2020 (Library: OpenSSL 1.1.1e-dev  xx XXX xxxx)

The "openssl" binary is version 1.1.1h, put it's using a shared
library 1.1.1e-dev. It's probably using the shared library from
/usr/lib/ or /usr/local/lib, instead of where you installed the
1.1.1h version too.

If you want to use the shared library, you either need to use
something like LD_LIBRARY_PATH, modify /etc/ld.so.conf, or
set an rpath.

The other option is of course to use static library.
