### ISSUE TITLE
Typo in EBCDIC content

### ISSUE THREAD

**Issue by opensslonzos-github** [openssl/openssl#9548]
There is a typo in the EBCDIC value for TLS_MD_EXTENDED_MASTER_SECRET_CONST.

It is in this file:  \openssl-1.1.1a\include\openssl\tls1.h

EXISTING/BAD 
  #define TLS_MD_EXTENDED_MASTER_SECRET_CONST    "\x65\x78\x74\x65\x63\x64\x65\x64\x20\x6d\x61\x73\x74\x65\x72\x20\x73\x65\x63\x72\x65\x74"

"extecded master secret"
The 5th character is a "c" rather than an "n".

CORRECT VERSION
 #define TLS_MD_EXTENDED_MASTER_SECRET_CONST    "\x65\x78\x74\x65\x6e\x64\x65\x64\x20\x6d\x61\x73\x74\x65\x72\x20\x73\x65\x63\x72\x65\x74"

"extended master secret"

I mention this because it was rather difficult to find and would really appreciate it if this were fixed in the next version of the library - along with re-adding EBCDIC support.

**Comment by mattcaswell** [comment]
By co-incidence I pushed the fix for this issue earlier today: bd1a74f8ee.
