### ISSUE TITLE
EBCDIC support for TLS 1.3 string constants

### ISSUE THREAD

**Issue by opensslonzos-github** [openssl/openssl#9549]
In the file openssl-1.1.1a\ssl\tls13_enc.c  there are no EBCDIC translations for several text constants.  These same constants exist for all the previous text constants for TLS 1.2 and below.
Here are the working fixes for this.

int tls13_hkdf_expand(SSL *s, const EVP_MD *md, const unsigned char *secret,
                             const unsigned char *label, size_t labellen,
                             const unsigned char *data, size_t datalen,
                             unsigned char *out, size_t outlen)
{
#ifdef CHARSET_EBCDIC
    static const unsigned char label_prefix[] = { 0x74, 0x6C, 0x73, 0x31, 0x33, 0x20, 0x00 };
#else
    static const unsigned char label_prefix[] = "tls13 ";
#endif

int tls13_derive_key(SSL *s, const EVP_MD *md, const unsigned char *secret,
                     unsigned char *key, size_t keylen)
{
#ifdef CHARSET_EBCDIC
  static const unsigned char keylabel[] ={ 0x6B, 0x65, 0x79, 0x00 };
#else
  static const unsigned char keylabel[] = "key";
#endif

int tls13_derive_iv(SSL *s, const EVP_MD *md, const unsigned char *secret,
                    unsigned char *iv, size_t ivlen)
{
#ifdef CHARSET_EBCDIC
  static const unsigned char ivlabel[] = { 0x69, 0x76, 0x00 };
#else
  static const unsigned char ivlabel[] = "iv";
#endif

int tls13_derive_finishedkey(SSL *s, const EVP_MD *md,
                             const unsigned char *secret,
                             unsigned char *fin, size_t finlen)
{
#ifdef CHARSET_EBCDIC
  static const unsigned char finishedlabel[] = { 0x66, 0x69, 0x6E, 0x69, 0x73, 0x68, 0x65, 0x64, 0x00 };
#else
  static const unsigned char finishedlabel[] = "finished";
#endif

#ifdef CHARSET_EBCDIC
    static const char derived_secret_label[] = { 0x64, 0x65, 0x72, 0x69, 0x76, 0x65, 0x64, 0x00 };
#else
    static const char derived_secret_label[] = "derived";
#endif

int tls13_change_cipher_state(SSL *s, int which)
{
#ifdef CHARSET_EBCDIC
  static const unsigned char client_early_traffic[]       = {0x63, 0x20, 0x65, 0x20,       /*traffic*/0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x00};
  static const unsigned char client_handshake_traffic[]   = {0x63, 0x20, 0x68, 0x73, 0x20, /*traffic*/0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x00};
  static const unsigned char client_application_traffic[] = {0x63, 0x20, 0x61, 0x70, 0x20, /*traffic*/0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x00};
  static const unsigned char server_handshake_traffic[]   = {0x73, 0x20, 0x68, 0x73, 0x20, /*traffic*/0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x00};
  static const unsigned char server_application_traffic[] = {0x73, 0x20, 0x61, 0x70, 0x20, /*traffic*/0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x00};
  static const unsigned char exporter_master_secret[] = {0x65, 0x78, 0x70, 0x20,                    /* master*/  0x6D, 0x61, 0x73, 0x74, 0x65, 0x72, 0x00};
  static const unsigned char resumption_master_secret[] = {0x72, 0x65, 0x73, 0x20,                  /* master*/  0x6D, 0x61, 0x73, 0x74, 0x65, 0x72, 0x00};
  static const unsigned char early_exporter_master_secret[] = {0x65, 0x20, 0x65, 0x78, 0x70, 0x20,  /* master*/  0x6D, 0x61, 0x73, 0x74, 0x65, 0x72, 0x00};
#else
  static const unsigned char client_early_traffic[] = "c e traffic";
  static const unsigned char client_handshake_traffic[] = "c hs traffic";
  static const unsigned char client_application_traffic[] = "c ap traffic";
  static const unsigned char server_handshake_traffic[] = "s hs traffic";
  static const unsigned char server_application_traffic[] = "s ap traffic";
  static const unsigned char exporter_master_secret[] = "exp master";
  static const unsigned char resumption_master_secret[] = "res master";
  static const unsigned char early_exporter_master_secret[] = "e exp master";
#endif

int tls13_update_key(SSL *s, int sending)
{
#ifdef CHARSET_EBCDIC
  static const unsigned char application_traffic[] = { 0x74, 0x72 ,0x61 ,0x66 ,0x66 ,0x69 ,0x63 ,0x20 ,0x75 ,0x70 ,0x64, 0x00};
#else
  static const unsigned char application_traffic[] = "traffic upd";
#endif

int tls13_export_keying_material(SSL *s, unsigned char *out, size_t olen,
                                 const char *label, size_t llen,
                                 const unsigned char *context,
                                 size_t contextlen, int use_context)
{
    unsigned char exportsecret[EVP_MAX_MD_SIZE];
#ifdef CHARSET_EBCDIC
    static const unsigned char exporterlabel[] = {0x65, 0x78, 0x70, 0x6F, 0x72, 0x74, 0x65, 0x72, 0x00};
#else
    static const unsigned char exporterlabel[] = "exporter";
#endif

int tls13_export_keying_material_early(SSL *s, unsigned char *out, size_t olen,
                                       const char *label, size_t llen,
                                       const unsigned char *context,
                                       size_t contextlen)
{
#ifdef CHARSET_EBCDIC
  static const unsigned char exporterlabel[] = {0x65, 0x78, 0x70, 0x6F, 0x72, 0x74, 0x65, 0x72, 0x00};
#else
  static const unsigned char exporterlabel[] = "exporter";
#endif

**Comment by opensslonzos-github** [comment]
Sorry, I for got to add a couple others.
openssl-1.1.1a\ssl\statem\statem_lib.c
```
static int get_cert_verify_tbs_data(SSL *s, unsigned char *tls13tbs,
                                    void **hdata, size_t *hdatalen)
{
#ifdef CHARSET_EBCDIC
    static const char servercontext[] = { 0x54 ,0x4c ,0x53 ,0x20 ,0x31 ,0x2e ,0x33 ,0x2c ,0x20 ,0x73 ,0x65 ,0x72 ,0x76 ,0x65 ,0x72 ,0x20 ,0x43 ,0x65 ,0x72 ,0x74 ,0x69 ,0x66 ,0x69 ,0x63 ,0x61 ,0x74 ,0x65 ,0x56 ,0x65 ,0x72 ,0x69 ,0x66 ,0x79, 0x00 };
    static const char clientcontext[] = { 0x54 ,0x4c ,0x53 ,0x20 ,0x31 ,0x2e ,0x33 ,0x2c ,0x20 ,0x63 ,0x6c ,0x69 ,0x65 ,0x6e ,0x74 ,0x20 ,0x43 ,0x65 ,0x72 ,0x74 ,0x69 ,0x66 ,0x69 ,0x63 ,0x61 ,0x74 ,0x65 ,0x56 ,0x65 ,0x72 ,0x69 ,0x66 ,0x79, 0x00  };
#else
    static const char servercontext[] = "TLS 1.3, server CertificateVerify";
    static const char clientcontext[] = "TLS 1.3, client CertificateVerify";
#endif
```


openssl-1.1.1a\ssl\statem\extensions.c
```
int tls_psk_do_binder(SSL *s, const EVP_MD *md, const unsigned char *msgstart,
                      size_t binderoffset, const unsigned char *binderin,
                      unsigned char *binderout, SSL_SESSION *sess, int sign,
                      int external)
{
    EVP_PKEY *mackey = NULL;
    EVP_MD_CTX *mctx = NULL;
    unsigned char hash[EVP_MAX_MD_SIZE], binderkey[EVP_MAX_MD_SIZE];
    unsigned char finishedkey[EVP_MAX_MD_SIZE], tmpbinder[EVP_MAX_MD_SIZE];
    unsigned char *early_secret;
#ifdef CHARSET_EBCDIC
    static const unsigned char resumption_label[] = { 0x72, 0x65, 0x64, 0x20, 0x62, 0x69, 0x6E, 0x64, 0x65, 0x72, 0x00 };
    static const unsigned char external_label[]   = { 0x65, 0x78, 0x74, 0x20, 0x62, 0x69, 0x6E, 0x64, 0x65, 0x72, 0x00 };
#else
    static const unsigned char resumption_label[] = "res binder";
    static const unsigned char external_label[] = "ext binder";
#endif

```
openssl-1.1.1a\crypto\rand\drbg_lib.c
```
/* NIST SP 800-90A DRBG recommends the use of a personalization string. */
#ifdef CHARSET_EBCDIC
static const char ossl_pers_string[] = { 0x4f ,0x70 ,0x65 ,0x6e ,0x53 ,0x53 ,0x4c ,0x20 ,0x4e ,0x49 ,0x53 ,0x54 ,0x20 ,0x53 ,0x50 ,0x20 ,0x38 ,0x30 ,0x30 ,0x2d ,0x39 ,0x30 ,0x41 ,0x20 ,0x44 ,0x52 ,0x42 ,0x47 , 0x00};
#else
static const char ossl_pers_string[] = "OpenSSL NIST SP 800-90A DRBG";
#endif

```

There are also a bunch of cases in these files:
openssl-1.1.1a\crypto\x509v3\v3_utl.c 
openssl-1.1.1a\crypto\x509v3\v3_ncons.c
openssl-1.1.1a\crypto\x509\x509_vfy.c
openssl-1.1.1a\crypto\asn1\a_time.c

where constants like 'a' 'z' 'A', 'Z', '0', '9', '_', '.', '-', '@', ':', '/', '+' are interpreted incorrectly by the IBM compilers as EBCDIC.  They need to be set to the correct ASCII indexes/values along the lines of:

```
#ifdef CHARSET_EBCDIC
const char    lower_a = 0x61,     lower_z = 0x7A,     upper_a = 0x41,     upper_z = 0x5A;
 #else
const char    lower_a = 'a',     lower_z = 'z',     upper_a = 'A',     upper_z = 'Z'
 #endif
```

**Comment by mattcaswell** [comment]
Could you create a PR for this?

**Comment by opensslonzos-github** [comment]
Should I still add a PR for this or does your action of adding "bug" and removing "feature" do the same thing?
And **thank you** for taking the time to look at these issues.

**Comment by mattcaswell** [comment]
> Should I still add a PR for this or does your action of adding "bug" and removing "feature" do the same thing?

Yes - please create a PR. That will enable us to properly assess and provide feedback on the code changes you are proposing.

The label change has nothing to do with whether its a PR or not. Its just a classification of the issue. If it's classified as a feature its not eligible for backport to 1.1.1. However I consider this a bug - because it *should* work on EBCDIC systems but doesn't.

**Comment by velemas** [comment]
DTLS1_SCTP_AUTH_LABEL in ssl/ssl_locl.h:

# ifndef OPENSSL_NO_SCTP
#  define DTLS1_SCTP_AUTH_LABEL   "EXPORTER_DTLS_OVER_SCTP"
# endif

"\x45\x58\x50\x4f\x52\x54\x45\x52\x5f\x44\x54\x4c\x53\x5f\x4f\x56\x45\x52\x5f\x53\x43\x54\x50"

**Comment by mattcaswell** [comment]
@velemas this issue is specifically about TLSv1.3 - your post above is about DTLS. Please could you raise that as a separate issue?

Closing this one, since it was fixed by #9556.

**Comment by velemas** [comment]
I got a compilation error with 1.1.1d:
```openssl-1.1.1d/ssl/statem/statem_lib.c:176:` error: expected a "}"```

It points into:
```      static const char *clientcontext = { 0x54, 0x4c, 0x53, 0x20, 0x31, 0x2e,```
Which tries to initialize char pointer with array.

It should be changed into:
```      static const char clientcontext[] = { 0x54, 0x4c, 0x53, 0x20, 0x31, 0x2e,```
or
```      static const char *clientcontext = "\x54\x4c\x53\x20\x31\x2e...```

In the latter case you don't need extra 0x00 in the end.

**Comment by t8m** [comment]
Right, would you open a PR? The first form is better and it should be applied to the non-EBCDIC case as well (change pointer to const char array) similarly to all the other occurences of this pattern.

**Comment by velemas** [comment]
> Right, would you open a PR? The first form is better and it should be applied to the non-EBCDIC case as well (change pointer to const char array) similarly to all the other occurences of this pattern.

Done https://github.com/openssl/openssl/issues/9869
