### ISSUE TITLE
Help on Disabling NEON support in openssl-1.1.1a

### ISSUE THREAD

**Issue by cerium001** [openssl/openssl#9560]
I am building Openssl-1.1.1a for my ARMv7 board with

./Configure no-shared no-idea no-mdc2 no-rc5 no-ec --openssldir=%{openssldir}
make depend
make -f Makefile DIRS="crypto ssl" all
mv libcrypto.a libcrypto.static
mv libssl.a libssl.static
make -f Makefile DIRS="crypto ssl" clean

./Configure shared no-idea no-mdc2 no-rc5 no-ec --openssldir=%{openssldir}

make 
make install

Now the problem is encounter when i try to execute my application on the board.
It gives an exception which occurs due to NEON support is enabled and the Board doesn't support NEON features. Its a very Old board and previously we were using very old openssl version - 1.0.x which didnt have NEON support.

Being a newbie can someone please help me in how can I disable NEON support completely.

**Comment by bernd-edlinger** [comment]
either configure with no-asm or set a environment variable
OPENSSL_armcap=0

**Comment by cerium001** [comment]
Thank-you,

It helped a lot and the application also ran successfully.
