### ISSUE TITLE
ssl/record/rec_layer_s3.c EVP_CIPH_FLAG_TLS1_1_MULTIBLOCK is never true

### ISSUE THREAD

**Issue by guidovranken** [openssl/openssl#9571]
In ssl/record/rec_layer_s3.c, ```EVP_CIPH_FLAG_TLS1_1_MULTIBLOCK``` is reset to 0 if:

```c
#if     defined(OPENSSL_SMALL_FOOTPRINT) || \
        !(      defined(AES_ASM) &&     ( \
                defined(__x86_64)       || defined(__x86_64__)  || \
                defined(_M_AMD64)       || defined(_M_X64)      ) \
        )
# undef EVP_CIPH_FLAG_TLS1_1_MULTIBLOCK
# define EVP_CIPH_FLAG_TLS1_1_MULTIBLOCK 0
#endif
```

When I compile and build OpenSSL, ```AES_ASM``` is defined when compiling the crypto subsystem, but not when compiling the SSL code. Hence, ```EVP_CIPH_FLAG_TLS1_1_MULTIBLOCK``` always gets redefined to 0, and some code in that file will never be compiled, unless the user explicitly configures with ```CFLAGS=-DAES_ASM```.

Is this intentional or a bug?

**Comment by mattcaswell** [comment]
It's a bug. Fix in #9574. This only seems to impact master.
