### ISSUE TITLE
A long lock occurred when calling the function of libcrypto.so (ERR_put_error())

### ISSUE THREAD

**Issue by githubkimizhou** [openssl/openssl#9583]
We use an open source software called freeswitch, which uses the libcrypto to encrypt and decrypt media packets(SRTP). When the traffic reaches a high amount, the thread that processes the media packets will hang for a long time. I used gdb to debug the call stack and found that a large number of threads had a long wait for locks when calling libcrypto's function. The first picture shows the thread waiting for the lock, and the second picture shows the thread holding the lock. Both threads have a call to ERR_put_error(), what does this mean?. Can friends tell me how to solve this problem? Thank you！

PS: 
openssl version: 1.0.1t (still have same problem after upgrading to 1.0.2s)

Call stack displayed using gdb：
![IMG20190814_115220](https://user-images.githubusercontent.com/11866144/62993505-1ba3e180-be8a-11e9-89cd-851cfb069364.png)
![IMG20190814_115246](https://user-images.githubusercontent.com/11866144/62993508-20689580-be8a-11e9-8152-78d2e2860348.png)

)

**Comment by richsalz** [comment]
The 1.0.1 release has been unsupported for years; the 1.0.2 release is in security-fixes-only mode for four more months and then is unsupported.

The threads and locking approach changed *a great deal* in the 1.1.0 release.  If you can upgrade, you should.

**Comment by davidben** [comment]
In particular, the pre-1.1.0 error queue behavior included a global lock and global hash table lookups. In some workloads, it was quite prone to thread contention. 1.1.0 uses thread-locals instead, which should perform much better.

**Comment by githubkimizhou** [comment]
> The 1.0.1 release has been unsupported for years; the 1.0.2 release is in security-fixes-only mode for four more months and then is unsupported.
> 
> The threads and locking approach changed _a great deal_ in the 1.1.0 release. If you can upgrade, you should.

Thank you very much for your answer. I just compiled the openssl-1.1.0t version and set the LD_LIBRARY_PATH to point to the installation directory of openssl-1.1.0t. I used ldd to see that the open source software I used depends on libcrypto.so.1.0.0, so I made a soft link: libcrypto.so.1.0.0 -> libcrypto.so.1.1.0. But when the program starts, an error occurs, as shown below. What is the cause of this? Thank you!

![IMG20190815_103719](https://user-images.githubusercontent.com/11866144/63069227-b4993200-bf48-11e9-846f-c6cf52216cfb.png)

**Comment by githubkimizhou** [comment]
> In particular, the pre-1.1.0 error queue behavior included a global lock and global hash table lookups. In some workloads, it was quite prone to thread contention. 1.1.0 uses thread-locals instead, which should perform much better.

Thank you very much for your answer. I just compiled the openssl-1.1.0t version and set the LD_LIBRARY_PATH to point to the installation directory of openssl-1.1.0t. I used ldd to see that the open source software I used depends on libcrypto.so.1.0.0, so I made a soft link: libcrypto.so.1.0.0 -> libcrypto.so.1.1.0. But when the program starts, an error occurs, as shown below. What is the cause of this? Thank you!

![IMG20190815_103719](https://user-images.githubusercontent.com/11866144/63069253-d1ce0080-bf48-11e9-8840-af900b2f84c2.png)

**Comment by mattcaswell** [comment]
> But when the program starts, an error occurs, as shown below. What is the cause of this? Thank you!

1.1.x is not ABI compatible with 1.0.x. The packages that depend on OpenSSL 1.0.x need to be recompiled, and often changed, to work with 1.1.x.

**Comment by mspncp** [comment]
Can this issue be closed?

**Comment by levitte** [comment]
Yes
