### ISSUE TITLE
X509_set0_sm2_id() and X509_get0_sm2_id() API's are not validating input parameters for NULL.

### ISSUE THREAD

**Issue by hareesh-d** [openssl/openssl#9585]
X509_set0_sm2_id() and X509_get0_sm2_id() API's are not validating input parameters for NULL.

I see at least destination pointer is validated for NULL in most of the set** variant API's.

So, can we validate in these API's also?

**Comment by mspncp** [comment]
Our simple structure accessor methods normally don't do NULL pointer checks on the structure pointer. It is not allowed to pass invalid pointers and considered a programming error similar, to the case when you access `p->member` without checking `p` first: also the compiler creates code which simply crashes in that case and does not 'return' some (ignorable) error. Adding all these NULL pointer checks to the simple accessors would unnecessarily bloat the code and harm performance.

As for the 'return pointers': I think you mean functions like the following:

https://github.com/openssl/openssl/blob/master/crypto/x509/x_x509.c#L243-L250

Here the situation is slightly different: those accessors allow to obtain several member values in a single call. But the out pointers are optional, you can provide NULL for values you are not interested in.

So I would say: it's not a bug, it works as designed.

**Comment by hareesh-d** [comment]
Thanks for reply.

I was actually taking reference of API's like OSSL_CMP_CTX_set0_pkey(), X509_set_pubkey(), X509_set_serialNumber() etc..

In these cases everywhere I see "X509 *x" or "OSSL_CMP_CTX *ctx" is checked for NULL first.

**Comment by mspncp** [comment]
Well, different people have different opinions and it's an open source project. There have been some general debates about usefulness of NULL pointer checks, but as far as I recall, the majority of contributors here currently shares my viewpoint (no guarantee, my opinion might be biased).

**Comment by hareesh-d** [comment]
I got your point. Thanks.

**Comment by InfoHunter** [comment]
> but as far as I recall, the majority of contributors here currently shares my viewpoint.

Right, especially when they are newly adding APIs. ;-)
