### ISSUE TITLE
Can openssl  support to parse digital envelope of sm2?

### ISSUE THREAD

**Issue by ZMHCL** [openssl/openssl#9588]
Digital envelope of sm2, just like :

```
SM2EnvelopedKey   ::= SEQUENCE {
--
    symAlgID                        AlgorithmIdentifier,
    symEncryptedKey                 SM2Cipher,
    Sm2PublicKey                    SM2PublicKey,
    Sm2EncryptedPrivateKey          BIT STRING  eKey
}
```

Can openssl  support to parse digital envelope of sm2?  And how ?

**Comment by InfoHunter** [comment]
Can you point us what standard defines this structure?

**Comment by ZMHCL** [comment]
> Can you point us what standard defines this structure?

GM/T 0009-2012

**Comment by ZMHCL** [comment]
@InfoHunter ，when  process sm2 digital envelope, firstly i use  d2i_PKCS7_bio 、PEM_read_bio_PKCS7  to get PKCS7(base64 or not),  but all returns are null. openssl  does not  support this Asn.1 format ?

**Comment by InfoHunter** [comment]
It looks like the SM2 enveloped key format defined in GM/T 0009-2012 is not a PKCS#7 object...

**Comment by ZMHCL** [comment]
@InfoHunter   Format of encrypted data just like  GM/T 0009-2012 7.2, can openssl  parse？ i use  sm2_decrypt to decode the data,  d2i_SM2_Ciphertext return NULL。But if i decode data encoded by openssl itself(sm2_encrypt), no error appear.
 
SM2Cipher   ::= SEQENCE{ |  
-- | --
XCoordinate      INTEGER,           -- x分量
YCoordinate       INTEGER,          -- y分量
HASH       OCTET   STRING SIZE(32),      -- 杂凑值
CipherText   OCTET   STRING     -- 密文
}

**Comment by InfoHunter** [comment]
OpenSSL has already supported the format of SM2Cipher defined in Section 7.2 of GM/T 0009-2012:

https://github.com/openssl/openssl/blob/aee6e29f0e88df18ebc21dbcf9d4d5794d7511e0/crypto/sm2/sm2_crypt.c#L32-L39

If you cannot decode a piece of data generated from other place rather than OpenSSL, one possible way of finding out the issue is to compare the encoded SM2Cipher ASN.1 data between OpenSSL and your own software. For instance, use `i2d_SM2_Ciphertext` to generate a SM2Cipher data and check its structure against your own data by using `openssl asn1` tool

**Comment by InfoHunter** [comment]
You can also paste the results of `openssl asn1` here and then we could see what is going wrong with the ASN.1 encoding...

**Comment by ZMHCL** [comment]
I did as you said，found that  the encrypted data from other place is UNKONW  TAG in ASN.1 Editor,while  from OpenSSL is  
(0, 123) SEQUENCE 
 (2, 33) INTEGER 
 (37, 33)INTEGER
 (72, 32)OCTET STRING
(106, 17)OCTET STRING

**Comment by levitte** [comment]
@InfoHunter, I would like to point out that `SM2Cipher` and `SM2_Ciphertext` are two different things...

**Comment by ZMHCL** [comment]
I  take the SM2Cipher part of the digital envelope,  and decrypt it , the result is ok. Now i can confirm  the data is not  formed in the format of envelopeddata , just formed in the format of  description in Section 7.2 of GM/T 0009-2012.  Thanks for your advice ，  @InfoHunter 

Key pair protection data format

**Comment by InfoHunter** [comment]
> @InfoHunter, I would like to point out that SM2Cipher and SM2_Ciphertext are two different things...

> Now i can confirm the data is not formed in the format of envelopeddata , just formed in the format of description in Section 7.2 of GM/T 0009-2012.

Hmmm, I found that there are two ASN.1 structures defined in GM/T 0009-2012, one is called 'SM2Cipher' mentioned in https://github.com/openssl/openssl/issues/9588#issuecomment-521479850, which is defined as 'SM2_Ciphertext' (mentioned in https://github.com/openssl/openssl/issues/9588#issuecomment-521482621)in OpenSSL...

The other one is called 'SM2EnvelopedKey' (https://github.com/openssl/openssl/issues/9588#issue-480671917), which has a field of the type of SM2Cipher (or SM2_Ciphertext in OpenSSL's name...).

We currently only support the SM2Cipher/SM2_Ciphertext encoding, which is an encoding for organizing a piece of encrypted data which is encrypted by SM2 asymmetric key. While 'SM2EnvelopedKey' is a structure to hold encrypted SM2 asymmetric key pair (like what PKCS#8 does), which has not been supported by OpenSSL yet. And there is no further plan to support that by now... @ZMHCL @levitte right?

**Comment by levitte** [comment]
Oh, so they *are* the same thing?  Sorry, my bad...

Se SM2EnvelopedKey, it's like you say, there are no current plans.  However, it might just be a PR away, if anyone is inclined (PR welcome!  However, it needs to be understood that there are higher priority items).

**Comment by InfoHunter** [comment]
> Oh, so they are the same thing?

From my understandings, yes. Because the only place that uses this ASN.1 structure is in the sm2 encrypt functions...

> However, it might just be a PR away, if anyone is inclined (PR welcome! However, it needs to be understood that there are higher priority items).

Right. Don't know if this envelop format is widely used or not...

**Comment by ZMHCL** [comment]
They call “SM2EnvelopedKey“” defined  in Section 7.4 of GM/T 0009-2012 digital envelope， but there is “EnvelopedData” defined  in Section 9.1 of GM/T 0010-2012. Now this envelop format they think is not  widely used， just used in  a small range. @InfoHunter

**Comment by ZMHCL** [comment]
https://github.com/openssl/openssl/issues/9588#issuecomment-521552065，what  i want to say is that they call “SM2EnvelopedKey“ not “EnvelopedData”   digital envelope,

**Comment by ZMHCL** [comment]
> I take the SM2Cipher part of the digital envelope, and decrypt it , the result is ok. Now i can confirm the data is not formed in the format of envelopeddata , just formed in the format of description in Section 7.4 of GM/T 0009-2012. Thanks for your advice ， @InfoHunter

what i want to say is that they call “SM2EnvelopedKey“ not “EnvelopedData” digital envelope,

**Comment by InfoHunter** [comment]
Never known there is an "EnvelopedData" format...
