### ISSUE TITLE
Missing symbolic link from "include/openssl/idea.h"

### ISSUE THREAD

**Issue by abegent21** [openssl/openssl#959]
Missing symbolic link from include/openssl/idea.h

I got error build failed by missing symbolic links from `include/openssl/idea.h` and `mdc2.h` with tar.gz from official website.
In openssl-1.0.1p tyhe symbolic link to `../../crypto/idea/idea.h` was exist but in openssl-1.0.1q the link was deleted.

I got recover by fixing the symblic link from manually operation.

Enviromnents:
OS:CentOS6.7
openssl:openssl-1.0.1q, openssl-1.0.1s
build-option:no-rc5 no-mdc2 no-idea

**Comment by richsalz** [comment]
do a 'make depend'

**Comment by dleonard0** [comment]
Sometimes need `make dclean && make depend` when building from release tars.
