### ISSUE TITLE
Data race in EVP_KEYEXCH_fetch()

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#9592]
`EVP_KEYEXCH_fetch` first calls `evp_generic_fetch()` and then separately fetches an `EVP_KEYMGMT` object. Finally it associates the EVP_KEYMGMT object with the `EVP_KEYEXCH` object. However as soon as `evp_generic_fetch` returns the EVP_KEYEXCH object has been cached and may be returned by an `EVP_KEYEXCH_fetch` call from another thread. So now the threads are competing to associate the EVP_KEYEXCH object with an EVP_KEYMGMT object.

**Comment by mattcaswell** [comment]
Note there is a similar issue in `EVP_CIPHER_fetch` and `EVP_MD_fetch`. #9590 attempts to resolve the issues in those functions.

**Comment by levitte** [comment]
A thought: maybe the association should happen in `evp_keyexch_from_dispatch` instead of in `EVP_KEYEXCH_fetch()`.  It means that we need to pass down the library context and the properties, but I think we can live with that...

**Comment by mattcaswell** [comment]
That was the solution I came up with for `EVP_CIPHER_fetch` and `EVP_MD_fetch` in #9590, although there the issue was quite a bit simpler.
