### ISSUE TITLE
Stderr used eventhough no-stdio defined

### ISSUE THREAD

**Issue by feliwir** [openssl/openssl#9597]
Version: OpenSSL 1.1.1c

Explanation:
I'm compiling OpenSSL for Android and using the no-stdio option

Problem: 
When compiling OpenSSL with -no-stdio there is still stderr used:
https://github.com/openssl/openssl/blob/master/crypto/engine/eng_openssl.c#L195

Solution:
There should be no fprintf when no-stdio is defined

**Comment by levitte** [comment]
Don't define `TEST_ENG_OPENSSL_RC4_P_INIT`

**Comment by levitte** [comment]
Ah, we're actually defining it unconditionally...  Ok, fix coming up

**Comment by levitte** [comment]
#9598 should fix it, please try that patch

**Comment by feliwir** [comment]
Thanks @levitte i already fixed it locally :) Just wanted to make sure this makes it into the next version
