### ISSUE TITLE
/usr/bin/ld: cannot find crti.o: No such file or directory

### ISSUE THREAD

**Issue by Re-bin** [openssl/openssl#9611]
**/usr/bin/ld: cannot find crti.o: No such file or directory**
How can I fix this?

**Comment by levitte** [comment]
Maybe tell us what you tried to do?  Start with how you configured OpenSSL

**Comment by Re-bin** [comment]
> Maybe tell us what you tried to do? Start with how you configured OpenSSL

Thank you for your reply.
I am trying to install the OpenSSL in my computer by compiling, but it always come to the same problem:
**/usr/bin/ld: cannot find crti.o: No such file or directory**
Here is the information displayed in the terminal:


ar: creating libssl.a
ar: creating libcrypto.a
LD_LIBRARY_PATH=: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DPOLY1305_ASM -DOPENSSLDIR="/home/loongson/AnyQ-master/build/third_party/ssl" -DENGINESDIR="/home/loongson/AnyQ-master/build/third_party/lib/engines-1.1" -Wall -O3 -pthread -mabi=n32 -DBN_DIV3W -mips3 -Wa,--noexecstack -fPIC -mabi=n32 -shared -Wl,-Bsymbolic -Wl,-soname=libcrypto.so.1.1 -o ./libcrypto.so.1.1 -Wl,--whole-archive,--version-script=crypto.map ./libcrypto.a -Wl,--no-whole-archive -ldl
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/lib64/libdl.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status

**Comment by Re-bin** [comment]
> Maybe tell us what you tried to do? Start with how you configured OpenSSL

Thank you for your reply.
I am trying to install the OpenSSL in my computer by compiling, but it always come to the same problem:
/usr/bin/ld: cannot find crti.o: No such file or directory
Here is the information displayed in the terminal:

ar: creating libssl.a
ar: creating libcrypto.a
LD_LIBRARY_PATH=: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DPOLY1305_ASM -DOPENSSLDIR="/home/AnyQ-master/build/third_party/ssl" -DENGINESDIR="/home/AnyQ-master/build/third_party/lib/engines-1.1" -Wall -O3 -pthread -mabi=n32 -DBN_DIV3W -mips3 -Wa,--noexecstack -fPIC -mabi=n32 -shared -Wl,-Bsymbolic -Wl,-soname=libcrypto.so.1.1 -o ./libcrypto.so.1.1 -Wl,--whole-archive,--version-script=crypto.map ./libcrypto.a -Wl,--no-whole-archive -ldl
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/lib64/libdl.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
