### ISSUE TITLE
Separate doc-nits as a separate travis build?

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#9616]
Should "make doc-nits" be its own travis job? It seems to be a common reason for corrections and it seems most contributors don't look at the CI build outputs.  Maybe even a separate "nits" CI task separate from travis?

**Comment by paulidale** [comment]
This seems like an eminently reason suggestion.

**Comment by levitte** [comment]
Actually, our current `.travis.yml` has a bug, it won't stop at doc-nits errors (or make update errors). That makes them hard to find. So maybe fix that issue first?

**Comment by richsalz** [comment]
The .travis.yml file is littered with "false" and perhaps those should be ```travis_terminate```  See https://medium.com/@manjula.cse/how-to-stop-the-execution-of-travis-pipeline-if-script-exits-with-an-error-f0e5a43206bf

**Comment by richsalz** [comment]
Closing since #9620 was merged.
