### ISSUE TITLE
/usr/lib64/libdl.so: error adding symbols: File in wrong format

### ISSUE THREAD

**Issue by Re-bin** [openssl/openssl#9617]
**/usr/lib64/libdl.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status**
When I was trying to install the Openssl_1_1_0 by compiling. I got this error.

**Comment by Re-bin** [comment]
Please tell me how to solve this problem. Thank you so mush.

**Comment by goodpaperman** [comment]
same error encountered, if you solved this problem, tell me the way, tks

**Comment by wangwanchao** [comment]
same problem,Had you solved this?

**Comment by kaduk** [comment]
It is very hard to make progress on a topic like this without some knowledge of the scenario -- what OS is involved, what openssl configuration, etc. Further note that OpenSSL 1.1.0 (if indeed the later reports are also with 1.1.0) is EOL.
