### ISSUE TITLE
broken links in manpages

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#9657]
There are over 70 errors in the links in the manpages.
```
; ./util/find-doc-nits -l | wc
     72     358    5615
; 
```

Perhaps these should be fixed up and then -l added to the doc-nits target?

Most of these seem to be from documentation added for 3.0

**Comment by levitte** [comment]
In what branch do you get that?  I just tried on the master branch, freshly updated, and this is what I got:

```
: ; ../master/util/find-doc-nits -l
doc/man7/openssl_user_macros.pod:1: reference to non-existing OPENSSL_VERSION_NUMBER(3)
: ; pwd
/home/levitte/gitwrk/openssl.net/official/_build
```

**Comment by levitte** [comment]
Oh!  Never mind, it's apparently different to run in the build directory...

**Comment by levitte** [comment]
There are some false ones:

```
doc/man3/EVP_aes.pod:1: missing EVP_aes
doc/man3/EVP_aria.pod:1: missing EVP_aria
doc/man3/EVP_camellia.pod:1: missing EVP_camellia
doc/man3/EVP_des.pod:1: missing EVP_des
doc/man5/fips_config.pod:1: missing fips_config
```

Most of these are marked generic, while `fips_config` is man5, so also considered generic by other parts of the script.

**Comment by levitte** [comment]
More false ones:

```
doc/internal/man3/ossl_algorithm_do_all.pod:1: reference to non-existing ossl_construct_method(3)
doc/internal/man3/ossl_algorithm_do_all.pod:1: reference to non-existing ossl_construct_method(3)
```

I guess find-doc-nits doesn't handle the internal docs path correctly

**Comment by richsalz** [comment]
Superceeded by #10109
