### ISSUE TITLE
pkeyutl -verifyrecover error "input data too long to be a hash"

### ISSUE THREAD

**Issue by yaoz39** [openssl/openssl#9658]
Before 1.1.1, the following commands work as expected:
```
echo "abcdefgABCDEFG0123456789" >file
openssl genrsa -out key.pem 4096
openssl pkeyutl -sign -in file -inkey key.pem -out sig
openssl pkeyutl -verifyrecover -in sig -inkey key.pem
```
In 1.1.1, the -verifyrecover command returns
```
Error: The input data looks too long to be a hash
```

The commands are from pkeyutl examples
https://www.openssl.org/docs/man1.1.1/man1/openssl-pkeyutl.html

**Comment by mattcaswell** [comment]
Confirmed as a bug. Unlike in a -verify operation, the file provided via "-in" is the signature itself, and not expected to be a hash. Therefore we shouldn't be attempting to check that it looks like a hash.

**Comment by denebolar** [comment]
Could you please let us know when this fix is going to be released?

**Comment by mspncp** [comment]
@mattcaswell it looks like your fix was not cherry-picked to 1.1.1?

**Comment by denebolar** [comment]
It is not mine, but it was definitely not included in the 1.1.1 branch.

**Comment by mspncp** [comment]
> It is not mine,

I know, I was talking to @mattcaswell, because he provided the fix #9731. Sorry for the misunderstanding.

**Comment by mattcaswell** [comment]
> I know, I was talking to @mattcaswell, because he provided the fix #9731. Sorry for the misunderstanding.

Oops. My mistake. I have cherry-picked it now.

**Comment by mshwf** [comment]
I have the same error:
command:
`openssl pkeyutl -sign -in digest.txt -out sig.txt -inkey private.pem`
> Error: The input data looks too long to be a hash
error in pkeyutl

version:
`OpenSSL 1.1.1g  21 Apr 2020`

**Comment by ip75** [comment]
workaround is:

`openssl sha512 -sha512 -sign internal/license/keys.pem -out sign.bin -keyform pem build/server`

**Comment by cconstab** [comment]
Work around does not work if you are keeping your keys in a TPM...

root@qth:/home/pi/demo# openssl pkeyutl -engine tpm2tss -keyform engine -inkey key.pair -sign -in hash.data -out sign.data
engine "tpm2tss" set.
Enter password for user key:
Error: The input data looks too long to be a hash
root@qth:/home/pi/demo#
