### ISSUE TITLE
 Logotype extensions not working

### ISSUE THREAD

**Issue by stas730** [openssl/openssl#966]
I want to add logotype extension to my CA certificate.
I added this lines to config: https://mta.openssl.org/pipermail/openssl-users/2015-January/000285.html
I need to remove OID, because ASN1:SEQUENCE not recognized by OpenSSL. There is no logo in certificate.
Is it an OpenSSL bug? Or I need to add another lines to config?

**Comment by richsalz** [comment]
the logotype extension is not supported.  you can probably do it by adding "raw" extension information in the conf file.  please post to openssl-users, https://mta.openssl.org for information about the mailing lists.

**Comment by stas730** [comment]
How to add raw extension and use it? I have a data (logo and hash). I need to do this:
[ logo ]
ASN1:UTF8String={
ASN1:UTF8String= {
…
and use this extension?

**Comment by stas730** [comment]
I think, it is my latest OpenSSL question. So, I doesn't see reason to post this message on openssl-users.
I found answers for my previous questions (I accidentally added TLS 1.2 to "-" in Apache, I need only browser "GCM" cipher).

**Comment by stas730** [comment]
I need working "Logotype" extension. Working logotype extension is CRITICAL for me.

**Comment by stas730** [comment]
Please, sorry for many messages. But I need working OID's too.

**Comment by richsalz** [comment]
As I said, use the mailing list.

**Comment by willie3535** [comment]
I know

**Comment by stas730** [comment]
Done. I implemented it.
