### ISSUE TITLE
target already defined - ssp-buffer-size=4 (offending arg: linux-armv4)

### ISSUE THREAD

**Issue by yangyangtiantianlonglong** [openssl/openssl#9663]
**issue：**
```javascript
OpenSSL> version
OpenSSL 1.1.1a  20 Nov 2018

./Configure -d  no-ui-console no-asm   no-shared  -fstack-protector-strong  -Wfloat-equal -Wshadow -fPIE -msoft-float -fno-common -MD -Wextra -Wformat-nonliteral -Wformat-security -Wswitch-default -ffunction-sections -fdata-sections -fno-omit-frame-pointer -mapcs-frame -fstrength-reduce -fno-strict-aliasing -DNDEBUG -mlittle-endian --param ssp-buffer-size=4 -g0 -O2 -Wall -Wcast-align -Wpointer-arith  ARFLAGS="cr" --cross-compile-prefix="arm32-linux-gnueabi-"  -DCODE_BRANCH_FLAGS="openssl" linux-armv4

Failure!  build file wasn't produced.
Please read INSTALL and associated NOTES files.  You may also have to look over
your available compiler tool chain or change your configuration.

target already defined - ssp-buffer-size=4 (offending arg: linux-armv4)
```
**The issue fail where follow：**
https://github.com/openssl/openssl/blob/d1c28d791a7391a8dc101713cd8646df96491d03/Configure#L875-L879

https://github.com/openssl/openssl/blob/d1c28d791a7391a8dc101713cd8646df96491d03/Configurations/10-main.conf#L683-L717

https://github.com/openssl/openssl/blob/d1c28d791a7391a8dc101713cd8646df96491d03/Configurations/10-main.conf#L635-L657

And according to the failure prompt, I can't find the definition "linux-armv4 --param ssp-buffer-size=4"，How can I find it?

**Comment by mspncp** [comment]
Because of the space inbetween, `--param ssp-buffer-size=4`, the Configure script does not recognize `ssp-buffer-size=4` as part of the option argument. Please try whether `--param=ssp-buffer-size=4` works for you.

**Comment by yangyangtiantianlonglong** [comment]
Your approach is correct, thank you for your reply！
