### ISSUE TITLE
gcc: error: unrecognized command line option '-mlittle-endian'; did you mean '-fconvert=little-endian'?

### ISSUE THREAD

**Issue by dixyang** [openssl/openssl#9665]
```
gcc: error: unrecognized command line option '-mlittle-endian'; did you mean '-fconvert=little-endian'? 
```

when i compile the project an error occuer with failure infomatiom : `gcc: error: unrecognized command line option '-mlittle-endian'; did you mean '-fconvert=little-endian'?`

but when i run :

```
./Configure -no-asm -O0 -m32 -pipe -fstack-protector-all -fpic -funwind-tables -DNDEBUG -mlittle-endian linux-x86
Configuring OpenSSL version 1.1.1a (0x1010101fL) for linux-x86
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile

**********************************************************************
***                                                                ***
***   OpenSSL has been successfully configured                     ***
***                                                                ***
***   If you encounter a problem while building, please open an    ***
***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
***   and include the output from the following command:           ***
***                                                                ***
***       perl configdata.pm --dump                                ***
***                                                                ***
***   (If you are new to OpenSSL, you might want to consult the    ***
***   'Troubleshooting' section in the INSTALL file first)         ***
***                                                                ***
**********************************************************************
```

it is successful to create Makefile

**Comment by dixyang** [comment]
OpenSSL> version
OpenSSL 1.1.1a  20 Nov 2018

**Comment by dixyang** [comment]
my quession is how can i know which options is recognized ?
please show me the trick

**Comment by dixyang** [comment]
when changed -mlittle-endian to -fconvert=little-endian ,a warning occur : command line option '-fconvert=little-endian' is valid for Fortran but not for C

**Comment by dixyang** [comment]
#### X86 / X86_64 targets
    "linux-x86" => {
        inherit_from     => [ "linux-generic32", asm("x86_asm") ],
        CFLAGS           => add(picker(release => "-fomit-frame-pointer")),
        cflags           => add("-m32"),
        cxxflags         => add("-m32"),
        lib_cppflags     => add("-DL_ENDIAN"),
        bn_ops           => "BN_LLONG",
        perlasm_scheme   => "elf",
    },

**Comment by levitte** [comment]
Our configuration scripts do not try to control the compiler options you're giving it, it just simply passes them on.  So gcc doesn't support `-mlittle-endian` on that platform?  Then don't have `-mlittle-endian` among your configuration options.
