### ISSUE TITLE
openssl.exe smime -decrypt not working if called from powershell / c# / .bat

### ISSUE THREAD

**Issue by fmagalini** [openssl/openssl#9671]
Hi,

Works from command line
`openssl.exe smime -decrypt -in C:\SdI\N1N3\FO.04669240287.2019231.1930.901.zip.p7m.enc -inform der -binary -out C:\SdI\N1N3\FO.04669240287.2019231.1930.901.zip.p7m -recip C:\SdI\Certificates\MGLFNC82H02Z112Z.EDYAT001.CIFRA.P12.pem -passin pass:123456789`

The same command does not work from powershell or run from c# code
`.\openssl.exe "smime" -decrypt –in "C:\SdI\N1N3\FO.04669240287.2019231.1930.901.zip.p7m.enc" –inform "der" –binary -out "C:\SdI\N1N3\FO.04669240287.2019231.1930.901.zip.p7m" –recip "C:\SdI\Certificates\MGLFNC82H02Z112Z.EDYAT001.CIFRA.P12.pem" -passin "pass:123456789"`

Error:
```
.\openssl : No recipient certificate or key specified
At line:1 char:1
```

All other openssl commands works from both cmd / powershell; any idea?
Thank you
Francesco

EDIT: does not work even from .bat file, same exact command

**Comment by fmagalini** [comment]
Sorry guys,
it was an issue with the "-" char transformed by MS Word to "û" in the command
Please close
Thank you

**Comment by levitte** [comment]
Ouch!  Ok, closing
