### ISSUE TITLE
Information regarding the S/MIME decryption stream support

### ISSUE THREAD

**Issue by ujjal-linux** [openssl/openssl#9673]
Hello Team 
I am trying to decrypt S/MIME large file. It seems that the whole file is being loaded into the memory.
so just want to know if openssl suppor the stream option for decryption so that the whole file is not loaded into the memory before processing.  May be the block are loaded for decryption and hence will not need much of memory to load the file completely in memory.
Please let me know if this is supported or not.  I am facing some issue with memory and would like to know if any solution exist for this case.
Thanks in advance 
~Us.

**Comment by ujjal-linux** [comment]
Hi Is it possible to get some comment/input for this topics ?  Thanks in advance.

**Comment by richsalz** [comment]
Not even a day passed; practice more patience. :)

You don't say what version you are using. Look at using the "-stream" option to the command, this may work. You may have to update to a newer version of openssl.

**Comment by ujjal-linux** [comment]
Thank you for your response. I am using OpenSSL 1.1.1b. It looks like "-stream" is for the encryption but not for the decryption. i tested and looks like it copies the whole file. 
Please let me know your suggestion/views.

**Comment by richsalz** [comment]
I think you're going to have to write your own software; others might have more helpful info.
