### ISSUE TITLE
Openssl-1.1.1 compilation failing with Depricated message

### ISSUE THREAD

**Issue by vishal307** [openssl/openssl#9676]
Configuring openssl-1.1.1c for arm-linux-gnu...

pushd openssl-1.1.1c/ \
    && unset CROSS_COMPILE \
    && bash ./Configure arm-none-linux-gnueabi-gcc -DL_ENDIAN no-ssl3 no-ssl2 --prefix=./ --install_prefix=/home/work/../root_arm/ --openssldir=/ssl/ shared threads --with-zlib-include=/home/work/../root_arm/include --with-zlib-lib=/home/work/../root_arm/lib zlib-dynamic  \
    && popd
~/work/../openssl/openssl-1.1.1c ~/work/trunk/os/oss/openssl
**Deprecated target configuration for arm-none-linux-gnueabi-gcc, ignoring...**

Failure!  build file wasn't produced.
Please read INSTALL and associated NOTES files.  You may also have to look over
your available compiler tool chain or change your configuration.

Also tried with removing the flags "-DL_ENDIAN no-ssl3 no-ssl2" but still the same error

**Comment by levitte** [comment]
arm-none-linux-gnueabi-gcc is not a config target that we know. Do you have config target files of your own?

**Comment by mspncp** [comment]
Are you migrating from an older OpenSSL version to 1.1.1? It looks like your configuration is still 'old-style', i.e in the form of those long, colon-separated strings.  

Support for those has been removed a long time ago in commit bd5192b1013b68373c47bdca8d68229906171695, which is the reason why you get the [Deprecated target](https://github.com/openssl/openssl/commit/bd5192b1013b68373c47bdca8d68229906171695#diff-f1206f9fadc5ce41694f69129aecac26R2112)  error message.

If that's the case, you need to convert your configuration to the new configuration format. Look at [Configurations/10-main.conf](https://github.com/openssl/openssl/blob/master/Configurations/10-main.conf) for examples.

Very often, there is already a configuration which matches your needs or which is very close to it. If the latter is the case: the new configuration scheme supports inheritance, so you easily can define your own configuration which inherits from an existing one (search for 'inherit_from') and changes a few options.

**Comment by vishal307** [comment]
mspncp, You were right, changing the config data into new format resolved the Deprecated target issue.

Many thanks for your inputs !!
