### ISSUE TITLE
[Not openssl program] Mailing list "openssl-users" not working…

### ISSUE THREAD

**Issue by stas730** [openssl/openssl#968]
I have problem with two ASN.1 sequences, and I cannot test certificate.
I need to post information on mailing list "openssl-users". Message sended, but I doesn't see it in archives. I using a temporary email (I doesn't have a real for now).

**Comment by richsalz** [comment]
Please see https://mta.openssl.org and join the openssl-users mailing list.

**Comment by stas730** [comment]
Not working but I am subscribed. Temporary email hostings are blocked?

**Comment by levitte** [comment]
Please send a message to postmaster@openssl.org with the details, such as your email address and a few lines about the issue.
