### ISSUE TITLE
Openssl-1.1.1c: SSL_CTX_build_cert_chain build empty chain

### ISSUE THREAD

**Issue by raniervf** [openssl/openssl#9684]
Openssl-1.1.1c
build with: perl Configure VC-WIN32 enable-ssl-trace no-asm no-async no-dso no-engine --debug 

res = SSL_CTX_build_cert_chain(ctx, SSL_BUILD_CHAIN_FLAG_CHECK | SSL_BUILD_CHAIN_FLAG_IGNORE_ERROR);
res result = 2

but in: statem_lib.c
 ssl_add_cert_chain function fail in construct chain certs.

i = ssl_security_cert_chain(s, extra_certs, x, 0);
        if (i != 1) {
            SSLfatal(s, SSL_AD_INTERNAL_ERROR, SSL_F_SSL_ADD_CERT_CHAIN, i);
            return 0;
        }
        if (!ssl_add_cert_to_wpacket(s, pkt, x, 0)) {
            /* SSLfatal() already called */
            return 0;
        }
        for (i = 0; i < sk_X509_num(extra_certs); i++) {
            x = sk_X509_value(extra_certs, i);
            if (!ssl_add_cert_to_wpacket(s, pkt, x, i + 1)) {
                /* SSLfatal() already called */
                return 0;
            }

sk_X509_num(extra_certs) returns 0!

Certificate is p12 bag with 3 certificates.

**Comment by agnosticdev** [comment]
Based on the `ssl_add_cert_chain()` function, the `X509_STORE` may not be getting set in this flow:
```c
if (cpk->chain != NULL)
    extra_certs = cpk->chain;
else
    extra_certs = s->ctx->extra_certs;

if ((s->mode & SSL_MODE_NO_AUTO_CHAIN) || extra_certs)
    chain_store = NULL;
else if (s->cert->chain_store)
    chain_store = s->cert->chain_store;
else
    chain_store = s->ctx->cert_store;
```

To help debug further are you able to validate that your certificates are all visible in the bag?
```bash
 openssl pkcs12 -in file.p12 -info -noout
```
https://www.openssl.org/docs/man1.0.2/man1/pkcs12.html

Also, one more thing to look into would be validating what is set for `SSL *s` before it is passed into `ssl_add_cert_chain()` and `s->cert` and `s->ctc` is used.

**Comment by raniervf** [comment]
openssl pkcs12 -in file.p12 -info -noout
Enter Import Password:
MAC: sha1, Iteration 1024
MAC length: 20, salt length: 20
PKCS7 Data
Shrouded Keybag: pbeWithSHA1And3-KeyTripleDES-CBC, Iteration 1024
PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-CBC, Iteration 1024
Certificate bag
Certificate bag
Certificate bag
Certificate bag

Before, SSL_CTX_add1_chain_cert, is set:
SSL_CTX_set_options(ctx, SSL_OP_NO_SSLv2 | SSL_OP_NO_SSLv3 | SSL_OP_NO_COMPRESSION);
SSL_CTX_set_options(ctx, SSL_OP_CIPHER_SERVER_PREFERENCE);
SSL_CTX_set_options(ctx, SSL_OP_SINGLE_DH_USE);
SSL_CTX_set_options(ctx, SSL_OP_SINGLE_ECDH_USE);
SSL_CTX_set_session_cache_mode(ctx, SSL_SESS_CACHE_OFF);
SSL_CTX_set_mode(ctx, SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER);

Based on results: openssl pkcs12 -in file.p12 -info -noout
Openssl-1.1.1c is not compiled with enable-weak-ssl-ciphers.

Is KeyTripleDES-CBC and RC2, weak ciphers?

**Comment by raniervf** [comment]
openssl version -a
OpenSSL 1.1.1c  28 May 2019
built on: Sat Aug 24 13:14:17 2019 UTC
platform: VC-WIN32
options:  bn(64,32) rc4(int) des(long) idea(int) blowfish(ptr)
compiler: cl /Z7 /Fdossl_static.pdb /Gs0 /GF /Gy /MDd /W3 /wd4090 /nologo /Od /W
X -DL_ENDIAN -DOPENSSL_PIC
OPENSSLDIR: "C:\Arquivos de programas\Arquivos comuns\SSL"
ENGINESDIR: "C:\Arquivos de programas\OpenSSL\lib\engines-1_1"
Seeding source: os-specific

**Comment by raniervf** [comment]
"Also, one more thing to look into would be validating what is set for SSL *s before it is passed into ssl_add_cert_chain() and s->cert and s->ctc is used."

Sorry, my mistake, type error.
SSL_CTX_clear_chain_certs(ctx);
while((x = sk_X509_pop(ca))) {
     if (SSL_CTX_add1_chain_cert(ctx, x509) != 1) {
correct is :
     if (SSL_CTX_add1_chain_cert(ctx, x) != 1) {
Now:
res = SSL_CTX_build_cert_chain(ctx, SSL_BUILD_CHAIN_FLAG_CHECK | SSL_BUILD_CHAIN_FLAG_IGNORE_ERROR);
res result = 1 SUCCESS
and
statem_lib.c:
ssl_add_cert_chain function work correctly.
Very sorry.
Thanks to Matt Caswell, for point me where the error.

**Comment by raniervf** [comment]
I thank you, sorry my mistake.
Best regards,
Ranier Vilela
________________________________________
De: Matt Eaton <notifications@github.com>
Enviado: quarta-feira, 28 de agosto de 2019 12:01
Para: openssl/openssl
Cc: raniervf; Mention
Assunto: Re: [openssl/openssl] Openssl-1.1.1c: SSL_CTX_build_cert_chain build empty chain (#9684)

Thank you @raniervf<https://github.com/raniervf>, glad you were able to get this resolved.
