### ISSUE TITLE
Openssl-1.1.1c: handshake failure(40), no client chain sent

### ISSUE THREAD

**Issue by raniervf** [openssl/openssl#9685]
Openssl-1.1.1c:
````
Compiled: perl Configure VC-WIN32 enable-ssl-trace no-asm no-async no-dso no-engine --debug
````

Building client chain with:
````
      SSL_CTX_clear_chain_certs(ctx);
      while((x = sk_X509_pop(ca))) {
         if (SSL_CTX_add1_chain_cert(ctx, x509) != 1) {
            X509_free(x);
            break;
	 }
      }
      sk_X509_pop_free(ca, X509_free);
````

the  code in function ssl_add_cert_chain: (statem_lib.c)

````
        i = ssl_security_cert_chain(s, extra_certs, x, 0);
        if (i != 1) {
            SSLfatal(s, SSL_AD_INTERNAL_ERROR, SSL_F_SSL_ADD_CERT_CHAIN, i);
            return 0;
        }
        if (!ssl_add_cert_to_wpacket(s, pkt, x, 0)) {
            /* SSLfatal() already called */
            return 0;
        }
        for (i = 0; i < sk_X509_num(extra_certs); i++) {
            x = sk_X509_value(extra_certs, i);
            if (!ssl_add_cert_to_wpacket(s, pkt, x, i + 1)) {
                /* SSLfatal() already called */
                return 0;
            }
````
works, `sk_X509_num(extra_certs)` return 3.

but, in header:
````
Sent Record
Header:
  Version = TLS 1.2 (0x303)
  Content Type = Handshake (22)
  Length = 8208
    Certificate, Length=8159
      certificate_list, length=8156
        ASN.1Cert, length=2036
------details-----
...
-----END CERTIFICATE-----
------------------
        extensions, length = 7
extensions, extype = 62512, extlen = 33287
          0000 - f4 30 82 07 f0 30 82                           .0...0.
Message length parse error!
````
Is printed only one certificate, none chain, why?
`SSL_trace` is wrong?

Probably cause this error writing in log:

````
SSL_connect:SSLv3/TLS write finished
Received Record
Header:
  Version = TLS 1.2 (0x303)
  Content Type = Alert (21)
  Length = 48
    Level=fatal(2), description=handshake failure(40)

SSL alert read:fatal:handshake failure
SSL_connect:error in error
SSL_read failed::
WSAError: 0
SSL State: SSLERR
SSL Error: -1 1 error:00000001:lib(0):func(0):reason(1)
SSL Error: -1 336151568 error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
````

**Comment by raniervf** [comment]
Hi, thanks.
My mistake, type error:
SSL_CTX_clear_chain_certs(ctx);
while((x = sk_X509_pop(ca))) {
    if (SSL_CTX_add1_chain_cert(ctx, x) != 1) {

However handshake still fail.
"SSL_connect:SSLv3/TLS read server done
Sent Record
Header:
  Version = TLS 1.2 (0x303)
  Content Type = Handshake (22)
  Length = 7344
    Certificate, Length=7303
      certificate_list, length=7300
        ASN.1Cert, length=2036
------details-----"

SSL_trace still prints one certificate, despite "Certificate, Length=7303", apparently
has more CA certificates.

SSL alert read:fatal:handshake failure
SSL_connect:error in error
SSL_read failed::
WSAError: 0
SSL State: SSLERR
SSL Error: -1 1 error:00000001:lib(0):func(0):reason(1)
SSL Error: -1 336151568 error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure

**Comment by raniervf** [comment]
[SOLVED]
For anyone who has the same problem:
https://forums.openvpn.net/viewtopic.php?t=23979
cipher list: "DEFAULT:@SECLEVEL=0"

**Comment by kaduk** [comment]
Just to note here as well as the forum post: setting ```@SECLEVEL=0``` is allowing ciphersuites and other security mechanisms that provide no, weak, or questionable security properties, and as such it is not a general-purpose solution.  It may be appropriate in specific, tailored, cases with external constraints, but more often the best long-term approach is to work to improve the security of the algorithms used, such that it is not necessary to override the security level.
