### ISSUE TITLE
OSS-Fuzz: Branch on uninitialized memory

### ISSUE THREAD

**Issue by guidovranken** [openssl/openssl#9691]
https://oss-fuzz.com/testcase-detail/5645357840596992

OSS-Fuzz reports ```soutl``` is uninitialized: https://github.com/openssl/openssl/blob/d32d304836caaca475c21a82b94e494898cb60c5/crypto/evp/evp_enc.c#L753

OSS-Fuzz reports this commit range: https://github.com/openssl/openssl/compare/784883fc2c8af035401f2a1e02a79aef41a2a7fb...c85d5e025797f4e77c2166150bbf8745e9d00696

This is distinct from https://github.com/openssl/openssl/pull/8874 (lack of return value checking)

These are the parameters:

```
operation name: SymmetricDecrypt
ciphertext: {}
tag: nullopt
aad: nullopt
cipher iv: {0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0xff} (8 bytes)
cipher key: {0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20} (16 bytes)
cipher: ARIA_128_CCM
```

**Comment by slontis** [comment]
Will have a look..

**Comment by slontis** [comment]
Can you see if this addresses the issue?

**Comment by guidovranken** [comment]
Yes, doesn't crash anymore after applying your PR, thanks.
