### ISSUE TITLE
ECDSA Key Pair verification failure in 1.0.2p fips

### ISSUE THREAD

**Issue by ARao0123** [openssl/openssl#9696]
I'm trying to run ECDSA key pair verification for [K-163] curve. 
Here are my calls: 

```
key = EC_KEY_new_by_curve_name(NID_sect163k1); 
rv = EC_KEY_set_public_key_affine_coordinates(key, Qx, Qy); 
```

For the following input, the result should've been a "FAIL" (as I got on Linux) but I get a "PASS" when the same code and same input is run on Windows: 

> Qx = bb8af626a652027955e29ff39e187fc1ebe537aeb 
> Qy = 05fc9f797943a40dac5913a108211f1e038af9e3d 

Can anyone suggest why this behavior changes on Windows? 

Thanks!

**Comment by romen** [comment]
Can you give more details?

How was the windows binary built? Can you report also `openssl.exe version - a`?

**Comment by romen** [comment]
Could you reproduce this without the FIPS module in windows?

**Comment by romen** [comment]
Also, would you be able to provide a simple piece of code with a list of test that are showing the behavior?

**Comment by romen** [comment]
It would be just to try and reproduce the issue and trying to figure out where the weird behavior is originating from.
