### ISSUE TITLE
Timestamping verification fails with SHA-384 algorithm

### ISSUE THREAD

**Issue by h-rueda** [openssl/openssl#9701]
This command fails for timestamping requests made with SHA-384.

```
openssl ts -verify -in response.tsr -queryfile request.tsq -CAfile cert.pem
Verification: FAILED
140597792569232:error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01:rsa_pk1.c:103:
140597792569232:error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed:rsa_eay.c:773:
140597792569232:error:21071069:PKCS7 routines:PKCS7_signatureVerify:signature failure:pk7_doit.c:1139:
140597792569232:error:2F06A06D:time stamp routines:TS_RESP_verify_signature:signature failure:ts_rsp_verify.c:225:
```

It works fine with timestamping request made with SHA-1, SHA-256, SHA-512.
It seems there is a bug when using SHA-384

**Comment by slontis** [comment]
Can you please give a full example of the steps to reproduce..
Also what version of openssl are you using?

**Comment by jayaram-intel** [comment]
Hi @h-rueda ,

I want to work on this issue, Please share required steps to re-produce the issue ?
Please specify on which OpenSSL version or commit ID or tag you observed the above issue.

**Comment by jayaram-intel** [comment]
Hi @h-rueda,

I followed below steps to re-produce the above issue.

1.Downloaded the below certificate file
`$ wget http://freetsa.org/files/cacert.pem`

2.Created timestamp request data
`$ openssl ts -query -data data.txt -cert -sha384 -no_nonce -out data.txt.ts_req`

3.Send the timestamp request and store the response
`$ curl -s -S -H 'Content-Type: application/timestamp-query' --data-binary @data.txt.ts_req http://freetsa.org/tsr -o data.txt.ts_res`

4.Verify the data with the timestamp response
`$ openssl ts -verify -in data.txt.ts_res -data data.txt -CAfile cacert.pem`

> Using configuration from /usr/local/ssl/openssl.cnf
> Verification: OK

**I didn't seen any Verification failure issue, It works fine with time stamping request made with SHA-1, SHA-256, SHA-384 and SHA-512.**

Note:
Used Latest OpenSSL master branch code base

Please Let me know in case if I missed anything and if everything is fine then verify from your end with latest OpenSSL master code base.

Thanks
Jayaram Matta

**Comment by jayaram-intel** [comment]
Hi @h-rueda ,

Please follow above mentioned steps and cross verify from your end with latest OpenSSL master code base and close this issue.

Thanks
Jayaram Matta

**Comment by jayaram-intel** [comment]
Hi @h-rueda ,

Please follow above mentioned steps and cross verify from your end with latest OpenSSL master branch code base and close this issue.

Thanks
Jayaram Matta

**Comment by romen** [comment]
@mattcaswell or @levitte should I close this issue?

**Comment by mattcaswell** [comment]
Doesn't seem to be a bug from the investigation by @jayaram-intel above. No response from original reporter, so closing.
