### ISSUE TITLE
When the cmp client applies for a certificate from the CA, can the parameters of the certificate template be added?

### ISSUE THREAD

**Issue by gezhouyu** [openssl/openssl#9704]
Hello, sir.
When the cmp client applies for a certificate from the CA, can the parameters of the certificate template be added?

**Comment by levitte** [comment]
@DDvO, you have worked with this, can you take a moment?

**Comment by DDvO** [comment]
Yes, the CMP client offers various functions for influencing the certificate template to use when requesting certificates. See the list of functions under `/* certificate template: */` in 
https://github.com/openssl/openssl/blob/master/doc/man3/OSSL_CMP_CTX_new.pod

Yet @gezhouyu please note that the CMP contribution to OpenSSL is still under way and the actual CMP client logic is not yet included there. If you need it now (or anytime soon) you may follow the intermediate users guide at https://github.com/mpeylo/cmpossl/wiki/Quick-Start

**Comment by DDvO** [comment]
Closing this since the question has been answered.
