### ISSUE TITLE
feature request: new cipher list "CBC"

### ISSUE THREAD

**Issue by bjmgeek** [openssl/openssl#9706]
There have been a number of attacks recently targeting CBC modes (e.g. POODLE, Zombie POODLE, etc.) so I would like a shortcut ciphersuite list such as `!CBC`, which would exclude any CBC mode ciphers.

**Comment by t8m** [comment]
Although not intuitive you can actually do that already with:
openssl ciphers -v DEFAULT:-SHA1:-SHA256:-SHA384

**Comment by levitte** [comment]
@t8m, is that future proof?

**Comment by t8m** [comment]
Given the present and future is TLS-1.3 which uses completely different setting for ciphersuites and does not use CBC mode at all I would expect it to be future-proof enough.

**Comment by levitte** [comment]
This could be a good idea to add.  PR welcome!
