### ISSUE TITLE
Android build of latest OpenSSL_1_1_1-stable fails

### ISSUE THREAD

**Issue by juha-h** [openssl/openssl#9708]
OpenSSL build on Anrdoid ndk19 has worked fine at least up to commit 2403153c95b312e0a5a178c516335ee8dd17526c from Aug 17.  Latest version from Aug 27 produces shm related compilation warnings:
```
clang  -I. -Icrypto/include -Iinclude -fPIC -pthread  -target armv7a-linux-androideabi -gcc-toolchain /home/vagrant/android-ndk/r19c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 --sysroot=/home/vagrant/android-ndk/r19c/platforms/android-21/arch-arm -Wa,--noexecstack -Qunused-arguments -Wall -O3 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -D__ANDROID_API__=21 -isystem /home/vagrant/android-ndk/r19c/sysroot/usr/include/arm-linux-androideabi -isystem /home/vagrant/android-ndk/r19c/sysroot/usr/include -DNDEBUG -D__ANDROID_API__=21 -MMD -MF crypto/rand/rand_unix.d.tmp -MT crypto/rand/rand_unix.o -c -o crypto/rand/rand_unix.o crypto/rand/rand_unix.c
crypto/rand/rand_unix.c:370:5: warning: implicit declaration of function 'shmdt' is invalid in C99 [-Wimplicit-function-declaration]
    shmdt(shm_addr);
    ^
```
and linking fails like this:
```
Build baresip arm64-v8a
[1/2] Building C object CMakeFiles/baresip.dir/baresip.c.o
[2/2] Linking C shared library /home/vagrant/build/com.tutpro.baresip/app/build/intermediates/cmake/release/obj/arm64-v8a/libbaresip.so
FAILED: : && /home/vagrant/android-ndk/r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang  --target=aarch64-none-linux-android21 --gcc-toolchain=/home/vagrant/android-ndk/r19c/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/vagrant/android-ndk/r19c/toolchains/llvm/prebuilt/linux-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security -DHAVE_INTTYPES_H -O2 -DNDEBUG  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libbaresip.so -o /home/vagrant/build/com.tutpro.baresip/app/build/intermediates/cmake/release/obj/arm64-v8a/libbaresip.so CMakeFiles/baresip.dir/baresip.c.o  -landroid -lOpenSLES /home/vagrant/build/com.tutpro.baresip/app/src/main/cpp/../../../../distribution/baresip/lib/arm64-v8a/libbaresip.a /home/vagrant/build/com.tutpro.baresip/app/src/main/cpp/../../../../distribution/rem/lib/arm64-v8a/librem.a /home/vagrant/build/com.tutpro.baresip/app/src/main/cpp/../../../../distribution/re/lib/arm64-v8a/libre.a /home/vagrant/build/com.tutpro.baresip/app/src/main/cpp/../../../../distribution/openssl/lib/arm64-v8a/libssl.a /home/vagrant/build/com.tutpro.baresip/app/src/main/cpp/../../../../distribution/openssl/lib/arm64-v8a/libcrypto.a /home/vagrant/build/com.tutpro.baresip/app/src/main/cpp/../../../../distribution/opus/lib/arm64-v8a/libopus.a /home/vagrant/build/com.tutpro.baresip/app/src/main/cpp/../../../../distribution/g7221/lib/arm64-v8a/libg722_1.a /home/vagrant/build/com.tutpro.baresip/app/src/main/cpp/../../../../distribution/ilbc/lib/arm64-v8a/libilbc.a /home/vagrant/build/com.tutpro.baresip/app/src/main/cpp/../../../../distribution/webrtc/lib/arm64-v8a/libwebrtc.a /home/vagrant/build/com.tutpro.baresip/app/src/main/cpp/../../../../distribution/zrtp/lib/arm64-v8a/libzrtp.a /home/vagrant/build/com.tutpro.baresip/app/src/main/cpp/../../../../distribution/bn/lib/arm64-v8a/libbn.a -lz -llog -latomic -lm && :
/home/vagrant/build/com.tutpro.baresip/app/src/main/cpp/../../../../distribution/openssl/lib/arm64-v8a/libcrypto.a(rand_unix.o): In function `rand_pool_acquire_entropy':
rand_unix.c:(.text+0x394): undefined reference to `shmget'
rand_unix.c:(.text+0x3b4): undefined reference to `shmat'
rand_unix.c:(.text+0x770): undefined reference to `shmget'
/home/vagrant/build/com.tutpro.baresip/app/src/main/cpp/../../../../distribution/openssl/lib/arm64-v8a/libcrypto.a(rand_unix.o): In function `cleanup_shm':
rand_unix.c:(.text+0x89c): undefined reference to `shmdt'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mattcaswell** [comment]
@paulidale - looks like 3a57775 is the culprit

**Comment by bernd-edlinger** [comment]
As a work-around you could configure with --with-rand-seed=getrandom
since you linux kernel will likely support that syscall anyway.

**Comment by paulidale** [comment]
I do not consider this to be a bug.  It is more a configuration problem.  The workaround that @bernd-edlinger suggests should be good but it would be best to cook this into the configuration.

If you are using a kernel that has `getentropy(2)` but doesn't support the System V shared memory calls, the _DEVRANDOM_ source should be disabled.  The _DEVRANDOM_ source is universally worse than `getentropy(2)`.

A PR that addresses the required configuration changes required would be ideal.

**Comment by mattcaswell** [comment]
> I do not consider this to be a bug. It is more a configuration problem

Hmm...but it seems it *is* a breaking change in a stable release. This configuration worked before, and now it doesn't. You seem to be redefining what is acceptable to configure in 1.1.1.

**Comment by bernd-edlinger** [comment]
Is there any android version with a kernel older than 3.17 (first to support getrandom)?

**Comment by paulidale** [comment]
System V shared memory was supported from (at least) Linux kernels 2.0 -- that's why I used it.  I didn't realise that it was removed from some later kernels.

I still think that a configuration update is the most appropriate fix here.

**Comment by paulidale** [comment]
Fixing the build would put me in the position of trying things without being able to confirm that they work or not.

In other words, I can't build for Android.

**Comment by mattcaswell** [comment]
> I can't build for Android

Building for Android is pretty straight forward. Download the NDK. Set up some environment variables. Instructions in NOTES.ANDROID.

**Comment by bernd-edlinger** [comment]
fixing a compile error is something different than testing on a target device.

**Comment by kroeckx** [comment]
I have no idea if the Android kernel is compiled with support for
it or not, it's something that can be disabled. But it's missing
from libc on Android.

**Comment by bernd-edlinger** [comment]
If anything is 100% for sure affected by weak entropy in /dev/urandom
then it is a mobile device with arm processor and linux earlier than 3.17

**Comment by juha-h** [comment]
Pauli writes:

> Fixing the build would put me in the position of trying things without
> being able to confirm that they work or not. 
> 
> In other words, I can't build for Android.

I can and anyone can use the Makefile of this project:

https://github.com/juha-h/libbaresip-android

Download OpenSSL_1_1_1-stable to openssl directory and give command

make openssl

-- Juha

**Comment by juha-h** [comment]
Bernd Edlinger writes:

> fixing a compile error is something different than testing on a target
> device.

I can do the testing on Android device.

**Comment by juha-h** [comment]
Rich Salz writes:

> I agree the config update probably makes sense.  But more importantly,
> I agree with @mattcaswell 's comment -- you broke the build, you fix
> it. :)

I too would appreciate a fix.

I'm using in my project OpenSSL_1_1_1-stable branch, since I thought
that 'stable' means that only bug and security fixes are done in such a
branch, and that don't need test after every commit to the branch if my
app still builds and works OK.

**Comment by paulidale** [comment]
The PR that introduced this was a security fix.  Without good random seed material, everything you do can be compromised.

My current feeling is that falling back to using `read(2)` to get one byte from `/dev/random` is the way to go on Android (with a kernel version check).  Without the `shm*(2)` calls, I can't think of a reliable way to guarantee that seeding has occurred without root permissions -- there are attacks against the other mechanisms I know of.  Albeit, I don't know much about Android.

For more recent kernels, `getrandom(2)` should be available.

**Comment by juha-h** [comment]
Bernd Edlinger writes:

> As a work-around you could configure with --with-rand-seed=getrandom
> since you linux kernel will likely support that syscall anyway.

I can confirm that with that flag OpenSSL_1_1_1-stable compiles without
warnings and Android build succeeds.

**Comment by mspncp** [comment]
> I do not consider this to be a bug. It is more a configuration problem. The workaround that @bernd-edlinger suggests should be good but it would be best to cook this into the configuration.

I agree with @mattcaswell, it _is_ a breaking change. Explicitly having to select a seed source (from `getrandom devrandom egd none rdcpu librandom`) using the `--with-rand-seed=xxx[,yyy,zzz]` configure option can only be considered a workaround, as @bernd-edlinger wrote.

The `--with-rand-seed=os` option (which is the default option) is special, because it means: choose whatever of the known seed sources is most appropriate for the current operating system. This default is implemented by the library and should work out-of-the box on the targeted operating system.

> If you are using a kernel that has `getentropy(2)` but doesn't support the System V shared memory calls, the _DEVRANDOM_ source should be disabled. The _DEVRANDOM_ source is universally worse than `getentropy(2)`.

Ideally, if the `getrandom` entropy source is available then there is no need to add `devrandom` to the `os` entropy source at all. Unfortunately, the final decisision isn't made at configuration time, but rather at runtime, depending on whether the `getrandom` system call succeeds or not. (At least that's the way it is implemented today). A logical consequence would be to load the shared memory functions dynamically at runtime (using `dlopen/dlsym`) only when using them is absolutely necessary. This would be the optimal fix to the problem. (Alternatively, if it is certain that no Android version at all supports dlopen/dlsym, then of course the shared memory approach should be disabled at configuration time.)

_(My personal opinion is that the shared memory problem is self-made, because commit 3a5777501a97cc3fbf28 attempts to achieve something which is actually the job of the operating system: If you care for your security, upgrade also your kernel, not just OpenSSL. But sigh, other team members think differently about it.)_

> > I can't build for Android
> 
> Building for Android is pretty straight forward. Download the NDK. Set up some environment variables. Instructions in NOTES.ANDROID.

Even if @paulidale could set up a toolchain to build for a specific Android version, this would still not guarantee that the solution works for all currently supported Android versions. So help from experienced Android users (e.g. testing) will be needed and appreciated.

**Comment by bernd-edlinger** [comment]
Agreed in general.
I think in the moment the straight forward fix would be something like this:
```
diff --git a/e_os.h b/e_os.h
index fe4c091..858bc40 100644
--- a/e_os.h
+++ b/e_os.h
@@ -28,7 +28,7 @@
  * default, we will try to read at least one of these files
  */
 #  define DEVRANDOM "/dev/urandom", "/dev/random", "/dev/hwrng", "/dev/srandom"
-#  ifdef __linux
+#  if defined(__linux) && !defined(__ANDROID__)
 #   ifndef DEVRANDOM_WAIT
 #    define DEVRANDOM_WAIT   "/dev/random"
 #   endif
```

**Comment by paulidale** [comment]
I've gone with your suggestion, @bernd-edlinger, in #9735.
