### ISSUE TITLE
Libraries porting to Windows IoT Core (mincore)

### ISSUE THREAD

**Issue by ksandowi** [openssl/openssl#971]
Based on http://pjdecarlo.com/2015/01/porting-open-source-libraries-to-windows-for-iot-mincore.html I was able to port openssl libraries to Windows IoT Core OS. Unfortunately besides configure/makefile there are some changes required in source code to avoid linking with user interface methods like MessageBox, GetDesktopWindows, GetDC etc. If you could port openssl to this new OS it would be very helpful for IoT world.

**Comment by richsalz** [comment]
It will not happen in 1.1  If you can make a PR out of your changes, that will help get it into a future release and maybe will help others.

**Comment by kaduk** [comment]
This is now being worked on in #4965 (by a community member).
The main motivation seems to be that this will be needed to support Windows 10 IoT, and probably some as-yet-unknown future consumer version of Windows that removes support for legacy applications.  I am not entirely sure what level of demand there would be for using openssl on Windows 10 IoT before the 1.2.0 release date.  Even though Windows is a "secondary" platform, I will tentatively put this in the 1.1.1 milestone, though of course that can be revisited at a later time.

**Comment by mattcaswell** [comment]
I think this issue should be closed as it is being tracked in #4965.
