### ISSUE TITLE
how did i remove SET and Reserved PrintableString (openssl1.1.1b)？

### ISSUE THREAD

**Issue by ygm521** [openssl/openssl#9726]
**oopenssl1.0.2d:**
```
/* a sequence of these are used */
typedef struct x509_attributes_st {
    ASN1_OBJECT *object;
    int single;                 /* 0 for a set, 1 for a single item (which is
                                 * wrong) */
    union {
        char *ptr;
        /*
         * 0
         */ STACK_OF(ASN1_TYPE) *set;
        /*
         * 1
         */ ASN1_TYPE *single;
    } value;
} X509_ATTRIBUTE;
DECLARE_STACK_OF(X509_ATTRIBUTE)
DECLARE_ASN1_SET_OF(X509_ATTRIBUTE)
```

**openssl1.1.1b：**
```
/* a sequence of these are used */
struct x509_attributes_st {
    ASN1_OBJECT *object;
    STACK_OF(ASN1_TYPE) *set;
};

```

**Comment by ygm521** [comment]
![2](https://user-images.githubusercontent.com/7271089/63916584-4c2f7200-ca6b-11e9-85f9-99de01106c6c.png)

**Comment by ygm521** [comment]
openssl1.0.2d:
      make_REQ -- prompt_info -- add_attribute_object -- X509_REQ_add1_attr_by_NID -- X509_ATTRIBUTE_create_by_NID :
`int X509_ATTRIBUTE_set1_data(X509_ATTRIBUTE *attr, int attrtype,
                             const void *data, int len)
{
    ASN1_TYPE *ttmp;
    ASN1_STRING *stmp = NULL;
    int atype = 0;
    if (!attr)
        return 0;
    if (attrtype & MBSTRING_FLAG) {
        stmp = ASN1_STRING_set_by_NID(NULL, data, len, attrtype,
                                      OBJ_obj2nid(attr->object));
        if (!stmp) {
            X509err(X509_F_X509_ATTRIBUTE_SET1_DATA, ERR_R_ASN1_LIB);
            return 0;
        }
        atype = stmp->type;
    } else if (len != -1) {
        if (!(stmp = ASN1_STRING_type_new(attrtype)))
            goto err;
        if (!ASN1_STRING_set(stmp, data, len))
            goto err;
        atype = attrtype;
    }
    //if (!(attr->value.set = sk_ASN1_TYPE_new_null()))
    //    goto err;
    attr->single = 1;
    /*
     * This is a bit naughty because the attribute should really have at
     * least one value but some types use and zero length SET and require
     * this.
     */
    if (attrtype == 0)
        return 1;
    if (!(ttmp = ASN1_TYPE_new()))
        goto err;
    if ((len == -1) && !(attrtype & MBSTRING_FLAG)) {
        if (!ASN1_TYPE_set1(ttmp, attrtype, data))
            goto err;
    } else
        ASN1_TYPE_set(ttmp, atype, stmp);
    //if (!sk_ASN1_TYPE_push(attr->value.set, ttmp))
    //    goto err;
    attr->value.single = ttmp;
    return 1;
 err:
    X509err(X509_F_X509_ATTRIBUTE_SET1_DATA, ERR_R_MALLOC_FAILURE);
    return 0;
}`

**Comment by mattcaswell** [comment]
It's not clear to me what your question is?

**Comment by ygm521** [comment]
how did i remove SET and Reserved PringtableString ？ look picture。

**Comment by ygm521** [comment]
the right like ：
![1](https://user-images.githubusercontent.com/7271089/63935620-747d9780-ca90-11e9-8172-cc01ab5e6dfb.png)

**Comment by ygm521** [comment]
@mattcaswell clear?

**Comment by mattcaswell** [comment]
No...not really. I'm hoping someone else will step in who understands what you're asking.

**Comment by ygm521** [comment]
The image opened is the request file. The first picture shows that the SET contains a PrintableString. My goal is to get the second chapter of the image, which is to remove the SET and leave the PrintableString.

**Comment by ygm521** [comment]
@mattcaswell  clear?

**Comment by mattcaswell** [comment]
Please explain:

- How did you create the request file
- Why do you consider what you have created to be wrong (i.e. why is it incorrect to have the SET there?)

A sample request file demonstrating the issue would also be helpful.

**Comment by ygm521** [comment]
You can generate the request file according to your own way. Like which function I can use to remove the SET, keep the PrintableString

**Comment by ygm521** [comment]
openssl1.0.2d:

/* a sequence of these are used */
typedef struct x509_attributes_st {
    ASN1_OBJECT *object;
    int single;                 /* **0 for a set, 1 for a single item** (which is
                                 * wrong) */
    union {
        char *ptr;
        /*
         * 0
         */ STACK_OF(ASN1_TYPE) *set;
        /*
         * 1
         */ ASN1_TYPE ***single**;
    } value;
} X509_ATTRIBUTE;
DECLARE_STACK_OF(X509_ATTRIBUTE)
DECLARE_ASN1_SET_OF(X509_ATTRIBUTE)

**Comment by mattcaswell** [comment]
It is not possible to remove the SET in this version of OpenSSL. This capability was removed by e20b57270dec on the basis that such X509_ATTRIBUTEs are malformed and should never be created.

**Comment by ygm521** [comment]
China's cfca company requires the request file format like my picture above of  national secret.

**Comment by mattcaswell** [comment]
> China's cfca company requires the request file format like my picture above of national secret certificate.

Then I think that is a problem for that organisation to resolve. They should not be requiring you to use a non-standard format, and I don't think it is reasonable for OpenSSL to have to support it.

**Comment by ygm521** [comment]
@mattcaswell why closed it?

**Comment by mattcaswell** [comment]
For the reasons I noted above:

> Then I think that is a problem for that organisation to resolve. They should not be requiring you to use a non-standard format, and I don't think it is reasonable for OpenSSL to have to support it.
