### ISSUE TITLE
Failing to include openssl1.1.1c with openLDAP

### ISSUE THREAD

**Issue by vishal307** [openssl/openssl#9728]
I am trying to build openLDAP using openssl1.1.1c. 
It is failing to locate the SSL/TLS package.
I have given the openssl lib and include paths in LDFLAGS and CPPFLAGS respectively in the Makefile of LDAP. The Make file also has --with-tls=openssl \ mentioned as config option

snapshot of config option in the ldap Makefile
-----------
CONFIG_OPTS= \
--host=$(TARGET) \
--prefix=${LINUX_ROOT} \
--exec_prefix=${LINUX_ROOT} \
--disable-static \
--enable-shared \
--with-yielding_select=no \
--disable-slapd \
--enable-syslog \
--disable-bdb \
--disable-hdb \
--enable-debug \
--with-tls=openssl \
--target=$(TARGET) \
LDFLAGS="-L${LINUX_ROOT}/lib -L$(LINUX_ROOT)/ssl/lib" \
CPPFLAGS="-I${LINUX_ROOT}/include -I$(LINUX_ROOT)/ssl/include" \

------------

checking for SSL_library_init in -lssl... no
checking for ssl3_accept in -lssl... no
configure: error: Could not locate TLS/SSL package
Makefile:27: recipe for target 'configure_arm-none-linux-gnueabi-2.4.42' failed

Could someone please help with the issue

**Comment by mattcaswell** [comment]
Sounds like a problem you need to take to the openLDAP people.

**Comment by makr** [comment]
Just my 2cents: The current OpenLDAP version 2.4.48 should compile and run with OpenSSL 1.1.1c. I can confirm this for the OpenLDAP client libraries on various UNIX Systems at least.

**Comment by petrovr** [comment]
Administrator please close this - reporter uses outdated OpenLDAP version.
