### ISSUE TITLE
when i use d2i_PKCS12_fp to load pfx，simple exit

### ISSUE THREAD

**Issue by zqb1992** [openssl/openssl#9737]

**Comment by mattcaswell** [comment]
Please add more detail to what you are trying to do, the steps you have taken so far and what your problem is.

**Comment by zqb1992** [comment]
VS2013 debug X64 + openssl master, d2i_PKCS12_fp simple exit.
`FILE* fp = NULL;
	if ((fp = fopen(path, "rb"))==NULL)
	{
		fprintf(stderr, "Error opening file %s\n", path);
		return NULL;
	}
	PKCS12 *p12 = d2i_PKCS12_fp(fp,NULL);
	if (p12 == NULL) {
		fprintf(stderr, "Error reading PKCS#12 file\n");
		ERR_print_errors_fp(stderr);
	}`

**Comment by mspncp** [comment]
_(@zqb1992 I edited your post to replace the single backquotes by triple backquotes, which are necessary to display multiline code)_

**Comment by mspncp** [comment]
What is the output of `ERR_print_errors_fp(stderr);`?

**Comment by zqb1992** [comment]
The function exits directly, and I recompile Version 1.1.1 with VS2013, so there's no problem.
