### ISSUE TITLE
EVP_CIPHER_CTX_set_key_length always succeeds for AES-256-CBC

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#9746]
Previously the return value as usable to check if the new length is acceptable for the cipher.
But now EVP_CIPHER_CTX_set_key_length accepts 31 byte length,
and EVP_CipherInit_ex fails.
This does *(edit:)* **not** do the same checks ...
https://github.com/openssl/openssl/blob/2f9789f7e7e8f17da32e1cadbbc3c398f99f2d23/crypto/evp/evp_enc.c#L990-L994
... as this previous code:
https://github.com/openssl/openssl/blob/2f9789f7e7e8f17da32e1cadbbc3c398f99f2d23/crypto/evp/evp_enc.c#L996-L1004

**Comment by levitte** [comment]
We do need to get something in place that allows us to see if a param was used.  There are quite a few suggestions, but it remains undecided what to choose.  I've forgotten what open PRs and issues there are on the matter...

**Comment by bernd-edlinger** [comment]
Yes, I just noticed that this effectively breaks the MMA countermeasures here:
https://github.com/openssl/openssl/blob/2f9789f7e7e8f17da32e1cadbbc3c398f99f2d23/crypto/cms/cms_enc.c#L109-L120

**Comment by mouse07410** [comment]
Naive question: what is MMA, and how could knowing that requested *key* length is bad reveal anything useful to the attacker?

**Comment by mspncp** [comment]
I think MMA here is the abbreviation for Million Message Attack, a.k.a. Bleichenbacher attack. 

See e.g. https://tools.ietf.org/html/rfc3218

**Comment by mspncp** [comment]
> See e.g. https://tools.ietf.org/html/rfc3218

...which contains the original reference:

```
[MMA] Bleichenbacher, D., "Chosen Ciphertext Attacks against
      Protocols based on RSA Encryption Standard PKCS #1",
      Advances in Cryptology -- CRYPTO 98.
```

**Comment by bernd-edlinger** [comment]
Howerver the name is a bit misleading,
you need only 20.000 messages to decrypt a message
that is in PKCS1 type2 format,
you only need 1.000.000 messages to forge a signature.

**Comment by mouse07410** [comment]
Thank you for the reference - now I understand.

But it seems that the responsibility for not presenting an error code that's too detailed, belongs to the app, and not to the underlying library. Especially since the app itself most likely should know the real reason the requested operation failed.

I personally

**Comment by levitte** [comment]
Several efforts were made to fix this.  The latest is #10449, which was recently merged, which means this issue can be closed.
