### ISSUE TITLE
openssl-1.1.0-pre4 cross compilation failed

### ISSUE THREAD

**Issue by asthaaggarwal** [openssl/openssl#976]
Hi,

I am not able to do cross compilation of openssl-1.1.0-pre4 build, I am building for arm and all previous build are working fine.
I m following below steps:

export INSTALLDIR=build-output
export PATH=$INSTALLDIR/bin:$PATH
export TARGETMACH=arm-none-linux-gnueabi
export BUILDMACH=i686-pc-linux-gnu
export CROSS=arm-none-linux-gnueabi
export CC=${CROSS}-gcc
export LD=${CROSS}-ld
export AS=${CROSS}-as
export AR=${CROSS}-ar
export PATH=$PATH:/opt/freescale/usr/local/gcc-4.1.2-glibc-2.5-nptl-3/arm-none-linux-gnueabi/bin

./Configure -DOPENSSL_NO_HEARTBEATS --openssldir=/home/user/priti/workbench/openssl/src/openssl-1.1.0-pre4/build-output shared os/compiler:/opt/freescale/usr/local/gcc-4.1.2-glibc-2.5-nptl-3/arm-none-linux-gnueabi/bin/arm-none-linux-gnueabi-gcc

Configuring OpenSSL version 1.1.0-pre4 (0x0x10100004L)
no-crypto-mdebug [default] OPENSSL_NO_CRYPTO_MDEBUG (skip dir)
no-crypto-mdebug-backtrace [forced] OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE (skip dir)
no-ec_nistp_64_gcc_128 [default] OPENSSL_NO_EC_NISTP_64_GCC_128 (skip dir)
no-egd [default] OPENSSL_NO_EGD (skip dir)
no-heartbeats [default] OPENSSL_NO_HEARTBEATS (skip dir)
no-md2 [default] OPENSSL_NO_MD2 (skip dir)
no-rc5 [default] OPENSSL_NO_RC5 (skip dir)
no-sctp [default] OPENSSL_NO_SCTP (skip dir)
no-ssl-trace [default] OPENSSL_NO_SSL_TRACE (skip dir)
no-ssl3 [default] OPENSSL_NO_SSL3 (skip dir)
no-ssl3-method [default] OPENSSL_NO_SSL3_METHOD (skip dir)
no-unit-test [default] OPENSSL_NO_UNIT_TEST (skip dir)
no-weak-ssl-ciphers [default] OPENSSL_NO_WEAK_SSL_CIPHERS (skip dir)
no-zlib [default]
no-zlib-dynamic [default]
Configuring for os/compiler:/opt/freescale/usr/local/gcc-4.1.2-glibc-2.5-nptl-3/arm-none-linux-gnueabi/bin/arm-none-linux-gnueabi-gcc
*Warning! target os/compiler:/opt/freescale/usr/local/gcc-4.1.2-glibc-2.5-nptl-3/arm-none-linux-gnueabi/bin/arm-none-linux-gnueabi-gcc doesn't exist!
*

Please let me know whats wrong here.

**Comment by levitte** [comment]
```
CROSS_COMPILE=arm-none-linux-gnueabi ./Configure {target} --openssldir=/home/user/priti/workbench/openssl/src/openssl-1.1.0-pre4/build-output shared no-heartbeats
```

To figure out what you want `{target}` to be, just run this, and pick from the list of targets presented:

```
./Configure
```

The `os/compiler[:flags]` part of the usage needs to be changed, we have forgotten...

**Comment by levitte** [comment]
As to the `--openssldir` option, I'm not sure what you expect from it.  Would you mind elaborating?

**Comment by asthaaggarwal** [comment]
--openssldir is to give the destination directory path.

**Comment by asthaaggarwal** [comment]
How to change the os/compiler[:flags] usage?? Can I do it at my end?

**Comment by levitte** [comment]
> How to change the os/compiler[:flags] usage?? Can I do it at my end?

No. Sorry, I meant Configure's usage printout. It's misleading. 

As for --openssldir, I think --prefix will suit you better.

**Comment by asthaaggarwal** [comment]
Why I am not able to build it? All previous builds i was able to build.
I Changed openssldir to prefix.

**Comment by asthaaggarwal** [comment]
I am able to build openssl-1.0.2g with the same commands mentioned above but i m not able to build openssl-1.1.0-pre4
As you suggested i checked the os/compiler target by running ./Configure command and my compiler is not mentioned in both the builds but still its able to cross compiled for openssl-1.0.2g not for openssl-1.1.0-pre4

**Comment by levitte** [comment]
The way you configure and build has changed in 1.1, substantially in some cases.

**Comment by asthaaggarwal** [comment]
I added my compiler details in conf file like this:
    "arm-none-linux-gnueabi-gcc" => {
        cc               => "arm-none-linux-gnueabi-gcc",
        cflags           => picker(default => "-Wall -DOPENSSL_THREADS",
                                   debug   => "-O0 -g",
                                   release => "-O3"),
        thread_scheme    => "(unknown)",
        bn_ops           => "BN_LLONG",
        shared_extension => ".so",
    },

And while running Configure command passed this config file:

./Configure --prefix=/home/gokul/Desktop/openssl-1.1.0-pre5/build-output --config=/home/gokul/Desktop/openssl-1.1.0-pre5/Configurations/10-main.conf os/compiler:/opt/freescale/usr/local/gcc-4.1.2-glibc-2.5-nptl-3/arm-none-linux-gnueabi/bin/arm-none-linux-gnueabi-gcc

And in target list i am able to view my target "arm-none-linux-gnueabi-gcc"

But still i m getting same issue:

**Comment by levitte** [comment]
Hey, sorry, lost you there for a bit.

I would recommend this in your conf file:

```
    "my-gcc" => {
        cc               => "gcc",
        cflags           => picker(default => "-Wall -DOPENSSL_THREADS",
                                   debug   => "-O0 -g",
                                   release => "-O3"),
        thread_scheme    => "(unknown)",
        bn_ops           => "BN_LLONG",
        shared_extension => ".so",
    },
```

And then configure like this:

```
export CROSS_COMPILE=arm-none-linux-gnueabi-
./Configure --prefix=/home/gokul/Desktop/openssl-1.1.0-pre5/build-output my-gcc
```

**Comment by asthaaggarwal** [comment]
Thanks :) I am able to cross compile it. I was not passing the target name in Configure command because of that i was not able to configure it.

**Comment by vinaysingh1234** [comment]
Astha

I am facing same issue, can't compile openssl-1.1.0 for arm-none-linux-gnueabi, can you please share the configure command(with all parameters) you used to configure?
