### ISSUE TITLE
Consistency in error messages

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#9766]
Noticed as part of the reviewing of #9662:
```
# define PROV_R_INVALID_IVLEN                             116
# define PROV_R_INVALID_IV_LENGTH                         109
# define PROV_R_INVALID_KEYLEN                            117
# define PROV_R_INVALID_KEY_LEN                           124
```

Here we have _invalid ivlen_ and _invalid iv length_ as errors.  Likewise _invalid keylen_ and _invalid key len_.  These should be made consitent.  The suggested approach is __LENGTH_ throughout.

There will be more similar cases.

**Comment by nhorman** [comment]
these seems to have been corrected in 2741128e9deeb7f6fd73f10a1c657c05433a41cb

closing.
