### ISSUE TITLE
OpenSSL servers can send a non-empty status_request in a CertificateRequest

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#9767]
In TLSv1.3, if a server has been configured to respond to the status_request extension, and also configured with client-auth then the server will send a CertificateRequest message to the client with a non-empty status_request extension - which is a violation of RFC8446.

This can be reproduced by building with enable-ssl-trace and then running s_server like this:

````
openssl s_server -status_file test/recipes/ocsp-response.der -Verify 5
````
And running s_client like this:
````
openssl s_client -status -trace -cert cert.pem -key key.pem
````
This shows a status_request extension in the CertificateRequest as follows:

````
Received Record
Header:
  Version = TLS 1.2 (0x303)
  Content Type = ApplicationData (23)
  Length = 1591
  Inner Content Type = Handshake (22)
    CertificateRequest, Length=1570
      request_context (len=0): 
      extensions, length = 1567
        extension_type=status_request(5), length=1521
          0000 - 01 00 05 ed 30 82 05 e9-0a 01 00 a0 82 05 e2   ....0..........
          000f - 30 82 05 de 06 09 2b 06-01 05 05 07 30 01 01   0.....+.....0..
          001e - 04 82 05 cf 30 82 05 cb-30 82 01 1a a1 81 86   ....0...0......
          002d - 30 81 83 31 0b 30 09 06-03 55 04 06 13 02 47   0..1.0...U....G
...more lines omitted...
````
If the status_request extension is present in a CertificateRequest then it should be empty according to RFC8446. In fact we should not be sending the extension at all in this case since we don't support this feature.

Also see: https://github.com/golang/go/issues/34040

**Comment by tomato42** [comment]
>  In fact we should not be sending the extension at all in this case since we don't support this feature.

any idea what will happen if a client actually does include an OCSP response with its certificate?

**Comment by mattcaswell** [comment]
> any idea what will happen if a client actually does include an OCSP response with its certificate?

Not tried it, but I *think* we hit this code:

https://github.com/openssl/openssl/blob/0220fc9921f0aa3aea43e6b672b8f89b3eb0261a/ssl/statem/extensions_srvr.c#L336-L338

With the result that it is just ignored.
