### ISSUE TITLE
Utility library for providers to unify getting and using digests and ciphers.

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#9768]
As part of the reviewing of #9662, it was noticed that there is a fair bit of repeated code around getting digests and ciphers (especially when supporting legacy implementations that aren't provider friendly).

It would seem sensible for this lump of code to be in a single place, so changes can be made there rather than in 10 places (8 digests, 2 ciphers excluding any upcoming PKEY uses).

Currently, only the MAC implementations do the full thing.  Refer to the first of the PDKDF2 discussions under https://github.com/openssl/openssl/pull/9662#pullrequestreview-279286157

**Comment by levitte** [comment]
You're talking about grouping the legacy support code into its own corner, right, so as to avoid having it sprinkled throughout the main code?  I've a branch where I'm doing that kind of work, it's not quite ready to be submitted yet, but has been a main focus the last few days...

**Comment by paulidale** [comment]
Exactly.

For example, the HMAC provider code includes this lump:
```
    if ((p = OSSL_PARAM_locate_const(params, OSSL_MAC_PARAM_DIGEST)) != NULL) {
        if (p->data_type != OSSL_PARAM_UTF8_STRING)
            return 0;

        {
            const char *algoname = p->data;
            const char *propquery = NULL;

/* Inside the FIPS module, we don't support engines */
#if !defined(FIPS_MODE) && !defined(OPENSSL_NO_ENGINE)
            ENGINE_finish(macctx->tmpengine);
            macctx->tmpengine = NULL;

            if ((p = OSSL_PARAM_locate_const(params, OSSL_MAC_PARAM_ENGINE))
                != NULL) {
                if (p->data_type != OSSL_PARAM_UTF8_STRING)
                    return 0;

                macctx->tmpengine = ENGINE_by_id(p->data);
                if (macctx->tmpengine == NULL)
                    return 0;
            }
#endif
            if ((p = OSSL_PARAM_locate_const(params,
                                             OSSL_MAC_PARAM_PROPERTIES))
                != NULL) {
                if (p->data_type != OSSL_PARAM_UTF8_STRING)
                    return 0;

                propquery = p->data;
            }

            EVP_MD_free(macctx->alloc_md);

            macctx->tmpmd = macctx->alloc_md =
                EVP_MD_fetch(PROV_LIBRARY_CONTEXT_OF(macctx->provctx),
                             algoname, propquery);

#ifndef FIPS_MODE /* Inside the FIPS module, we don't support legacy digests */
            /* TODO(3.0) BEGIN legacy stuff, to be removed */
            if (macctx->tmpmd == NULL)
                macctx->tmpmd = EVP_get_digestbyname(algoname);
            /* TODO(3.0) END of legacy stuff */
#endif

            if (macctx->tmpmd == NULL)
                    return 0;
        }
    }
```

This gets repeated for everything that uses a digest and would make for a great common function.  Even when engine support is removed, it would still be worth keeping as a common function.

**Comment by paulidale** [comment]
See #9770 for an attempt to make the digest code common between HMAC and KMAC.

The cipher code will come later.  Then the KDF conversions (once accept and merged).

**Comment by levitte** [comment]
Ah, ok, that is different from what I was thinking. I like what you did!

**Comment by paulidale** [comment]
I figure that this can be closed with the PR being reviewed.
