### ISSUE TITLE
a small bug of s_server when not specify hostname

### ISSUE THREAD

**Issue by zk3326312** [openssl/openssl#9771]
openssl version: 1.1.1b
when I use openssl s_server like this:
openssl s_server -cert *.crt -key *.key [-accept 4433](content in '[]' can be omitted)
it return me an error:
140737354036992:error:02004061:system library:socket:Address family not supported by protocol:crypto/bio/b_sock2.c:49:
140737354036992:error:2008C076:BIO routines:BIO_socket:unable to create socket:crypto/bio/b_sock2.c:50:
but in most last version(openssl 1.1.0 and before), if i don't specify hostname, it will set "localhost:4433" as the default host without error

Actually the problem happened in this way(kern function:app/s_socket.c, do_server()):
I don't exactly set the host name, when code come to function **do_serve()->BIO_lookup_ex()**, it will return me a list of addrinfo, the ai_family of the **res** contain **AF_INET** and **AF_INET6**, when the code come to **line 247** in function **do_server()**, it will choose AF_INET6 as default ai_family, but actually my pc don't support IPV6, so it gives me an error.

In s_server.c, it set **socket_family = AF_UNSPEC**, when usr don't specify hostname, then function getaddrinfo(const char *node, const char *service, const struct addrinfo *hints,  struct addrinfo **res) in function **BIO_lookup_ex()** turn to be **getaddrinfo(NULL, port, hint, res)**, even if my pc don't open IPV6, it will contain IPV6 ai_family(AF_INET6) in **res**.

I don't know if this is an exact bug, from the code in function **do_server()**, i think author wants us to use IPV6 as much as possible, but it seems like there are some problems in this way. Maybe the author expect user must specify the host when use s_server? If for such consideration, i think giving some statement or constrict in s_server would be better.

**Comment by t8m** [comment]
Please try 1.1.1c, this one should be fixed there although the fix introduced a small regression which is fixed in 1.1.1 branch in git.

**Comment by mattcaswell** [comment]
@zk3326312 has the answer from @t8m resolved your problem? If not please let us know otherwise we will close this issue in due course.

**Comment by zk3326312** [comment]
it works, thanks for your answering,
