### ISSUE TITLE
error: invalid use of incomplete type 'SSL {aka struct ssl_st}

### ISSUE THREAD

**Issue by vishal307** [openssl/openssl#9772]
I am trying to compile my application using openssl1.1.1c version.

When I am trying to reference S3 variable inside SSL structure it gives and error
main.cpp:297:12: error: invalid use of incomplete type 'SSL {aka struct ssl_st}'
In file included from /home/../include/openssl/crypto.h:25:0,
                 from /home/v../include/openssl/comp.h:16,
                 from /home/../include/openssl/ssl.h:17,

I check the difference between the previous openssl1.0.2r code with openssl1.1.1C I could see that the SSL structure which is actually a typedef to ssl_st structure.

In Openssl1.0.2r, the ssl_st structure and number of other structures were present in the ssl.h include file with the Openssl1.1.1c this structure is moved to a ssl_locl.h which is present is ssl directory. This looks to be the reason it is not finding the "ssl_st" structure

Could anyone please help to get a workaround on this problem

**Comment by mattcaswell** [comment]
OpenSSL 1.1.x is not fully source compatible with OpenSSL 1.0.2. Lots of structures were made opaque which means you have to use accessor functions to obtain data rather than reaching into the structure directly. What were you trying to do that needed access to s3?

**Comment by vishal307** [comment]
I am trying to use the flags variable of s3 structure
s3->flags |= SSL_OP_NO_RENEGOTIATION;

**Comment by mattcaswell** [comment]
The equivalent is:

`SSL_set_options(s, SSL_OP_NO_RENEGOTIATION`

**Comment by vishal307** [comment]
Will try it. Thanks a lot for quick response.

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.

**Comment by goodpaperman** [comment]
what about ssl->version ?
