### ISSUE TITLE
Reverted check?

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#9773]
https://github.com/openssl/openssl/blob/master/crypto/evp/cmeth_lib.c#L40-L46

The NULL check seems to be reverted.
Also gcc 8.3.0 complains about this code, so it may be useful to add it to Travis.

**Comment by levitte** [comment]
You're right!  Do you want to submit a PR for it?

**Comment by beldmit** [comment]
Not me, but the compiler :)
Will do a bit later.
