### ISSUE TITLE
Problem with Oracle 12.2 precompiler

### ISSUE THREAD

**Issue by wolfiepop1974** [openssl/openssl#9778]
When i try to compile with proc precompiler i get a lot of messages of this tipe:

```
Syntax error at line 20, column 27, file /usr/include/openssl/comp.h:
Error at line 20, column 27 in file /usr/include/openssl/comp.h
    int (*init) (COMP_CTX *ctx);
..........................1
PCC-S-02201, Encountered the symbol "*" when expecting one of the following:

   , )

Syntax error at line 21, column 30, file /usr/include/openssl/comp.h:
Error at line 21, column 30 in file /usr/include/openssl/comp.h
    void (*finish) (COMP_CTX *ctx);
.............................1
PCC-S-02201, Encountered the symbol "*" when expecting one of the following:

   , )

Syntax error at line 22, column 31, file /usr/include/openssl/comp.h:
Error at line 22, column 31 in file /usr/include/openssl/comp.h
    int (*compress) (COMP_CTX *ctx,
..............................1
PCC-S-02201, Encountered the symbol "*" when expecting one of the following:

   , )

Syntax error at line 25, column 29, file /usr/include/openssl/comp.h:
Error at line 25, column 29 in file /usr/include/openssl/comp.h
    int (*expand) (COMP_CTX *ctx,
............................1
PCC-S-02201, Encountered the symbol "*" when expecting one of the following:

   , )

Syntax error at line 44, column 10, file /usr/include/openssl/comp.h:
Error at line 44, column 10 in file /usr/include/openssl/comp.h
COMP_CTX *COMP_CTX_new(COMP_METHOD *meth);
.........1
PCC-S-02201, Encountered the symbol "*" when expecting one of the following:

   ; , = ( [
The symbol ";" was substituted for "*" to continue.

Syntax error at line 45, column 29, file /usr/include/openssl/comp.h:
Error at line 45, column 29 in file /usr/include/openssl/comp.h
void COMP_CTX_free(COMP_CTX *ctx);
............................1
PCC-S-02201, Encountered the symbol "*" when expecting one of the following:

   , )


The same happens with another header files, like env.p, asn1.h, etc. More examples:

Error at line 654, column 36 in file /usr/include/openssl/evp.h
   654  void EVP_EncodeInit(EVP_ENCODE_CTX *ctx);
   654  ...................................1
   654  PCC-S-02201, Encountered the symbol "*" when expecting one of the follo
        wing:
        
           , )
        
Error at line 655, column 38 in file /usr/include/openssl/evp.h
   655  void EVP_EncodeUpdate(EVP_ENCODE_CTX *ctx, unsigned char *out, int *out
        l,
   655  .....................................1
   655  PCC-S-02201, Encountered the symbol "*" when expecting one of the follo
        wing:
        
           , )

Error at line 992, column 29 in file /usr/include/openssl/asn1.h
   992  int ASN1_i2d_fp(i2d_of_void *i2d, FILE *out, void *x);
   992  ............................1
   992  PCC-S-02201, Encountered the symbol "*" when expecting one of the follo
        wing:
        
           , )
        
Error at line 1011, column 42 in file /usr/include/openssl/asn1.h
  1011  void *ASN1_d2i_bio(void *(*xnew) (void), d2i_of_void *d2i, BIO *in, voi
        d **x);
  1011  .........................................1
  1011  PCC-S-02201, Encountered the symbol "d2i_of_void" when expecting one of
         the following:
        
           ... auto, char, const, double, enum, float, int, long,
           ulong_varchar, OCIBFileLocator OCIBlobLocator,
           OCIClobLocator, OCIDateTime, OCIExtProcContext, OCIInterval,
           OCIRowid, OCIDate, OCINumber, OCIRaw, OCIString, register,
           short, signed, sql_context, sql_cursor, static, struct,
           union, unsigned, utext, uvarchar, varchar, void, volatile,
           a typedef name, exec oracle, exec oracle begin, exec,
           exec sql, exec sql begin, exec sql type, exec sql var,
        The symbol "enum," was substituted for "d2i_of_void" to continue.
```

Is possible to integrate OpenSSL with Oracle Pro*C? i was searching on tne net about this topic but i couldn't find nothing at all....

I tried to analize this case, and i think that the problem is on the precompiler, because the typedef struct is not taken on count on the same header file, like it doesn't exist....

**Comment by levitte** [comment]
*Note: message re-edited to add better mardown markup for output text*

**Comment by levitte** [comment]
I assume that you're building an application of your own, is that it?  Can you show the `#include` lines from the C unit that fails to build?

**Comment by levitte** [comment]
It might be as simple as you needing to `#include <openssl/ossl_typ.h>` first...

**Comment by wolfiepop1974** [comment]
I'm using two includes in my .pc file:

#include <openssl/ssl.h>
#include <openssl/err.h>

If i compile using gcc everything goes fine, but using proc i have the problem...

On my component i'm adding TLS 1.2 security on the sockets already implemented... The syntax for using OpenSSL don't have problem, this happens on the precompiler phase....

**Comment by levitte** [comment]
I have no idea how that precompiler works, like what assumptions it works under...

**Comment by wolfiepop1974** [comment]
On the messages obtained, looks like the definition of the structure wasn't identified by the precompiler. But the strange point is that the definition happened a few lines before that the function prototype...

**Comment by levitte** [comment]
Oh wow, that's an old OpenSSL! That's older than I have answers for...
(the 1.0.1 series reached end-of-life a while ago already, so we have dropped support for it)

The best I can suggest is to start with upgrading to 1.0.2. It should be compatible with what you're using today. Eventually, you will have to upgrade to even newer, but 1.0.2 is good enough for now.

**Comment by wolfiepop1974** [comment]
I agree, thats an old version.... but the user has problems with the environment... we are trying to use 1.0.2r....

**Comment by levitte** [comment]
Do you have this same problem with 1.0.2r?

**Comment by wolfiepop1974** [comment]
Some similar....

Syntax error at line 22, column 31, file /usr/include/openssl/comp.h:
Error at line 22, column 31 in file /usr/include/openssl/comp.h
    int (*compress) (COMP_CTX *ctx,
..............................1
PCC-S-02201, Encountered the symbol "*" when expecting one of the following:

I continue searching on the Net, but now looking for environment on gcc and proc, and i found that if i collect the path used by the GCC i can solved the mayor part of them.... i'm on this...

**Comment by wolfiepop1974** [comment]
After change that path environment i got only two messages, one is the same on typedef struct and another one is about another include of gcc......

**Comment by wolfiepop1974** [comment]
I've added:
/usr/include/openssl,/usr/gcc/4.8/lib/gcc/sparc-sun-solaris2.11/4.8.2/include,/usr/include

to the path of libraries on proc y now i got:

Syntax error at line 239, column 24, file openssl/bio.h:
Error at line 239, column 24 in file openssl/bio.h
void BIO_set_flags(BIO *b, int flags);
.......................1
PCC-S-02201, Encountered the symbol "*" when expecting one of the following:

   , )

**Comment by levitte** [comment]
Why did you add `/usr/include/openssl`?  That's completely unnecessary, because the inclusion directives are expected to be like `#include <openssl/bio.h>`

**Comment by wolfiepop1974** [comment]
It looks like unnecessary, but it helps to reduce the number of errors....

Now the error looks like the others, one struct dont recognized, but defined a few lines before on the same header file

**Comment by levitte** [comment]
You're not showing what you're actually doing, so there's not much we can say...

**Comment by wolfiepop1974** [comment]
The error was posted, one step before you ask why i do that change....

The path in the configuration of the precompiler was the only change. I obtained that path collecting the info of the gcc compiler, and pasting that path on the precompiler.

That was the only change, and i got less errors, as i said before. And still in 1.0.1p, tomorrow we will update to 1.0.2p and repeat the testing

**Comment by levitte** [comment]
You talk as if I somehow knew anything about that precompiler. I know nothing about it, I do not know how you run it, on what you run it, or what to expect from it. I said so among my first comments. And yet, you continue to present me errors, and seem to think that it will somehow provide enough knowledge...

That being said, it looks to me like that precompiler doesn't deal well with types that, at least as far as it's able to read, are opaque (i.e it's a typedef of a struct where the struct itself isn't defined). Could that guess lead to something fruitful?

(is there a manual for this precompiler that you can give us a url to?)

**Comment by wolfiepop1974** [comment]
OK, i was posting the message in the hope that somebody could help me. Sorry if feel this like personal.

The precompiler "translates" a series of special commands that Oracle recognize into ansi C sentences for make posible his compilation into a exe file.

This is the URL for the documentation of this precompiler: https://docs.oracle.com/cd/E11882_01/appdev.112/e10825/toc.htm

I agree that this tool looks "incomplete" about the precoessing of all the capabilities of Ansi C, and i think tahtat it has limitations on the use of structures of ansi C (been typedef struct one of this structures).

This is not a problem of OpenSSL, the structures are defined and are utilized on the flow of the application, but is a fact that the precompiler has problems parsing the header files.

**Comment by wolfiepop1974** [comment]
THinking about the problem, we'll try an option: use the precompiler on the original source componente, and add the openssl changes on the ansi c obtained as result of the precompiler.

On this way we can eliminate the process of the openssl changes in the precompiler. There will hace more work to do, but the problem on the bad parsing doesnt exist anymore....

Thank you for your support.

Atentamente

Manuel Villalobos
________________________________
De: Richard Levitte <notifications@github.com>
Enviado: jueves, 5 de septiembre de 2019 06:49 p. m.
Para: openssl/openssl <openssl@noreply.github.com>
CC: wolfiepop1974 <wolfiepop@outlook.com>; Author <author@noreply.github.com>
Asunto: Re: [openssl/openssl] Problem with Oracle 12.2 precompiler (#9778)


You talk as if I somehow knew anything about that precompiler. I know nothing about it, I do not know how you run it, on what you run it, or what to expect from it. I said so among my first comments. And yet, you continue to present me errors, and seem to think that it will somehow provide enough knowledge...

That being said, it looks to me like that precompiler doesn't deal well with types that, at least as far as it's able to read, are opaque (i.e it's a typedef of a struct where the struct itself isn't defined). Could that guess lead to something fruitful?

(is there a manual for this precompiler that you can give us a url to?)

**Comment by michael-o** [comment]
If OpenSSL uses C99, you have a problem. Pro*C does not properly support C99 mode. The you can do -- and this is what we do -- wrap your code with defines and add it to the `proc` call. That could path will be disabled for the preprocessor, but then picked up by your compiler and its processer. At worst, file an issue in MOSC. At best, migrate to unixODBC and Oracle's ODBC driver.

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
