### ISSUE TITLE
Unable to convert private key from der to pem 

### ISSUE THREAD

**Issue by suchithravn** [openssl/openssl#9783]
I have a private key in DER format. When i tried to convert it to PEM format following error occurs.

Please have a look at this issue.

**openssl rsa -inform DER -outform PEM -in mykey.der -out mykey.pem**

**unable to load Private Key**
140546670184336:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:tasn_dec.c:1220:
140546670184336:error:0D08303A:asn1 encoding routines:ASN1_TEMPLATE_NOEXP_D2I:nested asn1 error:tasn_dec.c:649:
140546670184336:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:tasn_dec.c:1220:
140546670184336:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:tasn_dec.c:386:Type=RSA
140546670184336:error:04093004:rsa routines:OLD_RSA_PRIV_DECODE:RSA lib:rsa_ameth.c:121:
140546670184336:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:tasn_dec.c:1220:
140546670184336:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:tasn_dec.c:386:Type=PKCS8_PRIV_KEY_INFO

**Comment by levitte** [comment]
Use `openssl pkey`

https://www.openssl.org/docs/man1.1.1/man1/openssl-pkey.html

**Comment by suraj0208** [comment]
@levitte can you please explain why using that command will help?
I know we use openssl rsa for PKCS#1 keys and openssl pkcs8 for PKCS#8 keys.

@suchithravn did using openssl pkey solved your problem?

any reason this is marked as a bug?

**Comment by mspncp** [comment]
> @levitte can you please explain why using that command will help?
> I know we use openssl rsa for PKCS#1 keys and openssl pkcs8 for PKCS#8 keys.

I think it's because the `openssl pkey` command is smarter and more flexible. For example, it can be used for both RSA and ECDSA keys.


> any reason this is marked as a bug?

Because there are currently only two different GitHub issue templates, one for bug reports, the other one for feature requests. A template for general questions is missing. It's on my todo list but I did not get around to do it yet. Thanks for the reminder.

**Comment by mspncp** [comment]
> > any reason this is marked as a bug?
> 
> Because there are currently only two different GitHub issue templates, one for bug reports, the other one for feature requests. A template for general questions is missing. It's on my todo list but I did not get around to do it yet. Thanks for the reminder.

See pull request #10051.

**Comment by levitte** [comment]
`openssl pkcs8` can probably be used as well, I'm might simply not have thought of it.  `openssl rsa` is antiquated and only reads "traditional" RSA keys, and cannot handle PKCS#8

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
