### ISSUE TITLE
Broken link in 1.1.0 RSA_set0_key documentation.

### ISSUE THREAD

**Issue by cpereida** [openssl/openssl#9789]
While working on #9779 I found out that In the [RSA_set0_key](https://www.openssl.org/docs/man1.1.0/man3/RSA_set0_key.html) documentation for 1.1.0 there is a broken link to `rsa(3)` in the **SEE ALSO** section. 

The link does not exist in the master and 1.1.1 documentation.

**Comment by mattcaswell** [comment]
Thanks @cpereida. I note that the link is gone from the 1.1.1 docs, so this is not a problem there. 1.1.0 is in security fix only mode (and after Wednesday next week will be out of support altogether). Therefore this is not something we'll be fixing.
