### ISSUE TITLE
Compilation issue of discache on RHEL8 openssl 1.1.1b

### ISSUE THREAD

**Issue by shivbindas** [openssl/openssl#9790]
I am also facing one issue while compiling my discache on RHEL8 which comes with openssl 1.1.1b
while compiling it i am seeing below error :

```./configure --prefix=/home/sgarg/rpmbuild/SOURCES/distcache```

checking for SSL/TLS toolkit base... none
checking openssl/opensslv.h usability... yes
checking openssl/opensslv.h presence... yes
checking for openssl/opensslv.h... yes
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking for OpenSSL version... OK
checking for OpenSSL ENGINE support... yes
checking for SSLeay_version in -lcrypto... no
checking for SSL_CTX_new in -lssl... yes
configure: error: ... Error, SSL/TLS libraries were missing or unusable
configure: error: /bin/sh './configure' failed for ssl

Can you please help me here ?

```openssl version -a```
Output:
OpenSSL 1.1.1 FIPS 11 Sep 2018
built on: Fri Dec 14 14:00:55 2018 UTC
platform: linux-x86_64
options: bn(64,64) md2(char) rc4(16x,int) des(int) idea(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wa,--noexecstack -Wa,--generate-missing-build-notes=yes -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DZLIB -DNDEBUG -DPURIFY -DDEVRANDOM=""/dev/urandom"" -DSYSTEM_CIPHERS_FILE="/etc/crypto-policies/back-ends/openssl.config"
OPENSSLDIR: "/etc/pki/tls"
ENGINESDIR: "/usr/lib64/engines-1.1"
Seeding source: os-specific
engines: rdrand dynamic

**Comment by t8m** [comment]
Can you show us the config.log part from the 'checking for SSLeay_version in -lcrypto... no' check?

**Comment by shivbindas** [comment]
[config.log](https://github.com/openssl/openssl/files/3584331/config.log)
 
I have uploaded confog.log , kindly check the logs

**Comment by t8m** [comment]
Ah that log does not contain anything about ssl, that seems to be handled by a nested configure call, can you please find the right config.log from that nested call?

**Comment by shivbindas** [comment]
[config.log](https://github.com/openssl/openssl/files/3584446/config.log)
please find the ssl logs , sorry to miss that before

**Comment by t8m** [comment]
The configure check is wrong. There is no API/ABI compatibility between 1.0.2 and 1.1.x - the SSLeay_version is no longer function but a macro and so it cannot be checked with the simple library linkage configure check.
I suppose even if you fix the configure check other code would be broken as well.

**Comment by danfe** [comment]
@shivbindas, you might find [this commit](https://svnweb.freebsd.org/changeset/ports/541400) useful.
