### ISSUE TITLE
X509_NAME_add_entry_by_txt() has bytes in Chinese, parsed dn will garble

### ISSUE THREAD

**Issue by jiagushuai** [openssl/openssl#9816]
The current version in use is openssl-1.1.1a, a 64-bit environment for win10
+ When generating 509_NAME through X509_NAME_add_entry_by_txt, the English string generates p10 and the parsing is normal, but cn contains Chinese is normal and the parsing cn is garble

## the subject
+ `CN=中文,O=gzsd.com,OU=sdtech,ST=Beijing City,L=beijing,C=CN`

##  The dn information in English, excluding Chinese, is generated and analyzed
+ subject:`CN=Test,OU=sdtech,O=gzsd.com,L=beijing,ST=Beijing City,C=CN`
```
-----BEGIN CERTIFICATE REQUEST-----
MIIDNDCCAhwCAQMwaTENMAsGA1UEAwwEVGVzdDEPMA0GA1UECwwGc2R0ZWNoMREw
DwYDVQQKDAhnenNkLmNvbTEQMA4GA1UEBwwHYmVpamluZzEVMBMGA1UECAwMQmVp
amluZyBDaXR5MQswCQYDVQQGEwJDTjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBALycaKk9XXIBCFmL+r322z8Tk85hqp7Ia9MnoE076pp5BOs83H3xVa7/
/5XdilLBMqK8A34TSsIw0FBwVE8/GAskBLHv6wawPbAJgCQWHucIHe2Hes25ijte
Mc1zHvvO/aARTddUnTz+l96unGjfyt7TaRbMNKOtRxVtBsPYH3g+rJLEik/ZwYm4
XNlAgxczV8sddxCK6/xCHnOh+bI04yo+hsu4m3ebITH3bzp+xCnPZ/FJa+WwecGm
w/wTD16+sgkL3QmLsq+R/bPdjKZInISj9xBB4btZQdb6HbFVA4nIuTpMb1JKuqHY
JNjQEGj3Zrguqx3IjlebK/A/9q7jDPcCAwEAAaCBhTAaBglghkgBhvhCAQ0xDQwL
u2v4tbPGMq6afOkwGwYDVR0RMRQMEkROUzp3d3cuZ3pzZGtqLmNvbTAfBgNVHSUx
GAwWc2VydmVyQXV0aCwgY2xpZW50QXV0aDApBgNVHQ8xIgwgZGlnaXRhbFNpZ25h
dHVyZSwgbm9uUmVwdWRpYXRpb24wDQYJKoZIhvcNAQELBQADggEBAF+lD4CNG+c1
tDOnx3Th98n4CaUaLLqT4Jayaa5/TzsmomZqnujLw6li8F6LDoN9PRvM6tWZ0JsR
u1ih1VveS59lC/B3EyX2/nEY+jXQXQ58YiS/M4xug5bnK0bWVFaehv2adZkfSHHV
q2+lLjla4b47iPFHPR0vG5o46vxamVLnyhsTtROLX85xM6MtNRI2Vtf8a8iH5ppi
NJd1+mc/gdU855qWTZMp5ljcUT8MClaKx+eLXvT7H14MHumq1hAvPg1eLGLgFIsM
o40f+dhGTp7FRrvLUoZdv/h+byE3j4HB61+VyN/ScJrRe7mBPko6biGDHUXVrCpF
MgEPLT7w/v4=
-----END CERTIFICATE REQUEST-----
```
##  Chinese dn information, generate normal but parse dn garbled code
+ subject:`CN=ÖÐÎÄ,OU=sdtech,O=gzsd.com,L=beijing,ST=Beijing City,C=CN`
```
-----BEGIN CERTIFICATE REQUEST-----
MIIDPTCCAiUCAQMwbTERMA8GA1UEAwwIw5bDkMOOw4QxDzANBgNVBAsMBnNkdGVj
aDERMA8GA1UECgwIZ3pzZC5jb20xEDAOBgNVBAcMB2JlaWppbmcxFTATBgNVBAgM
DEJlaWppbmcgQ2l0eTELMAkGA1UEBhMCQ04wggEiMA0GCSqGSIb3DQEBAQUAA4IB
DwAwggEKAoIBAQDhbn+L19dUr0XTKC9UQweJ2bskV/EjThgKGb+7n6nMbGRxh0M5
9lBUN/t7J69DE9vs2CeJ4CIGc0H2N1nt4od6KEzPz454xeCegTu0bfqkktd485S6
rUGAUSnXIYmfIQLu59lWa7Fz5fIOZktV8CN6HuLhh5ras+9Q5b29wnfVYqBefTU6
cnvx/VIPq/F6T+dvCIt1aQsY0FVrvS9Mi8BbD/TZRlsDLGvS8bBai/SIeCS5b5DE
LJseYItgamJzxM5u1vtiyitZx8hQRQfwJ3jl60ApkRR2PJYNLAGRbidtZugNpoNO
jCD89H3GbwLOttEWmOhXLkZG343CjSjHcRb/AgMBAAGggYowGwYDVR0RMRQMEkRO
Uzp3d3cuZ3pzZGtqLmNvbTAfBgNVHSUxGAwWc2VydmVyQXV0aCwgY2xpZW50QXV0
aDAfBglghkgBhvhCAQ0xEgwQgPWuDQ0xmnW40xV+c2RrajApBgNVHQ8xIgwgZGln
aXRhbFNpZ25hdHVyZSwgbm9uUmVwdWRpYXRpb24wDQYJKoZIhvcNAQELBQADggEB
AGKq86Vpfo/DSHSikujwZpdK1skKUkMn93t3D+XzJHerTY3hBz5Q6KhjzOIdfudE
sPQM+XRcg2Jxb6o2w/n4z4rOxjFsVc/9MejTQj1ZZ00Ue37fgV85swWQUWI2PH2/
th+fcVg+s03iIS/LGNfdcfTHYckfzTiMyR+nQ1CTUhx1kH21oFhoj8Jww0ewRYu0
AsOpBaeN9/hjuHwSpNcPD90L8C0p4nRcD8bHDRjki/BzOKFzNedE35HIZW2CfsiO
GyfdgyiFshkND1tRpNvgC4/PlfbAEsnP0QSk8pVcmf3N3o/EV8qgNoMNm7UP1SiI
Io9763PUDUrAKCzpmZkdC78=
-----END CERTIFICATE REQUEST-----
```

**Comment by jiagushuai** [comment]
How can I set it so that it will not be garble when the dn contains Chinese?

**Comment by petrovr** [comment]
Linggo wrote:
> How can I set it so that it will not be garble when the dn contains Chinese?
*MBSTRING_UTF8 type with UTF-8 encoded data ?
*

**Comment by jiagushuai** [comment]
+ I gave it a try. The certificate request generated after the replacement failed
![image](https://user-images.githubusercontent.com/29997741/64662391-de2b7780-d47a-11e9-9122-ad7554cc509a.png)
+ parse error
![image](https://user-images.githubusercontent.com/29997741/64662430-087d3500-d47b-11e9-8c9e-032f5fc8b88f.png)
+ pkcs10
```
-----BEGIN CERTIFICATE REQUEST-----
MIIDIjCCAgoCAQMwWjEPMA0GA1UECwwGc2R0ZWNoMREwDwYDVQQKDAhnenNkLmNv
bTEQMA4GA1UEBwwHYmVpamluZzEVMBMGA1UECAwMQmVpamluZyBDaXR5MQswCQYD
VQQGEwJDTjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALaMje6BaTQl
24IiNN+2gyeuSmRwDEgEUuX+RsUhdAkw3r3RDtxfGOnbuF/3CQgSZcKDXlsusXeW
/BOxd2g1LpUqkdrYGekahIwXkmc4kuqXPuFKVDiZnlrj2lTGbI51XX0g0xHJZmck
IvkuWBiytky1K1SWLqvUTn1cdg/Y+6DNdNosI1/pfw4R4S6LKafBryEQ8FuFYNCT
VqVXBwq0nMnMf5jfYKsYndCtZ5mUoOgrssNoVBIw1YM+4B9VRu6N+3MUhWOKRYr3
oba5l+0wJyZGoV0d5gGlVmk/PFvudD/sBkY4hBNE6QbSnQ62VTUzFQJZPq4z5cpL
YdfuS7f7FVMCAwEAAaCBgjAXBglghkgBhvhCAQ0xCgwIExonqW5RPl8wGwYDVR0R
MRQMEkROUzp3d3cuZ3pzZGtqLmNvbTAfBgNVHSUxGAwWc2VydmVyQXV0aCwgY2xp
ZW50QXV0aDApBgNVHQ8xIgwgZGlnaXRhbFNpZ25hdHVyZSwgbm9uUmVwdWRpYXRp
b24wDQYJKoZIhvcNAQELBQADggEBACkzkfFgRuUjRumg134M1rwOpk+qyPEG5KIC
yaSo9AduDhQLsI/rBcQhPAckuNfXBMdSmwluVZVtATNj6+qYRJQesOJUSpf6KmlS
A7M95nSUw3No22vxEY0B3z0IuNltHDHJKe+cOlaJxoTU/f9OzPNL4UDUGfyb2vIf
UmJfXdmukTbAdOvRHhojaLZBc277yyRmWo4MdHlzYb4IsTOiB/PYT7QEAMmCA/D0
RGreARc9tEtEchy/dcJwulDIuVRzW/W0jeSpEgWnlnkyQB8W8rWjvUNB5VluFpoj
s8lDw+izl7uDBea434GaCO4wpt2IkYR4Z0gP+9ZWI6VqQoWqaRo=
-----END CERTIFICATE REQUEST-----
```

**Comment by jiagushuai** [comment]
> Hello, Linggo wrote:
> + I gave it a try. The certificate request generated after the replacement failed
> [snip] No idea why is failing. Please check again content of pbCN - ensure valid UTF-8 string. I did simple experiment with pkix-ssh regressio test: diff --git a/tests/CA/3-cre_certs.sh b/tests/CA/3-cre_certs.sh index fa72ae8..8d3a3af 100644 --- a/tests/CA/3-cre_certs.sh +++ b/tests/CA/3-cre_certs.sh @@ -142,7 +142,7 @@ $SSH_DN_O ${SSH_DN_OU}-2 ${SSH_DN_OU}-1 ${SSH_DN_OU}-3 -$SSH_BASE_DN_CN(${type}${subtype}) +$SSH_BASE_DN_CN(${type}${subtype}-中文) $SSH_DN_EM . EOF -- 2.14.5 One of X.509 regression test uses distinguished name (string) in authorized keys file. Name is assembled using X509_NAME_add_entry_by_NID ( https://gitlab.com/secsh/pkixssh/blob/master/ssh-x509.c#L350 ). Test pass with "Chinese" in canonical name. Remark: there is no difference in "object" creation between X509_NAME_add_entry_by_NID and X509_NAME_add_entry_by_txt With other words X509_NAME_add_entry_by_{NID|txt} works fine. Regards, Roumen Petrov

## Thank you very much. I found that it was ok to convert GBK into utf8
