### ISSUE TITLE
HTTPD compilation failing with openssl 1.1.1b version

### ISSUE THREAD

**Issue by shivbindas** [openssl/openssl#9824]
OPENSSL version:
OpenSSL 1.1.1 FIPS  11 Sep 2018

Compilation Error:
command : QA_RPATHS=0x0002 rpmbuild -ba httpd.spec

Failure logs:
checking CommonCrypto/CommonKeyDerivation.h usability... no
checking CommonCrypto/CommonKeyDerivation.h presence... no
checking for CommonCrypto/CommonKeyDerivation.h... no
checking for CCKeyDerivationPBKDF in -lSystem... no
checking for ldap support...
checking for ldap_init in -lldap50... no
checking for ldap_init in -lldapssl41... no
checking for ldap_init in -lldapssl40... no
checking for ldap_init in -lldapssl30... no
checking for ldap_init in -lldapssl20... no
checking for ldap_init in -lldapsdk... no
checking for ldap_init in -lldapsdk... no
checking for ldap_init in -lldap... no
checking for ldap_init in -lldap... no
checking for ldap_init in -lldap... no
checking for ldap_init in -lldap... no
configure: error: could not find an LDAP library
configure failed for srclib/apr-util
error: Bad exit status from /var/tmp/rpm-tmp.EHLnn6 (%build)

**Comment by shivbindas** [comment]
[config.log](https://github.com/openssl/openssl/files/3589760/config.log)
Please find the apr-util config.log where compilation is failing

**Comment by t8m** [comment]
This fails on LDAP support, not on OpenSSL.
P.S. When building httpd against OpenSSL-1.1.1 please ensure that you are trying to build a httpd version that supports OpenSSL-1.1.1
