### ISSUE TITLE
rijndael-256 equivalent

### ISSUE THREAD

**Issue by morganmatt61** [openssl/openssl#9855]
A rijndael-256 equivalent would be great as I cannot find it anywhere else except the deprecated MCRYPT.
Thank you

**Comment by richsalz** [comment]
Why not use AES, the next evolution of Rijndael?

**Comment by levitte** [comment]
If I am not mistaken, Rijndael *is* AES, that's just the name it had before it won the competition...

**Comment by richsalz** [comment]
You're right, I am mistaken.  AES is Rijndael with some fixed block sizes.  I suggest this be closed.

**Comment by morganmatt61** [comment]
Since AES is Rijndael with fixed block sizes, it excludes Rijndael cyphers that are not of the fixed block sizes, many systems may already have stored data encrypted in Rijndael cyphers that are not within the fixed block sizes of AES. Some of us can't move off these specific Rijndael cyphers and no other major libraries support it. Please re-open. Thank you

**Comment by levitte** [comment]
You are asking for Rijndael-256 specifically, though.  Doesn't AES-256 correspond to that?

**Comment by morganmatt61** [comment]
for Rijndael-256, the 256 represents the block size, for AES-256, the 256 represents the key size. For AES the block size is fixed to 128 for all implementations.

**Comment by richsalz** [comment]
The OpenSSL policy is that only standards-body-approved crypto is provided; see the bottom of https://www.openssl.org/blog/blog/2018/01/18/f2f-london/

**Comment by levitte** [comment]
> The OpenSSL policy is that only standards-body-approved crypto is provided...

... going forward.  We do have some non-standard ciphers for historical reasons, they won't disappear immediately.

**Comment by levitte** [comment]
> for Rijndael-256, the 256 represents the block size, for AES-256, the 256 represents the key size.

Oh, right.  Sorry for the confusion

**Comment by richsalz** [comment]
Yes, but the project isn't going to *add* non-standard ciphers, right?  And many of then (whirlpool, blowfish, etc) are disabled by default at least.

**Comment by levitte** [comment]
> Yes, but the project isn't going to add non-standard ciphers, right? 

Yes, that's what I meant with "going forward"

**Comment by InfoHunter** [comment]
> Yes, but the project isn't going to add non-standard ciphers, right?

But 'drafts' seem to be a different story - for instance something being standardized sometimes could also be included before the approved version comes out.

**Comment by levitte** [comment]
Yes, true, but Rijndael is hardly going to be one of those...

**Comment by InfoHunter** [comment]
Sure

**Comment by lucasperin** [comment]
Since the issue was not closed after the discussion, I would like to add a bit of context some years later. 
https://csrc.nist.gov/news/2024/nist-proposes-to-standardize-wider-variant-of-aes

I think this issue should be upvoted so that there is support for Rijndael-256 ASAP, as NIST plans to standardize it soon.
