### ISSUE TITLE
openssl_get_fork_id has invalid syntax if !defined(OPENSSL_SYS_UNIX)

### ISSUE THREAD

**Issue by reaperhulk** [openssl/openssl#9858]
https://github.com/openssl/openssl/blob/5c184ff280ee042e3b7e07701b61adbcbe2958d7/crypto/threads_none.c#L145-L147

Presumably this is a typo, although since this made it through to release maybe this entire configuration isn't necessary?

**Comment by mspncp** [comment]
Ups!

**Comment by mspncp** [comment]
Fix is in #9860.

**Comment by reaperhulk** [comment]
Fixed so closing :)

**Comment by mspncp** [comment]
_Strange... this should have happened automatically through the `Fixes #9858` note in the commit message._

Never mind. Thanks again for your report. I will ping you when I have a pull request for my fork-protection improvements.
