### ISSUE TITLE
Feature: add `-list` option to `openssl enc` and `openssl dgst`

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#9893]
### Feature Request

Please add an option `-list` to both the `openssl enc` and `openssl dgst` command.

This is a **good first issue**, so the following gives an outline of what needs to be done.

_This issue was inspired by issue #9880._

### Introduction

Both the `openssl enc` and the `openssl dgst` command allow to use a supported algorithm in one of the following two ways: Either use the algorithm name as an option argument

```
openssl dgst -whirlpool some-file.txt
```

or using the algorithm name as command name itself:

```
openssl whirlpool some-file.txt
```

What cipher resp. digest is allowable, depends on whether the function `EVP_get_cipherbyname()`

https://github.com/openssl/openssl/blob/32bfa2e66ef81d2bc7e1ae1896efca01d03cdc10/apps/enc.c#L130

resp. `EVP_get_digestbyname()`

https://github.com/openssl/openssl/blob/32bfa2e66ef81d2bc7e1ae1896efca01d03cdc10/apps/dgst.c#L97

finds a matching entry.

#### openssl enc

The `openssl enc` command already has an option to list all supported ciphers, it is called `-ciphers`, not `-list`:

```
~/src/openssl-1.1.1$ openssl enc -ciphers
Supported ciphers:
-aes-128-cbc               -aes-128-cfb               -aes-128-cfb1             
-aes-128-cfb8              -aes-128-ctr               -aes-128-ecb              
-aes-128-ofb               -aes-192-cbc               -aes-192-cfb
...
```

In the case of the `openssl enc` command, the option to list all ciphers is implemented here:

https://github.com/openssl/openssl/blob/32bfa2e66ef81d2bc7e1ae1896efca01d03cdc10/apps/enc.c#L149-L155

For consistency, both commands should support the `-list` option, but the previous name needs to be kept for compatibility reasons.

#### openssl dgst

For `openssl dgst`, the option can be implemented analogously. Here is an outline of what's to be done:

- Copy the relevant code from `apps/enc.c` to `apps/dgst.c` replacing `OBJ_NAME_TYPE_CIPHER_METH` with `OBJ_NAME_TYPE_MD_METH`.
- Copy `show_ciphers()` to `show_digests()` and adjust it accordingly.
- Add a `-list` option for enc and dgst, but keep the `-ciphers` option.
- Update the documentation

**Comment by mspncp** [comment]
Strictly speaking it is a new feature, but OTOH it can be considered a bug that the list command was implemented only for `enc` but not for `dgst`. So I would advocate a backport to 1.1.1.

**Comment by mspncp** [comment]
Note: Actually the correct name of the callback would be `show_cipher()`, not `show_ciphers()`, because it prints only a single ciphername.

https://github.com/openssl/openssl/blob/32bfa2e66ef81d2bc7e1ae1896efca01d03cdc10/apps/enc.c#L624

**Comment by levitte** [comment]
Have you tried `openssl list`?

**Comment by mspncp** [comment]
Did not know that one yet. 

Does this mean we have three (partially incomplete) ways to list ciphers resp. digests? (`openssl help`,  `openssl {enc,dgst} -list`, and `openssl list -{cipher,digest}-commands`)?

Wouldn't it make more sense for example, to mention `openssl list` in `openssl help`, instead of duplicating functionality?

**Comment by levitte** [comment]
> Wouldn't it make more sense for example, to mention `openssl list` in `openssl help`, instead of duplicating functionality?

For 3.0, yes it would.

**Comment by agnosticdev** [comment]
I have opened a pull request with the implementation steps provided.  Please let me know your thoughts.
