### ISSUE TITLE
Linker errors when trying to build with MD2 and RC5 enabled--also tests get stuck on 70-test_comp.t

### ISSUE THREAD

**Issue by DragonOsman** [openssl/openssl#9896]
I'm using Windows 10 Home Single Language, Version 1903 Build 18362.356 on a laptop with a 64-bit 2 core processor with 4 available threads.  

The configuration command I ran first was: 
```
perl Configure VC-WIN64A --with-zlib-lib=C:/zlib/lib/zlibstatic --with-zlib-include=C:/zlib/include enable-md2 enable-rc5 --release`
```
and the output messages that I got, including linker errors, I put in [this Gist](https://gist.github.com/DragonOsman/e81ff5590561d999dce5b2f7ddb9d3bd).

Output of `perl configdata.pm --dump` from that configuration is in [this Gist](https://gist.github.com/DragonOsman/627aa2d00d7e5e354b57e94f7ff38d9f).

Right now, I already cleaned the build after the build using the above configuration failed and then I configured OpenSSL with a command similar to the one I quoted here except without the `enable-md2` and `enable-rc5` arguments included.  

This command:
```
perl Configure VC-WIN64A --with-zlib-lib=C:/zlib/lib/zlibstatic --with-zlib-include=C:/zlib/include --release
```

While testing the build with that configuration, I notice it's been stuck on 70-test_comp.t for more than 12 hours.

When I first tried to configure OpenSSL, I got an error about Win32::Console.  I tried to get and build that but got a few warnings and one error message from the Linker. But when I look, I see that Win32::Console is already there.  Could the problems I'm having now be because of some corruption in the Win32::Console module?  

Another question related to the configuration: if I want to Zlib, should I also add `enable-zlib` to my configuration command?  

Here's the [gist]() for the output from running `perl configdata.pm --dump` for the current configuration that I'm trying to test at the moment.

Any help is appreciated.  Thanks in advance.

**Comment by DragonOsman** [comment]
When adding `enable-zlib` to the configuration command and then running tests, the ENC test had this result:
```
test\recipes\20-test_enc.t ...................... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/172 subtests
```
And once again it got stuck on test_comp.t.

**Comment by mspncp** [comment]
> When adding `enable-zlib` to the configuration command and then running tests, the ENC test had this result:
> 
> ```
> test\recipes\20-test_enc.t ...................... Dubious, test returned 1 (wstat 256, 0x100)
> Failed 1/172 subtests
> ```

This is a known bug and has been fixed on the OpenSSL_1_1_1-stable branch in commit 86ed78676c660b553696cc10c682962522dfeb6c.

**Comment by DragonOsman** [comment]
Okay thanks, I'll get that one then.  I downloaded the latest stable release source code from the OpenSSL website.  

What about the other stuff?  The test_comp.t test being stuck and those linker errors when enabling MD2 and RC5.  

I edited my previous comment and added the `perl configdata.pm --dump` command output for the configuration where I enabled Zlib but didn't enable MD2 or RC5.

**Comment by DragonOsman** [comment]
I found out how to specify static or shared/dynamic builds.  I want a static build since the app I want to use it with has all static libs and I don't know if a dynamic one being thrown in would cause conflict or whatnot.  If it'll be fine then I'll go with a dynamic build.  

This is the configuration command I'm currently using:
```
perl Configure enable-zlib zlib-dynamic enable-external-tests --with-zlib-include=C:/zlib/include --with-zlib-lib=C:/zlib/lib/zlib.lib --with-zlib-lib=C:/zlib/bin/zlib.dll threads CXXFLAGS="/std:c++17;/permissive-;/W4" VC-WIN64A --release
```
I do want to know how to enable GOST and WPacket tests, by the way.  And I cloned the repository with this command this time:
```
git clone -b OpenSSL_1_1_1-stable https://github.com/openssl/openssl.git
```
Still need to see if it gave me that version of the library.  

Anyway, I'll try building it and running the tests again now.  I'll get back to you guys if something goes wrong with the tests.

**Comment by DragonOsman** [comment]
Report: alright, some tests were skipped but the rest all passed.  I want to know how to get some of them to not be skipped.  Like I said before, two of them are the GOST and WPacket ones.  And the other two are: the KRB5 test and the BoringSSL test.  For the latter, it says that the BoringSSL runner can't be found.  How can I get that?  And for the former is says, "Krb5 not available".  

I'm going to back to building static libs but I still want to know how to get those 4 test to not be skipped.  Thanks in advance.

**Comment by mattcaswell** [comment]
> Report: alright, some tests were skipped but the rest all passed. I want to know how to get some of them to not be skipped. Like I said before, two of them are the GOST and WPacket ones. And the other two are: the KRB5 test and the BoringSSL test. For the latter, it says that the BoringSSL runner can't be found. How can I get that? And for the former is says, "Krb5 not available".

It is perfectly normal for some tests to be skipped. This is almost always the case - I'm not sure if its actually possible to have a build configuration where no tests are skipped at all. The krb5 and boringssl tests are really tests for developers to use to make sure we didn't break anything during development. They run the test suites from external third party software. You don't need to run them. The GOST test requires use of the GOST engine. If you're not planning on using GOST ciphersuites you don't need it.

**Comment by DragonOsman** [comment]
What kind of ciphersuite is it and how do I get the engine for it?  And what about WPacket?  I can see that some tests being skipped is inevitable since a good chunk are only for dynamic builds, some are for Linux or VMS, and two are for MD2 and RC5 respectively which are apparently obsolete algorithms and not recommended.

**Comment by richsalz** [comment]
I suggest that you just go with the defaults that OpenSSL provides, until you have more understanding and just treat "skipped" as "test passed."

**Comment by DragonOsman** [comment]
I went ahead and installed it with the current setup, but I see I have no engines in the C:/Program Files/OpenSSL/lib/engines-1_1 directory.  How can I get engines?

**Comment by mattcaswell** [comment]
> How can I get engines?

This is the wrong question to ask. A better question might be:

What engines do I need?

And the answer in most cases is "none". You only need an engine in they provide some additional functionality that you need. For example if you need to use GOST ciphers then you need the GOST engine. But most users don't need the GOST ciphers.

There's a list of third-party engines here:
https://wiki.openssl.org/index.php/Binaries

**Comment by DragonOsman** [comment]
Alright, never mind then.  I'll close the issue now.
