### ISSUE TITLE
OPENSSL_FUNC goes wrong with GNU C and -pedantic

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#9911]
The recent c659882c9892788085fcdd4e8c47f98c01edf9ad removed the use of  `PEDANTIC` in `include/openssl/macros.h`.
This causes issues when using configuration option `-std=gnu90` and compiling with GCC:
```
include/openssl/macros.h:145:26: error: ISO C does not support '__FUNCTION__' predefined identifier [-Werror=pedantic]

```

To fix this, I would have suggested replacing
```
#  elif defined(_MSC_VER) || (defined(__GNUC__) && __GNUC__ >= 2)
#   define OPENSSL_FUNC __FUNCTION__
```
by
```
#  elif defined(_MSC_VER)
#   define OPENSSL_FUNC __FUNCTION__
#  elif defined(__GNUC__) && __GNUC__ >= 2
#   if defined PEDANTIC
#    define OPENSSL_FUNC "(unknown function due to -pedantic)"
#   else
#    define OPENSSL_FUNC __FUNCTION__
#   endif

```
but apparently `PEDANTIC` should not be used in this header file.

BTW, when I modify `macros.h`, `make` does not re-build anything, so it looks like the dependencies on this file are not properly reflected in the `Makefile`.

**Comment by levitte** [comment]
I had a look at https://sourceforge.net/p/predef/wiki/Standards/, and it looks like a check to see if `__STDC_VERSION__` exists might be the proper solution.

**Comment by DDvO** [comment]
I've just tried
```
#  elif defined(_MSC_VER)
#   define OPENSSL_FUNC __FUNCTION__
#  elif defined(__GNUC__) && __GNUC__ >= 2
#   if defined(__STDC_VERSION__)
#    define OPENSSL_FUNC "(unknown function due to -pedantic)"
#   else
#    define OPENSSL_FUNC __FUNCTION__
#   endif
```
which I think is what you suspect as a remedy, but this gives both false positives and false negatives regarding `-pedantic`.

Better try yourself with `gcc` and `-std=gnu90`, with and without `-DPEDANTIC -pedantic`.

**Comment by levitte** [comment]
In any case, *forget `PEDANTIC`*

**Comment by levitte** [comment]
BTW, what you wrote is incorrect.  C89 and C90 defined `__STDC__`, while `__STDC_VERSION__` came with C94...

**Comment by DDvO** [comment]
No matter when `__STDC__` and `__STDC_VERSION__` came,
GCC treats both `__FUNCTION__` and `__func__` as forbidden for c90 and gnu90 when `-pedantic` is used,
so the declaration of `OPENSSL_FUNC` somehow must deal with this problem.

When not using `defined(PEDANTIC)', how else should one find out in `macros.h` whether `-pendantic` is in effect?

**Comment by DDvO** [comment]
BTW, which C standard is OpenSSL code required to build with?
I did not find an official statement on this in the documentation.

**Comment by levitte** [comment]
When you tell gcc `-std=c90`, `-std=gnu90` or `-ansi`, it doesn't define `__STDC_VERSION__`. So the solution isn't to try to detect `-pedantic`, but to properly detect the language standard that's used. Have a look at #9913

**Comment by DDvO** [comment]
Ok, let's switch to #9913 to discuss only at one place.

**Comment by DDvO** [comment]
I've removed "; dependency issue with macros.h" from the title of this issue since I cannot reproduce that with the latest master.
