### ISSUE TITLE
dsa signature failure with external keys / master 2019-09-16

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#9915]
Issue is from e_nss (engine) regression tests - with current(2019-09-16) master "sign-dsa-dss1.test" fail.
Output file sign-dsa-sha1.out after (4) shows:
```
=== sign ===
engine "e_nss" set.
Error Signing Data
00:A7:5E:3F:7B:7F:00:00:error:80000085:E_NSS::Missing private key:/work/src/MyProjects/e_nss/anon-access/origin-local/engines/e_nss_dsa.c:42:
=== verify ===
Error reading signature file cfg-nss-dsa-sha1.sign
```

Commit history:
(4) Add support for verify/verify_recover functions to EVP_SIGNATURE:
commit 390acbebfa90500c79c5014e6659eacda861550c
(3) Implement DSA in the default provider:
commit 4889dadcb8511176c30888c748f1981adc38451d
(2) Add the ability to perform signatures in a provider
commit dfcb5d29b525f5d2b6bd80602dca5efe5fca77bb
(1) DH_check_pub_key_ex was accidentally calling DH_check, so results were undefined.
commit 2b95e8efcf8b99892106070d9ac745a0a369f503

(1) is lest know **good** version , (4) is **broken** version. With (2) or (3) as usually in "group" commits build fail.

**Comment by petrovr** [comment]
The test cases are simple. In particular:
```shell
$OPENSSL dgst $DIGEST -sign "$nickname" -keyform ENGINE -engine $engine_name -passin $nsspass $data > $signature
```

(1) Engine source code - https://gitlab.com/e_nss.

(2) Bootstrap:
After checkout autoreconf -ifv will create configure scrip and etc. Command requires all autotools installed - libtool, aclocal, automake, autoheader and autoconf. See manual autoreconf(1) how to set aclocal automake if you system provides script with version suffix.

(3) Configuration:
CPPFLAGS and LDFLAGS (with runpath) could be used to point to openssl build tree.
Headers nspr and nss  may require additional options - CPPFLAGS="$CPPFLAGS -I/usr/include/nspr4 -I/usr/include/nss3" (location depend from distribution).
Option --enable-tests is required together with installed nss binaries like pk12util.

(4) Tests
Command is standard - make check.
For non-standard openssl installations environment variable should OPENSSL point to executable used in tests. For instance to use build tree:
```shell
OPENSSL=$opensslbuilddir/util/opensslwrap.sh \
make check
```

**Comment by petrovr** [comment]
In above list with commits (3) Implement DSA in the default provider exist code that serializes EV_KEY to EVP_KEYMGMT.
The issue with this code is lack of serialization of "extra data" associated to key.

So it seems to me CAPI engine (part of OpenSSL code) is also broken - information set 
here https://github.com/openssl/openssl/blob/7cfa1717b812a126ce6f8e4cc32139164c89d789/engines/e_capi.c#L749 is lost. As result external key cannot be located.

**Comment by levitte** [comment]
Ah, thanks for that last bit.
The engine bits are a bit up in the air for the moment, and support for hidden private keys hasn't been completed yet. I'm actually looking at that bit right now, so thanks for the reminder that I need to keep an eye on engine.

**Comment by petrovr** [comment]
It is funny to see 6 months later some progress ....

**Comment by petrovr** [comment]
Theoretically correction from #11193 should do the trick but is not correct from functional point of view!
Note that default method is not the same as crypto-library method!

**Comment by petrovr** [comment]
Situation In master branch is quite interesting:
- DSA sign as reported fail;
- RSA sing fail as well - this is expected. RSA verify fail - not expected;
- EC pass - also not expected.
