### ISSUE TITLE
DTLS heartbeat does not respond in time when application data load is heavy

### ISSUE THREAD

**Issue by zjbbuaa** [openssl/openssl#9918]

**Comment by zjbbuaa** [comment]
our enviroment is that when DTLS client send heavy(maybe not heavy 3kpps) payoad to DTLS server,but DTLS server cannot reply heartbeat in time ,Is there any method to solve this?

**Comment by richsalz** [comment]
It does not seem like a bug, under heavy load (on sender or receiver) or a busy network, UDP packets can get dropped.
