### ISSUE TITLE
Unable parse TSA token

### ISSUE THREAD

**Issue by metsma** [openssl/openssl#993]
openssl 1.0.2g

Seems like openssl does not like HEX:"A1 82 02 45".
bouncy castle is able parse this TimeStampToken

openssl ts -reply -in TSA.ts -token_in -text
`
MIAGCSqGSIb3DQEHAqCAMIIMLAIBAzELMAkGBSsOAwIaBQAwggEXBgsqhkiG9w0BCRABBKCCAQYE
ggECMIH/AgEBBgorBgEEAYRZCgMBMCEwCQYFKw4DAhoFAAQU9ykkdUODoQAjIZe/H2JZtVrboYEC
BlZXpO8H/BgTMjAxNjA0MTExMzMyMjYuNzE3WjAEgAIB9AIGAVQFhe5noIGfpIGcMIGZMQswCQYD
VQQGEwJMVjENMAsGA1UEBxMEUmlnYTEOMAwGA1UEChMFTFZSVEMxDDAKBgNVBAsTA0lTRDEVMBMG
A1UECxMMZVBhcmFrc3RzLmx2MSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjoyMjhDLUM0OEQtMkM2
QzEeMBwGA1UEAxMVZVBhcmFrc3RzIExaSTEgKFRTQTEpoIIIgzCCBjYwggUeoAMCAQICChR4V08A
AQAAACkwDQYJKoZIhvcNAQEFBQAwUDELMAkGA1UEBhMCTFYxKDAmBgNVBAsTH1NlcnRpZmlrYWNp
amFzIHBha2FscG9qdW11IGRhbGExFzAVBgNVBAMTDkUtTUUgUFNJIChQQ0EpMB4XDTE1MDcxMDEz
MDc0OFoXDTIxMDcxMDEzMTc0OFowgZkxCzAJBgNVBAYTAkxWMQ0wCwYDVQQHEwRSaWdhMQ4wDAYD
VQQKEwVMVlJUQzEMMAoGA1UECxMDSVNEMRUwEwYDVQQLEwxlUGFyYWtzdHMubHYxJjAkBgNVBAsT
HVRoYWxlcyBUU1MgRVNOOjIyOEMtQzQ4RC0yQzZDMR4wHAYDVQQDExVlUGFyYWtzdHMgTFpJMSAo
VFNBMSkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCmHoRtojOn1gcAUZGS8nEkWRFv
pbCNsOcAvpGuD5EHTrE4psTcq4d6B0mlwsHtNhi7PBGch15L+ePv5tAJ0JAqtRnIJ5KIAipMsTg6
O1NiiF4UHepMOMx+ehYzqZp00qglfUldR66e0B52Z+5LjA8aljZzc7fgkhQR+EPvoRjpucqr4xXA
oHicyx2AJx1Q0JK+9nceluDlKamAOjzI1/V2BS6/ZUXCSq+xaPjAknrpFyy5+dpTfbPX9wjQ5697
bSrXzHAmAiH9sF/sGUSAtEougE7MV3k/wAxCnSOa4OdgmpepINzFYYmLDAzFnoxbqGMBIULXTQjU
3/Y4xPnQAE8dAgMBAAGjggLGMIICwjAdBgNVHQ4EFgQUQX59X3l/fvMYqgECK6ivvuuQzWcwHwYD
VR0jBBgwFoAUTS+GCx4VzZSjH4tPLkwLn7lzp9YwgeMGA1UdHwSB2zCB2DCB1aCB0qCBz4YvaHR0
cDovL3d3dy5lbWUubHYvY2RwL0UtTUUlMjBQU0klMjAoUENBKSgxKS5jcmyGgZtsZGFwOi8vZW1l
Lmx2L2NuPUUtTUUlMjBQU0klMjAoUENBKSgxKSxPVT1TZXJ0aWZpa2FjaWphcyUyMHBha2FscG9q
dW11JTIwZGFsYSxPPUUtTUUsQz1sdj9jZXJ0aWZpY2F0ZXJldm9jYXRpb25saXN0P2Jhc2U/b2Jq
ZWN0Y2xhc3M9Y2VydGlmaWNhdGlvbmF1dGhvcml0eTCCARwGCCsGAQUFBwEBBIIBDjCCAQowOwYI
KwYBBQUHMAKGL2h0dHA6Ly93d3cuZW1lLmx2L2FpYS9FLU1FJTIwUFNJJTIwKFBDQSkoMSkuY3J0
MCwGCCsGAQUFBzABhiBodHRwOi8vb2NzcC5lbWUubHYvcmVzcG9uZGVyLmVtZTCBnAYIKwYBBQUH
MAKGgY9sZGFwOi8vZW1lLmx2L0NOPUUtTUUlMjBQU0klMjAoUENBKSgxKSxPVT1zZXJ0aWZpa2Fj
aWphcyUyMHBha2FscG9qdW11JTIwZGFsYSxPPUUtTUUsQz1sdj9jYWNlcnRpZmljYXRlP2Jhc2U/
b2JqZWN0Y2xhc3M9Y2VydGlmaWNhdGlvbmF1dGhvcml0eTAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB
/wQEAwIGwDAWBgNVHSUBAf8EDDAKBggrBgEFBQcDCDBEBgNVHSAEPTA7MDkGCysGAQQBgfo9AQEB
MCowKAYIKwYBBQUHAgEWHGh0dHA6Ly93d3cuZW1lLmx2L3JlcG9zaXRvcnkwDQYJKoZIhvcNAQEF
BQADggEBAEFJ6+KSX7wpWG05xpQeJ2mu9b6IT8r6A934qPc0PdpJ1Fa5Vocy8qmrEaIsGXcsrSnd
Mw0F21ld2l4/HI5rOrjhnyQqwUg6IHCX9n6yL3Ziq7aieO83WW2k4UngIK5EGHYyfGd7YH6zCDbV
yYec3tlJb/L9jAvUEs0rMUzI+OxZmFrJg+MjagGpQeVHk8A1ex9Iektnq+s8P7FxdqqQytQYpX7x
ov5OPpqfI7ZKIzk7cPBg0G0c/y5vdU0inwcpPI+Jl0Vdzo2EqMFj5KeWN7JkJIeJ5OqkNq/o1vFS
tY2Iia4cvzwk3uQyzod1b3KvYx+DRcOU53qQH5eaWyyUKjqhggJFMIIBrgIBATCByaGBn6SBnDCB
mTELMAkGA1UEBhMCTFYxDTALBgNVBAcTBFJpZ2ExDjAMBgNVBAoTBUxWUlRDMQwwCgYDVQQLEwNJ
U0QxFTATBgNVBAsTDGVQYXJha3N0cy5sdjEmMCQGA1UECxMdVGhhbGVzIFRTUyBFU046MjI4Qy1D
NDhELTJDNkMxHjAcBgNVBAMTFWVQYXJha3N0cyBMWkkxIChUU0ExKaIlCgEBMAkGBSsOAwIaBQAD
FQAqyOChkVh+2ry2vOwbXmenRB9d56AqMCikJjAkMSIwIAYDVQQDExlMb2NhbEF1ZGl0LjIyOEMt
QzQ4RC0yQzZDMA0GCSqGSIb3DQEBBQUAAgUA2rYYIzAiGA8yMDE2MDQxMTEyMzMzOVoYDzIwMTYw
NDEyMTIzMzM5WjB3MD0GCisGAQQBhFkKBAExLzAtMAoCBQDathgjAgEAMAoCAQACAgLUAgH/MAcC
AQACAhIJMAoCBQDat2mjAgEAMDYGCisGAQQBhFkKBAIxKDAmMAwGCisGAQQBhFkKAwKgCjAIAgEA
AgMHoSChCjAIAgEAAgMBhqAwDQYJKoZIhvcNAQEFBQADgYEAkIzfCxH5KSzbw1De3fRN6mYFVf4p
1v6P2OZiMihc/dl/eS/9zI2C0+KA2tjWYbkSz8yHJIph6vFd51q0RgU/odSdDbFmhIwbhWz4/PvM
sV03DRs1+366GZLCR7mrlsox5CwpHeUU0y13ShKSESND++492nswT5hytsvWQOt503kxggJ2MIIC
cgIBATBeMFAxCzAJBgNVBAYTAkxWMSgwJgYDVQQLEx9TZXJ0aWZpa2FjaWphcyBwYWthbHBvanVt
dSBkYWxhMRcwFQYDVQQDEw5FLU1FIFBTSSAoUENBKQIKFHhXTwABAAAAKTAJBgUrDgMCGgUAoIHu
MBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAjBgkqhkiG9w0BCQQxFgQUGQg5NIxN/6WyoSxr
3Ji5FieZIEYwgaoGCyqGSIb3DQEJEAIMMYGaMIGXMIGUMHoEFCrI4KGRWH7avLa87BteZ6dEH13n
MGIwVKRSMFAxCzAJBgNVBAYTAkxWMSgwJgYDVQQLEx9TZXJ0aWZpa2FjaWphcyBwYWthbHBvanVt
dSBkYWxhMRcwFQYDVQQDEw5FLU1FIFBTSSAoUENBKQIKFHhXTwABAAAAKTAWBBS6fvOgpMHVt1J7
2376rk14aZlDLzANBgkqhkiG9w0BAQUFAASCAQAaw1P0tZiGUhL7VUo5iEQqaqldNHFVucJ8SHMu
gUTEfeKTVxMP1PcJEFFs0BaNf7QELUlcpQN3MGUyAgRdD0Is736a/x3JIfMBI2P5XUrH9gbRzGsC
wb0dvb96uWnAQbfuDXA9MoIpOMPFzn7WzbmWWIlkfWIRGwhp3ZGeLA9igIATz9eB5Ca3QKlwWKXz
R8UrJu3MV9dOKGJfiGSH8uGduuhta1q4Bvah8fRdFlKHdKuLPj2cxJXzhOifm0DKCXg2aLhJXgGv
IzSJjUF+3CWqkDWpI1GRhv2+RXkcpk4nywc1QNu9U2yfYS22a5x6tc93wkwsJuqEFib4/MxqWysR
AAAAAA==
`

**Comment by levitte** [comment]
Hi,

I've spent some time trying to analyse the contents of TSA.ts.  `openssl asn1parse` has no problem with it, so it's not an issue with parsing the DER structure per se, it's rather about how the contents of the file is structured.

The sequence that you claim - "A1 82 02 45" - is in position 1916 of the binary data extracted from TSA.ts, and a bit of `openssl asn1parse` with a bit of filtering makes it clear what it is that OpenSSL doesn't quite like:

```
: ; openssl asn1parse -in FOO.ts -i | grep ':d=[1234] '
    2:d=1  hl=2 l=   9 prim:  OBJECT            :pkcs7-signedData
   13:d=1  hl=2 l=inf  cons:  cont [ 0 ]        
   15:d=2  hl=4 l=3116 cons:   SEQUENCE          
   19:d=3  hl=2 l=   1 prim:    INTEGER           :03
   22:d=3  hl=2 l=  11 cons:    SET               
   24:d=4  hl=2 l=   9 cons:     SEQUENCE          
   35:d=3  hl=4 l= 279 cons:    SEQUENCE          
   39:d=4  hl=2 l=  11 prim:     OBJECT            :id-smime-ct-TSTInfo
   52:d=4  hl=4 l= 262 cons:     cont [ 0 ]        
  318:d=3  hl=4 l=2179 cons:    cont [ 0 ]        
  322:d=4  hl=4 l=1590 cons:     SEQUENCE          
 1916:d=4  hl=4 l= 581 cons:     cont [ 1 ]        
 2501:d=3  hl=4 l= 630 cons:    SET               
 2505:d=4  hl=4 l= 626 cons:     SEQUENCE          
 3135:d=2  hl=2 l=   0 prim:   EOC               
 3137:d=1  hl=2 l=   0 prim:  EOC               
```

I *believe* that the `cont [0]` at position 318 corresponds to the `certificates` field in the PKCS#7 [SignedData](https://tools.ietf.org/html/rfc2315#section-9.1) type...  the `cont [1]` item within is a mystery to me, I can't quite grasp what that should be.  A collegue will hopefully help me out with that.

Just wanted you to know it's being looked into.

**Comment by levitte** [comment]
It turns out that the issue is that `TSA.ts` is a CMS structure (an evolution of PKCS#7), while the `openssl ts` command only supports wrapping the time stamp in a PKCS#7 structure...

I suggest making a feature request to support CMS tokens.

**Comment by richsalz** [comment]
Which FYI will not happen in OpenSSL 1.1, just to make it clear.
