### ISSUE TITLE
Question about DRBG security

### ISSUE THREAD

**Issue by Tomahawkd** [openssl/openssl#9933]
Environment:
- OpenSSL version: 1.1.1d from Homebrew
- OS: MacOS 10.14.6

Hello, I'm currently working on DRBG described in NIST SP800-90A rev. 1. I tested out generated bits from my DRBG impl. with Statistical Test Suite provided by [NIST](https://csrc.nist.gov/Projects/Random-Bit-Generation/Documentation-and-Software) and an enhanced version by [arcetri](https://github.com/arcetri/sts). I found that I got failures on several tests. Then I tested OpenSSL's DRBG and got the same situation.

Here is the part of my code for RAND_DRBG.
```
    RAND_DRBG *drbg = RAND_DRBG_new(NID_aes_256_ctr, RAND_DRBG_FLAG_CTR_NO_DF, NULL);

    RAND_DRBG_instantiate(drbg, NULL, 0);

    uint8_t out[32];
    FILE *file = fopen("./random", "w");
    // generate 32*32(1k)*1024(1m)*150(150m)
    for (int i = 0; i < 32 * 1024 * 150; ++i) {
        RAND_DRBG_generate(drbg, out, 32, 0, NULL, 0);
        fputs(out, file);
    }

    RAND_DRBG_uninstantiate(drbg);
    RAND_DRBG_free(drbg);
```

It writes the generated bits into a file for tools described above as an input for testing.

The question is, the DRBG algorithm could pass the test or not? Or the entropy input which is not from a random source lead to test failure? Or other things like cipher security strength?

Thank you.

**Comment by richsalz** [comment]
The algorithm that the OpenSSL DRBG code uses is fine.  The most likely issue is the entropy that you are feeding into it.

**Comment by t8m** [comment]
The bug is in your code that saves the data to the file. You cannot use fputs to write binary data as the resulting file will not contain any \0 bytes which will certainly trigger some statistical test failures. You have to use fwrite() instead.

**Comment by Tomahawkd** [comment]
aah... I just test out on the enhance version after fixing the misuse. Everything goes well now. Thanks for your help. 

By the way, I would like to ask about entropy input in DRBG. During the whole reseed interval period, DRBG uses initial entropy input (and the other things) to transform the internal state and generate bits. Before reseeding, the length generated is far more than entropy input's. How does it remain enough entropy(or security strength)? (I just a new comer to random generator and I could not understand the algorithm.)

Moreover, this is another thing I would like to learn about. 
```
DRBG_Instantiate(drbg, entropy_input) // instantiate using external entropy input
DRBG_generate(drbg, result) // generate bit string into result
DRBG_Instantiate(drbg, result) // reinstantiate DRBG using the result
DRBG_generate(drbg, output_bits) // Is output bits secure?
```
In the above pseudo code, is the reinstantiation secure? Can I consider this as the chaining DRBG described in NIST doc? (In fact, I have limitation to get external random source. And considering the similarity between reseed procedure and the instantiate procedure, I choose to reinstantiate the DRBG)

Thanks.

**Comment by kroeckx** [comment]
Entropy does not go away. The limit of how much data you can
generate from that entropy depends on the algorithm. We use some
very conservative default settings.

If you want to chain DRBGs, you use the output from 1 DRBG as
entropy source for the next DRBG. You seem to be doing that, but
then throw away the source DRBG (and reuse it). This seems like a
bad idea, and I suggest you just change the reseed intervals and
keep using the DRBG for a longer time.

**Comment by Tomahawkd** [comment]
Thanks for your advice. I'll adjust my programme and retest it.

Again, thanks all of you for help. Have a nice day:)

Now closing.
