### ISSUE TITLE
Build fails with Error: __attribute__ does not have a number assigned

### ISSUE THREAD

**Issue by MonkeybreadSoftware** [openssl/openssl#9934]
When building Openssl 1.1.1d for Linux targets, we get failures with the result:

Error: __attribute__ does not have a number assigned

Not sure what changed since 1.1.1c which causes this problem.

**Comment by MonkeybreadSoftware** [comment]
configure works:
./Configure no-unit-test no-zlib shared no-dso enable-rc5 no-async linux-generic32

> Configuring OpenSSL version 1.1.1d (0x1010104fL) for linux-generic32
> Using os-specific seed configuration
> Creating configdata.pm
> Creating Makefile

and make fails on the end with this lines:

> arm-linux-gnueabihf-gcc  -Iinclude -pthread -Wa,--noexecstack -fPIC -g1 -O2 -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -fno-omit-frame-pointer -I.. -I/Users/cs/Development/Libs/zlib/linux32arm -DNDEBUG -fPIC -g1 -O2 -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -fno-omit-frame-pointer -I.. -I/Users/cs/Development/Libs/zlib/linux32arm -MMD -MF test/lhash_test.d.tmp -MT test/lhash_test.o -c -o test/lhash_test.o test/lhash_test.c
> arm-linux-gnueabihf-gcc  -Iinclude -pthread -Wa,--noexecstack -fPIC -g1 -O2 -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -fno-omit-frame-pointer -I.. -I/Users/cs/Development/Libs/zlib/linux32arm -DNDEBUG -fPIC -g1 -O2 -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -fno-omit-frame-pointer -I.. -I/Users/cs/Development/Libs/zlib/linux32arm -MMD -MF test/md2test.d.tmp -MT test/md2test.o -c -o test/md2test.o test/md2test.c
> arm-linux-gnueabihf-gcc  -I. -Iinclude -pthread -Wa,--noexecstack -fPIC -g1 -O2 -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -fno-omit-frame-pointer -I.. -I/Users/cs/Development/Libs/zlib/linux32arm -DNDEBUG -fPIC -g1 -O2 -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -fno-omit-frame-pointer -I.. -I/Users/cs/Development/Libs/zlib/linux32arm -MMD -MF test/mdc2_internal_test.d.tmp -MT test/mdc2_internal_test.o -c -o test/mdc2_internal_test.o test/mdc2_internal_test.c
> Error: __attribute__ does not have a number assigned

We see this error with cross compiling Linux ARM on Mac as well as native compiling Linux on 32 and 64-bit machines.

**Comment by MonkeybreadSoftware** [comment]
Error is generated by mkdef.pl in line 1203.

I'll try and comment out the die and see if it builds. No idea why no number is assigned here.

**Comment by MonkeybreadSoftware** [comment]
Looks like it builds with the two lines commented out.

> 			if (!defined($nums{$s})) {
> 				# die "Error: $s does not have a number assigned2\n"
> 				# 	if(!$do_update);
> 			} else {

No idea whether this has consequences...

**Comment by richsalz** [comment]
Are you sure you are using a proper version of perl?
There's no reason that should happen.  Consider wiping your build tree and starting over.

**Comment by MonkeybreadSoftware** [comment]
Well, one computer is 5.10.1, one is 5.14.2 and one is 5.18.4 on the perl command line tool.
I would not expect perl to be the reason.

**Comment by richsalz** [comment]
So perhaps try the second thing I mentioned.  Start with a completely fresh copy of the sources.

**Comment by MonkeybreadSoftware** [comment]
This is confusing. It now works and I can't find the difference between the one which didn't worked.

**Comment by mattcaswell** [comment]
I just tried the same cross-compilation target on my Linux 64-bit machine with the same Configure params as you. Compilation was successful.

**Comment by MonkeybreadSoftware** [comment]
Today I run again into this with 1.1.1h. Strange. But commenting out the die line again makes it work.
