### ISSUE TITLE
openssl1.1.1c rpm build using spec file is showing issue during installtion

### ISSUE THREAD

**Issue by shivbindas** [openssl/openssl#9944]
Hi Team , 

I have created a rpm using openssl1.1.1c source code. my rpm created successfully with name :
openssl-1.1.1c-01.x86_64.rpm

but when i am trying to upgrade my openssl old version then its showing me error something like below :+1: 

error: Failed dependencies:
        perl(WWW::Curl::Easy) is needed by openssl-1.1.1c-01.x86_64
        openssl < 1:1.0.1-0.3.beta3 is obsoleted by (installed) openssl-libs-1:1.0.2k-19.el7.x86_64

I am not sure from where its picking up obsolete version of openssllib  - 1:1.0.1-0.3.beta3

Thanks in advance

**Comment by levitte** [comment]
This line was surprising too:

```
perl(WWW::Curl::Easy) is needed by openssl-1.1.1c-01.x86_64
```

I have no clue, and considering we don't even know what spec file you used, there's very little we can do.  Most of all, this sounds like a RPM / Fedora problem, so this may not be the right forum for your issue.

**Comment by shivbindas** [comment]
please find the spec file 




[openssl_spec.txt](https://github.com/openssl/openssl/files/3630119/openssl_spec.txt)

**Comment by shivbindas** [comment]
Kindly check the spec file and suggest me if there is any issue with this file

**Comment by levitte** [comment]
I looked, and I see nothing that stands out.

Mind you, my knowledge of RPM specs is *very* rudimentary.  I did fiddle with that eons ago (seriously, early 2000's), but haven't touched the stuff since.  If someone else knows, they'll probably say something, but otherwise, I suggest asking somewhere else.

**Comment by t8m** [comment]
I would use a different package name and definitely not add Provides: openssl = %{version}_%{release}-prodeng
You are installing it outside of the system directories so there is no sense in clashing with the system openssl packages.

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
