### ISSUE TITLE
dlopen failed: cannot locate symbol "UINT32_it" referenced by "/data/app/com.gigaiot.sasa.android-1/lib/arm64/libssl.so"

### ISSUE THREAD

**Issue by jingw96** [openssl/openssl#9978]
Hi,

I got an dlopen failed when I try to load the 64bit libssl.so which built by myself in my Android application on Android 7.1 and 5.1. Here is the error info:

Process: com.gigaiot.sasa.android:sasavideo, PID: 17292
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "UINT32_it" referenced by "/data/app/com.gigaiot.sasa.android-1/lib/arm64/libssl.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:371)
        at java.lang.System.loadLibrary(System.java:988)
        at com.seaside.core.ClientSessMgr.<clinit>(ClientSessMgr.java:23)
        at com.gigaiot.sasa.android.AppApplication.initAVModule(AppApplication.java:78)
        at com.gigaiot.sasa.android.AppApplication.getCurrentProccess(AppApplication.java:57)
        at com.gigaiot.sasa.android.AppApplication.onCreate(AppApplication.java:33)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4605)
        at android.app.ActivityThread.access$1700(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1389)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5315)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)

However, the same library can be loaded correctly for Android 9.1.

Due to the app can not load the libssl.so.1.1, I tried to build an .so file with no version info:

Step 0:
My setenv-android.sh looks like:
	
Screen Shot 2019-09-23 at 2.10.42 PM.png
Step 1:
	I run the script below:
export ANDROID_NDK_ROOT=/Users/jimwei/Library/Android/android-ndk-r10e
source ./setenv-android.sh

DIR=`pwd`
sh ./config \
        --prefix=$DIR/out \
        --openssldir=$DIR/out \
        shared no-ssl3 no-comp no-hw no-engine no-asm
Step 2:
	I Changed the soname SHLIBS in the Makefile as below: 
Screen Shot 2019-09-23 at 1.16.36 PM.png

Step 3:
make clean
make depend
make all -j8 
make install

	
Finally I got the libssl.so, and I run
nm -gC libssl.so
			and the result seems that the UINT32_it is not define :(
            000000000001a464 T TLSv1_server_method
                                                 U UINT32_it@@OPENSSL_1_1_0f

**Comment by levitte** [comment]
(1.1.0 (any letter) has reached end-of-life, so no real support for that specifically.  I recommend upgrading to 1.1.1d.  However, this may be a general problem, applicable to any OpenSSL version, so I'll answer with that in mind)

Where does `UINT32_t` come from?  As far as I know, we're not using that at all in our source.
Also, this looks very much like a type (usually downcased, i.e. `uint32_t`), so it should not appear as a symbol, at all.

**Comment by mattcaswell** [comment]
> Where does UINT32_t come from? As far as I know, we're not using that at all in our source.

The symbol is `UINT32_it`. And we do use it in our source in the ASN.1 code.

**Comment by levitte** [comment]
Oh, of course!  I had totally forgotten, obviously...

**Comment by levitte** [comment]
But...  `UINT32_it` isn't defined in libssl.so, it's defined in libcrypto.so...  this starts to sound like there's a mixup somewhere.  Why isn't the appropriate libcrypto.so loaded?

**Comment by jingw96** [comment]
I check the libcrypto.so, it do define the UINT32_it:
            00000000001c8e90 D UINT32_it
And I did load the libcrypto.so for my app :(

**Comment by jingw96** [comment]
Hi levitte and mattcaswell , I also tried with -fuse-ld=bfd while compiling libssl.so and it did not work when I loaded it in my app. So what I can try to fix it as soon as possible?

**Comment by petrovr** [comment]
jingw96 wrote:
> Hi levitte and mattcaswell , I also tried with -fuse-ld=bfd while compiling libssl.so and it did not work when I loaded it in my app. So what I can try to fix it as soon as possible?
>

What is result if you build libraries and version as part of name.
crypto -> libopenssl-{ver}.so
ssl -> libssl-{ver}.so / depend from libopenssl-{ver}.so

And in application you load ssl-{ver}, i.e. System.loadLibrary("ssl-{ver}")

Regards
Roumen

**Comment by jingw96** [comment]
> jingw96 wrote:
> Hi levitte and mattcaswell , I also tried with -fuse-ld=bfd while compiling libssl.so and it did not work when I loaded it in my app. So what I can try to fix it as soon as possible?
> What is result if you build libraries and version as part of name. crypto -> libopenssl-{ver}.so ssl -> libssl-{ver}.so / depend from libopenssl-{ver}.so And in application you load ssl-{ver}, i.e. System.loadLibrary("ssl-{ver}") Regards Roumen

So, let me understand your suggestion. 
1) Do you mean libopenssl-{ver}.so for crypto? In my mind, it is normally libcrypto.so. 
2) Do you mean libssl-{ver}.so but not libssl.so.{ver}? Usually the version num is the last part of the soname.

Regards,
Jim

**Comment by petrovr** [comment]
jingw96 wrote:
>> jingw96 wrote:
>> Hi levitte and mattcaswell , I also tried with -fuse-ld=bfd while compiling libssl.so and it did not work when I loaded it in my app. So what I can try to fix it as soon as possible?
>> What is result if you build libraries and version as part of name. crypto -> libopenssl-{ver}.so ssl -> libssl-{ver}.so / depend from libopenssl-{ver}.so And in application you load ssl-{ver}, i.e. System.loadLibrary("ssl-{ver}") Regards Roumen
> 
> So, let me understand your suggestion.
> 1) Do you mean libopenssl-{ver}.so for crypto? In my mind, it is normally libcrypto.so.

SONAME libcrypto-{ver}.so


> 2) Do you mean libssl-{ver}.so but not libssl.so.{ver}? Usually the version num is the last part of the soname.

SONAME libssl-{ver}.so ,  NEEDED  libcrypto-{ver}.so


No "version suffix"


> 
> Regards,
> Jim
> 

Goal is to avoid clash with system names.

Regards,
Roumen

**Comment by jingw96** [comment]
> jingw96 wrote:
> > jingw96 wrote: > Hi levitte and mattcaswell , I also tried with -fuse-ld=bfd while compiling libssl.so and it did not work when I loaded it in my app. So what I can try to fix it as soon as possible? > What is result if you build libraries and version as part of name. crypto -> libopenssl-{ver}.so ssl -> libssl-{ver}.so / depend from libopenssl-{ver}.so And in application you load ssl-{ver}, i.e. System.loadLibrary("ssl-{ver}") Regards Roumen So, let me understand your suggestion. 1) Do you mean libopenssl-{ver}.so for crypto? In my mind, it is normally libcrypto.so.
> SONAME libcrypto-{ver}.so
> 2) Do you mean libssl-{ver}.so but not libssl.so.{ver}? Usually the version num is the last part of the soname.
> SONAME libssl-{ver}.so , NEEDED libcrypto-{ver}.so No "version suffix"
> Regards, Jim
> Goal is to avoid clash with system names. Regards, Roumen


Thanks Roumen! Let me try it.

**Comment by jingw96** [comment]
Hi Roumen,
It seems not work for your suggestion. Any comment on it?

**Comment by petrovr** [comment]
Hi,

jingw96 wrote:
> Hi Roumen,
> It seems not work for your suggestion. Any comment on it?
> 

ReLinker is an project available on github.  Dunno if this project could 
help in reported case. May be not.


Another solution could be "super-library" - shared library created from 
static libraries(ssl+crypto and etc code).
In the past OpenSSL create shared library from static:  ... -shared ... 
-Wl,--whole-archive  ... {list of static libraries}... 
-Wl,--no-whole-archive (for gnu linker).


Regards,
Roumen

**Comment by petrovr** [comment]
This is not OpenSSL issue. What about to close?
