### ISSUE TITLE
update key  why  MAX_KEY_UPDATE_MESSAGES times

### ISSUE THREAD

**Issue by yangyangtiantianlonglong** [openssl/openssl#9985]
`
OpenSSL> version -a
OpenSSL 1.1.1a  20 Nov 2018
built on: Thu Aug 22 08:27:52 2019 UTC
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O0 -g -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM
`
https://github.com/openssl/openssl/blob/d1c28d791a7391a8dc101713cd8646df96491d03/ssl/statem/statem_locl.h#L32-L33

https://github.com/openssl/openssl/blob/d1c28d791a7391a8dc101713cd8646df96491d03/ssl/statem/statem_lib.c#L611-L620

Find RFC without related introduction， Can help explain why this MAX_KEY_UPDATE_MESSAGES is based on？

**Comment by mattcaswell** [comment]
The original idea was as a simple DoS protection mechanism, i.e. to prevent one peer from continually request key updates from the other peer. The approach was later abandoned in f6d64b5142 which appears in releases from 1.1.1b onwards.

**Comment by yangyangtiantianlonglong** [comment]
Thanks
